### ISSUE TITLE
Vote for releasing v1.1.0-rc.1

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#1002]
At least 3 approvals are needed from the 5 owners to cut https://github.com/oras-project/oras/commit/7fc68d4b18ab6d86a2ee4b596dcbdf2ad4948091 as the release branch for oras CLI v1.1.0 release. This branch will be named as `release-1.1` and tagged as `v1.1.0-rc.1` for releasing.

 - [x] Terry Howe (@TerryHowe)
 - [x] Sajay Antony (@sajayantony)
 - [x] Shiwei Zhang (@shizhMSFT)
 - [x] Steve Lasker (@SteveLasker)
 - [x] Billy Zha (@qweeah)

The release will be conducted by following the [release checklist](https://oras.land/docs/cli/developer_guide#release-checklist).

### Bug Fixes
- `oras push` and `oras attach` generates unwanted manifest file (#995)
- Path validation not enforced for `oras attach` and `oras push` (#983, #980, #973)
- Wrong error information when `--distribution-spec` is provided with invalid value (#897)  
- Tree view print bug in `oras discover` (#1003)

### New Features
- Add a new flag `--skip-delete-referrers` to allow oras commands to skip referrer index clean up (#954, #952, #915)
- Support Golang scripting (#807)

### Other Changes
- Improve UX
  - `oras pull` prints better error msg when path traversal is required (#978)
  - Mention OCI support in help doc (#904)
  - Mark filtered tag listing as experimental (#993)
- Improve Documentation
  - Fix link in contribute doc (#950)
- Update dependencies
  - Remove dependencies on docker CLI (#414)
  - Update dependency from `github.com/moby/term` to `golang.org/x/term` (#908)
- Update to golang `1.20.5`
- Improve tests
  - Generate code coverage for E2E tests (#900)
  - Added more tests (#904, #901)

Comparing to [v1.0.0](https://github.com/oras-project/oras/tree/v1.0.0), the release includes below code changes:
## What's Changed
* refactor: Logger initializes logging by @TerryHowe in https://github.com/oras-project/oras/pull/867
* test(cov): make unit tests cover more by @qweeah in https://github.com/oras-project/oras/pull/905
* refactor: add root package for Cobra commands by @qweeah in https://github.com/oras-project/oras/pull/825
* build(deps): bump github.com/docker/cli from 23.0.1+incompatible to 23.0.2+incompatible by @dependabot in https://github.com/oras-project/oras/pull/909
* refactor: unify command contexts by @qweeah in https://github.com/oras-project/oras/pull/899
* test: generate coverage profile during e2e tests by @qweeah in https://github.com/oras-project/oras/pull/903
* build(deps): bump github.com/spf13/cobra from 1.6.1 to 1.7.0 by @dependabot in https://github.com/oras-project/oras/pull/919
* refactor: replace terminal package used by `oras login` by @qweeah in https://github.com/oras-project/oras/pull/910
* test(e2e): OCI layout specs for `oras tag` by @qweeah in https://github.com/oras-project/oras/pull/902
* build(deps): bump github.com/docker/cli from 23.0.2+incompatible to 23.0.3+incompatible by @dependabot in https://github.com/oras-project/oras/pull/918
* Add make target for e2e by @sajayantony in https://github.com/oras-project/oras/pull/924
* test: make e2e coverage data in action by @qweeah in https://github.com/oras-project/oras/pull/926
* build(deps): bump github.com/docker/cli from 23.0.3+incompatible to 23.0.4+incompatible by @dependabot in https://github.com/oras-project/oras/pull/929
* feat: use oras-credential-go to do auth by @qweeah in https://github.com/oras-project/oras/pull/932
* doc: fix broken logo link by @FeynmanZhou in https://github.com/oras-project/oras/pull/935
* docs: fix broken links in README by @wangxiaoxuan273 in https://github.com/oras-project/oras/pull/937
* build: using cross compilation in docker build by @northtyphoon in https://github.com/oras-project/oras/pull/938
* build(deps): bump golang.org/x/term from 0.7.0 to 0.8.0 by @dependabot in https://github.com/oras-project/oras/pull/942
* build(deps): bump oras-go and oras-credentials-go by @qweeah in https://github.com/oras-project/oras/pull/946
* fixed the link in the file : oras/CONTRIBUTING.md by @yash7raut in https://github.com/oras-project/oras/pull/951
* build(deps): bump github.com/sirupsen/logrus from 1.9.0 to 1.9.2 by @dependabot in https://github.com/oras-project/oras/pull/953
* build: add dependabot for e2e module by @qweeah in https://github.com/oras-project/oras/pull/958
* build(deps): bump oras.land/oras-go/v2 from 2.1.0 to 2.2.0 by @dependabot in https://github.com/oras-project/oras/pull/955
* build(deps): bump github.com/oras-project/oras-credentials-go from 0.1.0 to 0.1.1 by @dependabot in https://github.com/oras-project/oras/pull/956
* build(deps): bump github.com/opencontainers/image-spec from 1.1.0-rc2 to 1.1.0-rc.3 in /test/e2e by @dependabot in https://github.com/oras-project/oras/pull/961
* build(deps): bump github.com/onsi/ginkgo/v2 from 2.9.0 to 2.9.5 in /test/e2e by @dependabot in https://github.com/oras-project/oras/pull/962
* build(deps): bump github.com/onsi/gomega from 1.27.1 to 1.27.7 in /test/e2e by @dependabot in https://github.com/oras-project/oras/pull/959
* build(deps): bump oras.land/oras-go/v2 from 2.1.0 to 2.2.0 in /test/e2e by @dependabot in https://github.com/oras-project/oras/pull/960
* build(deps): bump github.com/onsi/ginkgo/v2 from 2.9.5 to 2.9.7 in /test/e2e by @dependabot in https://github.com/oras-project/oras/pull/963
* fix: correct spec flag description by @qweeah in https://github.com/oras-project/oras/pull/964
* build(deps): bump github.com/sirupsen/logrus from 1.9.2 to 1.9.3 by @dependabot in https://github.com/oras-project/oras/pull/966
* chore: add snap for ubuntu by @SamirPS in https://github.com/oras-project/oras/pull/965
* build(deps): bump github.com/onsi/gomega from 1.27.7 to 1.27.8 in /test/e2e by @dependabot in https://github.com/oras-project/oras/pull/970
* build(deps): bump github.com/onsi/ginkgo/v2 from 2.9.7 to 2.10.0 in /test/e2e by @dependabot in https://github.com/oras-project/oras/pull/969
* chore: simplify e2e scripts and github action by @qweeah in https://github.com/oras-project/oras/pull/967
* Revert "Add help to make file" by @TerryHowe in https://github.com/oras-project/oras/pull/974
* Add help to make file by @TerryHowe in https://github.com/oras-project/oras/pull/975
* build(deps): bump golang.org/x/term from 0.8.0 to 0.9.0 by @dependabot in https://github.com/oras-project/oras/pull/971
* build(deps): bump github.com/onsi/ginkgo/v2 from 2.10.0 to 2.11.0 in /test/e2e by @dependabot in https://github.com/oras-project/oras/pull/976
* test: add unit-tests for `internal/version.go` by @enraiha0307 in https://github.com/oras-project/oras/pull/977
* build(deps): bump github.com/oras-project/oras-credentials-go from 0.1.1 to 0.2.0 by @qweeah in https://github.com/oras-project/oras/pull/990
* fix: enforce path validation for push/attach and improve path traversal failure message for pull by @suganyas in https://github.com/oras-project/oras/pull/988
* chore: add experimental mark to filtered tag listing by @qweeah in https://github.com/oras-project/oras/pull/994
* test(e2e): add test for pushing via absolute path by @qweeah in https://github.com/oras-project/oras/pull/991
* test(e2e): update spec-related constants to string literal by @qweeah in https://github.com/oras-project/oras/pull/992
* chore: update help doc with OCI layout support by @qweeah in https://github.com/oras-project/oras/pull/997
* feat: add flag to skip deleting obsolete referrers index by @qweeah in https://github.com/oras-project/oras/pull/957
* fix: pushing based on temporary file store path by @qweeah in https://github.com/oras-project/oras/pull/996
* chore: update minor version by @qweeah in https://github.com/oras-project/oras/pull/1000
* fix: properly print tree for `oras discover` by @shizhMSFT in https://github.com/oras-project/oras/pull/1005
* build(deps): bump golang.org/x/term from 0.9.0 to 0.10.0 by @dependabot in https://github.com/oras-project/oras/pull/1008
* build(deps): bump oras-go to main branch by @qweeah in https://github.com/oras-project/oras/pull/1004

**Comment by shizhMSFT** [comment]
It would be better if the long list of changes can be summarized.

**Comment by shizhMSFT** [comment]
> BREAKING CHANGE: oras blob delete and oras manifest delete return success on non-existent content when the flag --force is specified

It is not a breaking change but a behavior fix.

**Comment by qweeah** [comment]
> > BREAKING CHANGE: oras blob delete and oras manifest delete return success on non-existent content when the flag --force is specified
> 
> It is not a breaking change but a behavior fix. That is, a bug fix.

Removed from the list, it's done in 1.0.0

**Comment by FeynmanZhou** [comment]
LGTM but I am not a maintainer for ORAS CLI. 

Are there any changes that should be reflected in the ORAS documentation? I see at least `--skip-delete-referrers` should be added to the ORAS documentation accordingly. Anything else?

**Comment by shizhMSFT** [comment]
LGTM

**Comment by shizhMSFT** [comment]
@qweeah We need to consider bump up the `oras-go` version to bring the latest bug fixes. Since https://github.com/oras-project/oras-go/commit/7dd0378382c6fe8acc5e8e1ad1d4681213889799 depended by the current `oras` is a feature and is not covered by `v2.2.1`, we need to bump up to the latest `main` branch of `oras-go`.

**Comment by qweeah** [comment]
Had a discuss offline with @shizhMSFT. Will bump oras-go to https://github.com/oras-project/oras-go/commit/6b5bd4b4372b8ba8f5ec0251ddffba8f360f5cf1 to include two bug fixes on OCI layout. Will not include [image-spec 1.1.0 rc.4](https://github.com/opencontainers/image-spec/tree/v1.1.0-rc4) changes in ORAS CLI 1.1.0 release.

**Comment by sajayantony** [comment]
Check the symversion issue in image spec. We should do rc1 instead of rc.1.

**Comment by SteveLasker** [comment]
> Will not include [image-spec 1.1.0 rc.4](https://github.com/opencontainers/image-spec/tree/v1.1.0-rc4) changes in ORAS CLI 1.1.0 release.

If `oras rc.1` won't support `image-spec rc.4`, what is the plan/timeframe to sync these up?

**Comment by sajayantony** [comment]
@qweeah - I've created draft PR to see if we can move this from an issue to PR approval and also introduce the +dev semantic into the ORAS CLI so that folks building off main and not from a tag know.

**Comment by qweeah** [comment]
> Check the symversion issue in image spec. We should do rc1 instead of rc.1.

Should it be rc.x? The spec of Semantic version is using it, e.g. https://semver.org/spec/v2.0.0-rc.2.html

**Comment by qweeah** [comment]
> @qweeah - I've created draft PR to see if we can move this from an issue to PR approval and also introduce the +dev semantic into the ORAS CLI so that folks building off main and not from a tag know.

It's better not to use a PR to vote, since the PR will change the digest of last commit, which results in another vote the cutting the branch. @shizhMSFT @FeynmanZhou What's your idea on adding the +dev semantic?

**Comment by qweeah** [comment]
> > Will not include [image-spec 1.1.0 rc.4](https://github.com/opencontainers/image-spec/tree/v1.1.0-rc4) changes in ORAS CLI 1.1.0 release.
> 
> If `oras rc.1` won't support `image-spec rc.4`, what is the plan/timeframe to sync these up?

ORAS 1.1.0 and its RC will not include the changes. ORAS 1.2.0 will include the changes (https://github.com/oras-project/oras/issues/1009). But we haven't discussed the release date for 1.2.0 yet.

**Comment by shizhMSFT** [comment]
> Check the symversion issue in image spec. We should do rc1 instead of rc.1.

The `image-spec` repo has its own versioning issue. Basically, `rc.1 < rc.2 < rc.10 < rc1 < rc10 < rc2` presents a critical issue on `rc10 < rc2`.

I've also written a small program to demonstrate the version order.
```go
package main

import (
	"fmt"
	"strings"

	"golang.org/x/mod/semver"
)

func main() {
	versions := []string{
		"v1.1.0",
		"v1.1.0-rc.1",
		"v1.1.0-rc.2",
		"v1.1.0-rc.10",
		"v1.1.0-rc1",
		"v1.1.0-rc2",
		"v1.1.0-rc10",
	}
	semver.Sort(versions)
	fmt.Println(strings.Join(versions, "\n"))
}
```
The above code prints
```
v1.1.0-rc.1
v1.1.0-rc.2
v1.1.0-rc.10
v1.1.0-rc1
v1.1.0-rc10
v1.1.0-rc2
v1.1.0
```

Precisely, [SemVer 2.0.0](https://semver.org/) states

> Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows:
> 
> 1. **Identifiers consisting of only digits are compared numerically.**
> 2. **Identifiers with letters or hyphens are compared lexically in ASCII sort order.**
> 3. Numeric identifiers always have lower precedence than non-numeric identifiers.
> 4. A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal.
> 
> Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

Overall, oras should name the RC version as `vA.B.C-rc.D` instead of `vA.B.C-rcD`.

**Comment by shizhMSFT** [comment]
LGTM on cutting 7fc68d4b18ab6d86a2ee4b596dcbdf2ad4948091

**Comment by qweeah** [comment]
> > > Will not include [image-spec 1.1.0 rc.4](https://github.com/opencontainers/image-spec/tree/v1.1.0-rc4) changes in ORAS CLI 1.1.0 release.
> > 
> > 
> > If `oras rc.1` won't support `image-spec rc.4`, what is the plan/timeframe to sync these up?
> 
> ORAS 1.**1**.0 and its RC will not include the changes. ORAS 1.**2**.0 will include the changes (#1009). But we haven't discussed the release date for 1.2.0 yet.

@SteveLasker Also **oras-go hasn't implemented changes introduced by image spec 1.1.0-rc4 yet**, @Wwwsylvia only added rc4 to go.mod and made oras-go compatible to use with image spec 1.1.0-rc4 in https://github.com/oras-project/oras-go/commit/4763cd4ba3b7040dd72de5b06c970c9a9008607b. It's not possible for ORAS CLI 1.1.0 to include image spec 1.1.0-rc4 changes without underlying SDK support. Will do that in ORAS CLI 1.2.0.

**Comment by TerryHowe** [comment]
LGTM

**Comment by sajayantony** [comment]
LGTM since the symversion is not an issue for ORAS. 
I would like going forward to move this to a PR process rather than an issue.

**Comment by SteveLasker** [comment]
LGTM for cutting this release, with a hopeful quick move to image spec 1.1.0-rc4

**Comment by shizhMSFT** [comment]
Closing since `v1.1.0-rc.1` was released.
