### ISSUE TITLE
improve error log for `oras push` and `oras attach` when annotation file is invalid

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#1021]
If a malformed JSON file is provided via `--annotation-file` flag, oras will output below error log, which is hard to understand for the common user. 

> Error: json: cannot unmarshal string into Go value of type map[string]string

CLI should 
1) give hints of the provided path of JSON file is malformed, and
2) point user to the document in https://oras.land/docs/how_to_guides/manifest_annotations.

**Comment by 1Shubham7** [comment]
@qweeah Please assign me this issue.
