### ISSUE TITLE
move oras snapcraft configuration to GitHub actions

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#1052]
The [snapcraft configuration](https://github.com/oras-project/oras/blob/e6b9a44c0ecbb2b705fb5ec57e9eeb5cb20c1e0f/snapcraft.yaml) contains detail about current version and Golang version. The version-specific detail should be removed from source code and injected during building.

Snapcraft file schema: https://snapcraft.io/docs/snapcraft-schema. Also, below actions can be used to build and publish:
- https://github.com/snapcore/action-build
- https://github.com/snapcore/action-publish

**Comment by shizhMSFT** [comment]
@qweeah Could you provide a link to the documentation on how to write a snapcraft configuration?
