### ISSUE TITLE
Enable artifact guidance for ORAS

### ISSUE THREAD

**Issue by sajayantony** [oras-project/oras#1062]
### What is the version of your ORAS CLI

v1.1.0-rc1

### What would you like to be added?

Continuing the conversation here since its about an ORAS CLI experience discussion.  https://github.com/oras-project/oras-www/pull/248#issuecomment-1674110920 @qweeah 

> @sajayantony To align oras's behavior with this subtree, do we need to ban `--config` if no file specified in below scenario?

I think we can warn since this is guidance and not a MUST in the specification. 
The above example has a config file but no blob and that is not a scenario that cannot be executed but not recommended. 

Also we probably need to consider how to enable the user to pass in the config mediaType and also artifact-type. 
```
❯ oras push --config config.json:application/example.config+json  localhost:5000/oras-test:push1 --artifact-type application/example
Error: --artifact-type and --config cannot both be provided
```

### Why is this needed for ORAS?

Updated support for v1.1 

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by qweeah** [comment]
Also in the diagram of `Deciding on artifactType or config.mediaType`, there is no recommendation of not specifying `artifactType`, but it's doable via `oras push --config`, I suggest ORAS CLI give warning on that so user is aware they are not producing sth recommonded?

**Comment by qweeah** [comment]
> Also we probably need to consider how to enable the user to pass in the config mediaType and also artifact-type.

This change will be covered in #1043, when using `--image-spec v1.1`, both flags can be used.

**Comment by shizhMSFT** [comment]
What if an artifact has a config but no layers?
```json
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "artifactType": "application/vnd.example+type",
  "config": {
    "mediaType": "application/vnd.example.config.v1+json",
    "digest": "sha256:5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03",
    "size": 123
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.empty.v1+json",
      "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
      "size": 2
    }
  ]
}
```
It is technically possible but this path is currently not in the decision tree.

**Comment by shizhMSFT** [comment]
> It is technically possible but this path is currently not in the decision tree.

Oh. The decision tree actually covers it.

- Artifact has at least one file or blob? --> **Yes** since config blob is a blob
- Artifact has additional metadata config blob? -->**Yes** since we have a config blob
- Specify **artifactType**, specify config blob and mediaType, include artifact in layers. (where artifacts are empty)

**Comment by qweeah** [comment]
> Specify artifactType, specify config blob and mediaType, include artifact in layers. (where artifacts are empty)

This is not accurate, according to current l[atest version of the guide](https://github.com/oras-project/oras-www/blob/4f510fd2e92ea1ca1bb14fc5ade69bd4ce184aa7/docs/concepts/artifact.mdx#L205C1-L205C99), if there is not layer, **the config descriptor must be empty and `artifactType` must be presented**, which is not enforced in oras CLI now.

**Comment by shizhMSFT** [comment]
> This is not accurate, according to current l[atest version of the guide](https://github.com/oras-project/oras-www/blob/4f510fd2e92ea1ca1bb14fc5ade69bd4ce184aa7/docs/concepts/artifact.mdx#L205C1-L205C99), if there is no layer blob, **the config descriptor must be empty and `artifactType` must be presented**, which is not enforced in oras CLI now.

I think config blob is considered as a blob, isn't it?

**Comment by qweeah** [comment]
No, the guide explicitly callout config blob as `ConfigData`

**Comment by shizhMSFT** [comment]
LoL. `ConfigData` is just a variable to render the flowchart. BTW, you may also want to checkout https://github.com/opencontainers/image-spec/pull/1101
