### ISSUE TITLE
Winget installation is broken, it installs an older version of ORAS and is not installing the latest release

### ISSUE THREAD

**Issue by asilverman** [oras-project/oras#1063]
### What happened in your environment?

```bash
$ winget search ORASProject.ORAS
Name     Id               Version Source
-----------------------------------------
ORAS CLI ORASProject.ORAS 1.0.0   winget
```

From the DOCS:
![image](https://github.com/oras-project/oras/assets/9611108/772d9d95-51a8-446b-a764-63a0da8a3783)

Notice how the winget package manager is finding the latest version to be 1.0.0, however version 1.0.1 is already released.
![image](https://github.com/oras-project/oras/assets/9611108/36f70259-9d74-49d3-b3bf-da4918d3bbde)

BTW the version in the docs for the alternative is also wrong
![image](https://github.com/oras-project/oras/assets/9611108/1fe8c103-bfa8-422a-bb04-30528ad7e9fb)

### What did you expect to happen?

I would expect it to detect and download the latest version that was released but it doesn't do that, it downloads an old version

### How can we reproduce it?

run `winget search oras`

### What is the version of your ORAS CLI?

N\A

### What is your OS environment?

Win11

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by qweeah** [comment]
Raised a PR to add oras 1.0.1 to winget, see https://github.com/microsoft/winget-pkgs/pull/117234

**Comment by asilverman** [comment]
Looks like the PR was merged but the issue remains since there are no guarantees that the maintainers will remember to manually issue a PR for future releases. @FeynmanZhou are there any plans to automate this process?

**Comment by qweeah** [comment]
> are there any plans to automate this process?

Yes, you are right. It's tracked in https://github.com/oras-project/oras/issues/1025. I think for Winget we can utilize winget-create to raise a PR after releasing.

> Also, @qweeah the documentation is still not updated to reflect the new version and this is true for all platforms, not just windows

Please check https://github.com/oras-project/oras-www/pull/251, which is pending for merge @FeynmanZhou can you help approve.

**Comment by asilverman** [comment]
Fixed
