### ISSUE TITLE
support `--platform` in `oras push` and `oras attach`

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#1066]
### What is the version of your ORAS CLI

oras v1.1.0-rc.1

### What would you like to be added?

Add a new flag `--platform`(flag name TBD) to allow baking platform information into config data like
```shell
oras push localhost:5000/oras:v1.0.1 --artifact-type "application/vnd.example+type" --platform linux/amd64 oras--1.0.1.arm64_monterey.bottle.tar.gz
oras attach localhost:5000/oras:v1.0.1 --artifact-type "application/vnd.sbom" --platform linux/amd64 oras--1.0.1.arm64_monterey.bottle.tar.gz
```

The specified platform information will be stored in the config blob like https://oras.land/docs/concepts/artifact#artifacts-with-config

### Why is this needed for ORAS?

User can easily build artifact with platform information without composing config blob on their own.

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by amands98** [comment]
Should I include support for a platform flag ? // @qweeah

**Comment by qweeah** [comment]
@amands98 Thanks for volunteering! Please make sure the baked config is following https://github.com/opencontainers/image-spec/blob/main/config.md#properties

**Comment by shizhMSFT** [comment]
What's the media type of the config? Is it artifact-type or the standard config type? How is it supported by multiple cloud providers?

**Comment by wangxiaoxuan273** [comment]
Looks like `--platform` for `oras attach` is already completed: #813 #1309

**Comment by qweeah** [comment]
Still need to apply this to `oras attach`

**Comment by TerryHowe** [comment]
`oras atach` has a platform option although I haven't tried it

**Comment by Wwwsylvia** [comment]
> Still need to apply this to oras attach

Do you mean we can add a `--artifact-platform` flag to the manifest of the config referrers, just like we do for `oras push`?

> oras atach has a platform option although I haven't tried it

That is to control which arch-specific manifest to attach on.

---
But what are the use cases of adding platform to a referrer?🤔

**Comment by FeynmanZhou** [comment]
> Still need to apply this to `oras attach`

Since we lack of the scenario for `oras attach`, we will keep it in ORAS future milestone.

**Comment by TerryHowe** [comment]
I think a new issue for attach would make it easier

**Comment by Wwwsylvia** [comment]
I just opened a new issue for `oras attach`: https://github.com/oras-project/oras/issues/1537
I think we are good to close this one.
