### ISSUE TITLE
Improve verbose logging for oras commands

### ISSUE THREAD

**Issue by sajayantony** [oras-project/oras#1091]
Tracking issue to list out verbose logging improvements for oras 

- #911

Discussion that might help formalize the thinking for various commands - https://hackmd.io/fvLyJ4NLSkKJug1JpOcsbA?view

**Comment by FeynmanZhou** [comment]
We need to design the tree view holistically in the verbose output mode in v1.3.0.

Linking https://github.com/oras-project/oras/pull/1199#discussion_r1597328441

**Comment by Wwwsylvia** [comment]
This can be broken down into 4 sub-tasks:
- #1533 
- #1534 
- #1535 
- #1536
