### ISSUE TITLE
oras tries to use http instead of https

### ISSUE THREAD

**Issue by erikschul** [oras-project/oras#1106]
### What happened in your environment?

When executing command `oras repo ls localhost`
I get this error:
```
Error: Get "http://localhost/v2/_catalog": dial tcp [::1]:80: connect: connection refused
```

There is no argument for using https, only for using http (`--plain-http`), so what's going wrong?

### How can we reproduce it?

.

### What is the version of your ORAS CLI?

Version:    1.1.0+Homebrew
Go version: go1.21.0

### What is your OS environment?

MacOS

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by qweeah** [comment]
@erikschul Thanks for reporting this bug. Confirmed that `--plain-http` doesn't work for `localhost`

**Comment by qweeah** [comment]
@erikschul There is a workaround, you may force the hostname to be not localhost like using `--resolve <mock-host>:443:0.0.0.0` as below:
```shell
oras repo ls my.registry --resolve my.registry:443:0.0.0.0
```
