### ISSUE TITLE
`oras discover` should show a placeholder of `artifactType` if it's not presented in an index referrer

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#1108]
### What is the version of your ORAS CLI

1.1.0

### What would you like to be added?

Currently `oras discover` shows an empty node when `artifactType` if it's not presented in an index referrer,  like

```console
✗ oras discover -o tree localhost:5000/test:multi
localhost:7000/command/artifacts@sha256:e2bfc9cc6a84ec2d7365b5a28c6bc5806b7fa581c9ad7883be955a64e3cc034f
├── referrer/index
│   └── sha256:d37baf66300b9006b0f4c7102075d56b970fbf910be5c6bca07fdbb000dfa383
└── 
    └── sha256:7679bc22c33b87aa345c6950a993db98a6df7a6cc77a35c388908a3
```

Should use a placeholder for the empty `artifactType`, like `<nil>` since `fmt.Println(nil)` prints `<nil>`
```console
✗ oras discover -o tree localhost:5000/test:multi
localhost:7000/command/artifacts@sha256:e2bfc9cc6a84ec2d7365b5a28c6bc5806b7fa581c9ad7883be955a64e3cc034f
├── referrer/index
│   └── sha256:d37baf66300b9006b0f4c7102075d56b970fbf910be5c6bca07fdbb000dfa383
└── <nil>
    └── sha256:7679bc22c33b87aa345c6950a993db98a6df7a6cc77a35c388908a3
```

### Why is this needed for ORAS?

Showing an empty node makes no sense and will confuse our user.

### Are you willing to submit PRs to contribute to this feature?

- [X] Yes, I am willing to implement it.

**Comment by wangxiaoxuan273** [comment]
I'd like to work on this item
