### ISSUE TITLE
Sign release artifacts with cosign

### ISSUE THREAD

**Issue by kranurag7** [oras-project/oras#1110]
### What is the version of your ORAS CLI

1.1.0

### What would you like to be added?

The release artifacts as of now are signed by GPG keys and can be verified in the following ways. 

### using checksums
```bash
curl -LO https://github.com/oras-project/oras/releases/download/v1.1.0/oras_1.1.0_checksums.txt
curl -LO https://github.com/oras-project/oras/releases/download/v1.1.0/oras_1.1.0_linux_amd64.tar.gz
diff <(awk '/linux_amd64/ {print $0}' oras_1.1.0_checksums.txt) <(sha256sum oras_1.1.0_linux_amd64.tar.gz)
echo $?
```
### using GPG keys 

```bash
$ curl -sLS https://github.com/qweeah.gpg > public.key
$ gpg --import public.key
gpg: key 276D8A724CE1C704: "Billy Zha <jinzha1@microsoft.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
$ gpg --verify oras_1.1.0_linux_amd64.tar.gz.asc oras_1.1.0_linux_amd64.tar.gz
gpg: Signature made Tue 05 Sep 2023 01:43:08 AM UTC
gpg:                using RSA key BE6FA8DDA48D4C230091A0A9276D8A724CE1C704
gpg: Good signature from "Billy Zha <jinzha1@microsoft.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: BE6F A8DD A48D 4C23 0091  A0A9 276D 8A72 4CE1 C704
```
We (me & @developer-guy) want to sign the artifacts (tarballs and container image) with [cosign](https://github.com/sigstore/cosign). This would include changes in the workflows files related to releasing [binaries](https://github.com/oras-project/oras/blob/main/.github/workflows/release-github.yml) and [images](https://github.com/oras-project/oras/blob/main/.github/workflows/release-ghcr.yml). 

### Why is this needed for ORAS?

This will help in verification of oras artifacts without the need of importing public keys. Users will be able to [verify](https://docs.sigstore.dev/verifying/verify/#keyless-verification-using-openid-connect) the artifacts with a single `cosign verify` command for images and `cosign verify-blob` with arguments, signatures and certs for tarballs if we sign our artifacts with keyless signing. 

Here's a detailed [reference](https://github.com/opentffoundation/opentf/issues/307#issuecomment-1708413711) on reason to avoid GPG keys by Jason. 

### Are you willing to submit PRs to contribute to this feature?

- [X] Yes, I am willing to implement it.

**Comment by developer-guy** [comment]
Super excited about that 😂

**Comment by TerryHowe** [comment]
I'm not sure we should close this
