### ISSUE TITLE
Binaries are missing for ppc64le and riscv64

### ISSUE THREAD

**Issue by AkihiroSuda** [oras-project/oras#1111]
https://github.com/oras-project/oras/releases/tag/v1.1.0

Would it be possible to add binaries for ppc64le and riscv64?

Not obvious for me how to do so though
https://github.com/oras-project/oras/blob/ed1a9e6a5564d1b3cdc6301c09d3ee89f4434227/.github/workflows/release-github.yml#L33-L39

**Comment by qweeah** [comment]
Since both archs are supported by golang 1.21, we can add that easily in 1.20

**Comment by qweeah** [comment]
Also, `ppc64le` can be added to the supported platform of oras CLI container image. `riscv64` is not supported by `docker.io/library/alpine:3.17.1` so it's out of option.

**Comment by qweeah** [comment]
> Not obvious for me how to do so though

New targets like `build-linux-ppc64le` and `build-linux-riscv64` need to be added to `build-linux` target in the Makefile.


@AkihiroSuda Also may I know what are the scenarios of using oras on ppc64le and riscv64? Need to know since if we add new platforms in, we need to make extra effort to support.

**Comment by AkihiroSuda** [comment]
> @AkihiroSuda Also may I know what are the scenarios of using oras on ppc64le and riscv64? Need to know since if we add new platforms in, we need to make extra effort to support.

I don't think I'll actually use these platforms by myself, but having multi-platform ORAS binaries will help creating thirdparty multi-platform tools that will depend on ORAS.

**Comment by TerryHowe** [comment]
If we build these, do we support them? Seems like we'd be taking on a lot to support this.

**Comment by FeynmanZhou** [comment]
> If we build these, do we support them? Seems like we'd be taking on a lot to support this.

+1. Should we add basic test coverage for these two platforms if ORAS releases binary for them?

**Comment by qweeah** [comment]
> > If we build these, do we support them? Seems like we'd be taking on a lot to support this.
> 
> +1. Should we add basic test coverage for these two platforms if ORAS releases binary for them?

Currently we don't have resource to validate binaries on ppcle64 and riscv

**Comment by FeynmanZhou** [comment]
I think it's worth mentioning that these binaries are available but not fully tested and have limited support if we add them to the release build assets.
