### ISSUE TITLE
oras discover gives wrong artifact type

### ISSUE THREAD

**Issue by wy65701436** [oras-project/oras#1127]
### What happened in your environment?

I successfully pushed an SBOM to my registry and the pushing process worked fine for me. I used the following command:

`oras attach --annotation "creator=Yan" --annotation "Type=Software Bill of Materials"  --artifact-type application/vnd.oci.sbom.v1+json --distribution-spec v1.1-referrers-api {my_registry}/library/registry:2 sbom.cdx.json`

However, when I attempted to use oras discover with version v1.1.0, I encountered incorrect results. 
```
oras discover --distribution-spec v1.1-referrers-api {my_registry}/library/registry:2
Discovered 2 artifacts referencing 2
Digest: sha256:10ecc12177735e5a6fd6fa0127202776128d860ed7ab0341780ddaeb1f6dfe61

Artifact Type                           Digest
application/vnd.cncf.notary.signature   sha256:4560328aeb7d811111d51dbc3ffb9286c6fc3d0afc738316ecb5c64f1f351ba8
application/vnd.oci.empty.v1+json       sha256:92220f8cbda53853bc432a419a7f5d8893e1be213d75eda2b4bc73e314466c6d
```

In comparison, using version v1.0.0 provided the correct results.
```
oras discover --distribution-spec v1.1-referrers-api {my_registry}/library/registry:2
Discovered 2 artifacts referencing 2Digest: sha256:10ecc12177735e5a6fd6fa0127202776128d860ed7ab0341780ddaeb1f6dfe61

Artifact Type                           Digest
application/vnd.cncf.notary.signature   sha256:4560328aeb7d811111d51dbc3ffb9286c6fc3d0afc738316ecb5c64f1f351ba8
application/vnd.oci.sbom.v1+json        sha256:5ad834d796c3c29a04b7ece40af5a45ae9d7b9dac40e2c4623e7df9989903a97
```

### How can we reproduce it?

oras discover

### What is the version of your ORAS CLI?

v1.1.0

### What is your OS environment?

Ubuntu 20.04

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by qweeah** [comment]
@wy65701436 Which registry are you using?

**Comment by wy65701436** [comment]
The latest Harbor, v2.9.0

**Comment by qweeah** [comment]
This is expected. Harbor's implementation of referrers API follows [OCI distribution spec v1.1.0-rc2](https://github.com/opencontainers/distribution-spec/releases/tag/v1.1.0-rc2). It's expected that Harbor's Referrers API will return wrong artifact type for artifacts generated by `oras(1.1.0) attach`
- oras v1.0.0 attach generates oci-image-spec-v1.1.0-rc.2-compliant artifact, the artifact type comes from `manifest.config.mediaType`
- oras v1.1.0 attach generates oci-image-spec-v1.1.0-rc.4-compliant artifact. If `--config` is not used, the artifact type comes from `manifest.artifactType` and `manifest.config` is set to [empty descriptor](https://github.com/opencontainers/image-spec/blob/d881fa897c6b29057813e943d3e37d3d3985a51f/manifest.md#guidance-for-an-empty-descriptor)
- Referrer API implementation following OCI Distribution-spec v1.1.0-rc2 will return artifact type as `manifest.config.mediaType` , which is always `application/vnd.oci.empty.v1+json` for artifacts generated by oras attach (1.1.0)

**Comment by FeynmanZhou** [comment]
I think we can document this case especially when users are using ORAS v1.1.0 with [OCI distribution spec v1.1.0-rc2](https://github.com/opencontainers/distribution-spec/releases/tag/v1.1.0-rc2) compliant registry. Users may not be aware of [empty descriptor](https://github.com/opencontainers/image-spec/blob/d881fa897c6b29057813e943d3e37d3d3985a51f/manifest.md#guidance-for-an-empty-descriptor) and which OCI spec version that the registry implements.
