### ISSUE TITLE
Adding a new workflow to build a container image tagged main on PR merge

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#1155]
It would be useful to have a Github workflow that automatically builds a container image whenever a PR is merged into the main branch. In this way, users can play with features from the latest version of the code easily via running a GHCR image without having to build it themselves.

**Comment by FeynmanZhou** [comment]
@vsoch Are you expecting an ORAS image with a `latest` flag automatically built from the main branch for non-prod environment? Is this issue https://github.com/oras-project/oras/issues/1155 meet your expectation?

@qweeah For PRs that are not merged yet, what's the purpose of building an image? Is it for dev preview purposes?

**Comment by qweeah** [comment]
> @qweeah For PRs that are not merged yet, what's the purpose of building an image? Is it for dev preview purposes?

If a PR is not merged, it will not be included in the dev image.

**Comment by vsoch** [comment]
If you find PRs are regular, you can also do a nightly or even bi-weekly build instead. That would accomplish the same I think and give you more control of the frequency.

**Comment by kranurag7** [comment]
Hey @qweeah I took a look at the issue. 
As of now, we don't have any image here with `latest` tag. 

<details><summary>Details</summary>
<p>

```bash
$ oras repo tags ghcr.io/oras-project/oras
v0.12.0
v0.2.0-alpha.1
v0.2.1-alpha.1
v0.13.0
v0.14.0
v0.14.1
v0.15.0
v0.15.1
v0.16.0
v1.0.0-rc.1
v1.0.0-rc.2
v1.0.0
v1.1.0-rc.1
v1.0.1
v1.1.0-rc.2
v1.1.0
```

</p>
</details> 

If you want to have the latest image tag whenever we create a commit on `main` then I can add another workflow similar to what we use to releasing image with tag. 
The only requirement will be to removing the tags filter when the workflow is trigger. 
https://github.com/oras-project/oras/blob/01e9cdd6353c498e89e163b8ecf44fc0a8e69186/.github/workflows/release-ghcr.yml#L18-L19

Then the trigger for the new target will be: 
```yaml
on:
  push:
    branches: [main]
```

**Comment by qweeah** [comment]
@kranurag7 Thanks for volunteering. `main` sounds more like a better option to me. `latest` should be used to point to a stable version.
