### ISSUE TITLE
add reference details to output errors

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#1156]
### What is the version of your ORAS CLI

oras 1.1.0

### What would you like to be added?

Some oras commands like `oras copy`, `oras discover` and `oras attach` require user to specify a tag or digest. If not provided, oras would output error information like:

> invalid image reference, expecting <name:tag|name@digest>

oras should output more specific error info like:
> no tag or digest when expecting <name:tag|name@digest>

### Why is this needed for ORAS?

It would make error message more friendly to newbie users who are not familiar with concepts like image reference.

### Are you willing to submit PRs to contribute to this feature?

- [X] Yes, I am willing to implement it.

**Comment by qweeah** [comment]
#1152 solves this for remote registry targets, extra work need to be done for OCI layout targets.

**Comment by FeynmanZhou** [comment]
Could you change the issue title to add reference details to error messages for OCI layout and registry? I think the major intention of this issue is to improve the error messages for OCI layout as well as some cases that across two targets.
