### ISSUE TITLE
`oras pull` returns a `403: Denied` error on public package when logged in with expired PAT

### ISSUE THREAD

**Issue by AaronCrawfis** [oras-project/oras#1161]
### What happened in your environment?

1. I begin by logging into GHCR:
   ```powershell
   $ docker login ghcr.io -u AaronCrawfis --password **************
   WARNING! Using --password via the CLI is insecure. Use --password-stdin.
   Login Succeeded
   ```
1. I then create a file and push it to my remote GHCR artifact:
   ```powershell
   $ echo "Hello World" > test.txt
   $ oras push ghcr.io/aaroncrawfis/test:latest .\test.txt
   Uploading b08022d315cf test.txt
   Uploaded  b08022d315cf test.txt
   Pushed ghcr.io/aaroncrawfis/test:latest
   Digest: sha256:bdfada6304e53648d7d8adfb0c80fa5d0700ab2fcece5455bdf0eb6082ea2108
   ```
1. I go into the GitHub Packages UI and make my package public ([link](https://github.com/users/AaronCrawfis/packages/container/package/test))
1. I'm able to remove the file and pull it back down to show that it works:
   ```powershell
   $ rm .\test.txt
   $ oras pull ghcr.io/aaroncrawfis/test:latest
   Downloading b08022d315cf test.txt
   Downloaded  b08022d315cf test.txt
   Pulled ghcr.io/aaroncrawfis/test:latest
   Digest: sha256:bdfada6304e53648d7d8adfb0c80fa5d0700ab2fcece5455bdf0eb6082ea2108
   ```
1. I now go into my PAT and regenerate the token, invalidating the old one. (I could also delete the PAT to invalidate the current token):
   ```powershell
   $ rm .\test.txt
   $ oras pull ghcr.io/aaroncrawfis/test:latest --debug
   time=2023-11-01T08:22:57-07:00 level=debug msg= Request URL: "https://ghcr.io/v2/aaroncrawfis/test/manifests/latest"
   time=2023-11-01T08:22:57-07:00 level=debug msg= Request method: "GET"
   time=2023-11-01T08:22:57-07:00 level=debug msg= Request headers:
   time=2023-11-01T08:22:57-07:00 level=debug msg=   "Accept": "application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, application/vnd.oci.artifact.manifest.v1+json"
   time=2023-11-01T08:22:57-07:00 level=debug msg=   "User-Agent": "oras/0.16.0"
   time=2023-11-01T08:22:57-07:00 level=debug msg= Response Status: "401 Unauthorized"
   time=2023-11-01T08:22:57-07:00 level=debug msg= Response headers:
   time=2023-11-01T08:22:57-07:00 level=debug msg=   "Content-Type": "application/json"
   time=2023-11-01T08:22:57-07:00 level=debug msg=   "Www-Authenticate": "Bearer realm=\"https://ghcr.io/token\",service=\"ghcr.io\",scope=\"repository:aaroncrawfis/test:pull\""
   time=2023-11-01T08:22:57-07:00 level=debug msg=   "Date": "Wed, 01 Nov 2023 15:22:58 GMT"
   time=2023-11-01T08:22:57-07:00 level=debug msg=   "Content-Length": "73"
   time=2023-11-01T08:22:57-07:00 level=debug msg=   "X-Github-Request-Id": "DEA0:DFA35:2A300:51371:65426D51"
   time=2023-11-01T08:22:58-07:00 level=debug msg= Request URL: "https://ghcr.io/token?scope=repository%3Aaaroncrawfis%2Ftest%3Apull&service=ghcr.io"
   time=2023-11-01T08:22:58-07:00 level=debug msg= Request method: "GET"
   time=2023-11-01T08:22:58-07:00 level=debug msg= Request headers:
   time=2023-11-01T08:22:58-07:00 level=debug msg=   "Authorization": "*****"
   time=2023-11-01T08:22:58-07:00 level=debug msg=   "User-Agent": "oras/0.16.0"
   time=2023-11-01T08:22:58-07:00 level=debug msg= Response Status: "403 Forbidden"
   time=2023-11-01T08:22:58-07:00 level=debug msg= Response headers:
   time=2023-11-01T08:22:58-07:00 level=debug msg=   "Content-Type": "application/json"
   time=2023-11-01T08:22:58-07:00 level=debug msg=   "Docker-Distribution-Api-Version": "registry/2.0"
   time=2023-11-01T08:22:58-07:00 level=debug msg=   "Date": "Wed, 01 Nov 2023 15:22:58 GMT"
   time=2023-11-01T08:22:58-07:00 level=debug msg=   "Content-Length": "50"
   time=2023-11-01T08:22:58-07:00 level=debug msg=   "X-Github-Request-Id": "DEA0:DFA35:2A301:51373:65426D52"
   Error: GET "https://ghcr.io/v2/aaroncrawfis/test/manifests/latest": GET "https://ghcr.io/token?scope=repository%3Aaaroncrawfis%2Ftest%3Apull&service=ghcr.io": response status code 403: denied: denied


### What did you expect to happen?

I expected my `oras pull` to succeed because the GitHub package is public. A `403: Denied` error tells me that I'm not authorized to pull, which is confusing because anyone can pull the public package.

I'd love if the oras client could retry a pull anonymously if an authenticated pull fails. A warning or message indicating it's retrying via an unauthenticated call would be ok.

### How can we reproduce it?

See above steps

### What is the version of your ORAS CLI?

```powershell
oras version
Version:        0.16.0
Go version:     go1.19.2
Git commit:     d606fed4be252fd6162f63548e024451c31f3864
Git tree state: clean
```

### What is your OS environment?

Windows 11

### Are you willing to submit PRs to fix it?

- [X] Yes, I am willing to fix it.

**Comment by qweeah** [comment]
Thanks @AaronCrawfis for reporting this issue. ORAS only maintains 2 latest minor versions so 0.16.0 is not expected be patched for any update in the future.

**Comment by qweeah** [comment]
From oras' context, it's hard to know whether the target ghcr repository is public or not, suggest to use `oras logout ghcr.io` to explicitly clean the token if it's intended to pull from a public ghcr repository.

**Comment by AaronCrawfis** [comment]
Thanks @qweeah! Installed 1.1 and confirmed the behavior is the same:

```
PS C:\scratch\oras> oras version
Version:        1.1.0
Go version:     go1.21.0
Git commit:     7079c468a06fb5815c99395eb4aaf46dd459d3fa
Git tree state: clean
PS C:\scratch\oras> oras pull ghcr.io/aaroncrawfis/test:latest
Error: failed to resolve latest: GET "https://ghcr.io/v2/aaroncrawfis/test/manifests/latest": GET "https://ghcr.io/token?scope=repository%3Aaaroncrawfis%2Ftest%3Apull&service=ghcr.io": response status code 403: denied: denied
```

We're starting to get some bug reports over at https://github.com/radius-project/radius due to out usage of GHCR for some of our CLI downloads: https://github.com/radius-project/radius/issues/6597. Since ghcr uses paths instead of subdomains for all registries, if a user logs into their own registry (`ghcr.io/AaronCrawfis`) and then tries to download Radius (`ghcr.io/radius-project`) it throws an error.

In the oras library, thoughts on having an option to opt-in to an unauthenticated retry if the authenticated attempt fails? That way a user's local token could be used to access private assets and prevent rate-limiting if it's available, but then if that fails due to an expiry they could still access public packages. That way the failure mode is to still have a successful download instead of a hard error.

**Comment by qweeah** [comment]
> if a user logs into their own registry (ghcr.io/AaronCrawfis) and then tries to download Radius (ghcr.io/radius-project) it throws an error.

If you need to auth across different repository in the same registry with different credential, the best practice is to use dedicated registry authentication files via `--registry-config` flag. By default `oras` follow the implementation of `docker` and uses `$HOME/.docker/config.json`

**Comment by qweeah** [comment]
> In the oras library, thoughts on having an option to opt-in to an unauthenticated retry if the authenticated attempt fails?

This is a doable feature but IMHO it should be prioritized @FeynmanZhou. 

- On one hand, as I mentioned, ORAS user should use different registry auth config file to segregate credentials for different repositories in a monolithic registry. 

- On the other hand, if the target can be anonymously pulled from, helping ORAS user ignore expired credential with a best-effort retry does not sounds like a stable solution. On the contrary, I think provide a flag to let user force anonymous pull makes more sense.

**Comment by Wwwsylvia** [comment]
> On the other hand, if the target can be anonymously pulled from, helping ORAS user ignore expired credential with a best-effort retry does not sounds like a stable solution. 

Agreed. Automatically retrying failed pulls doesn't sound necessary in most cases. 

> On the contrary, I think provide a new option to let user force anonymous pull makes more sense. 

+1. This would allow users to manually retry the failed command with an anonymous identity when needed. To implement this option, ORAS CLI can pass an empty credential to `oras-go`.

**Comment by FeynmanZhou** [comment]
According to a discussion in the community meeting on Nov 8, ORAS will not support retrying to pull anonymously from a registry if the token is expired.

**Comment by AaronCrawfis** [comment]
> Does this workaround work for you?

Yeah I'm ok with this this given the need for extra requests. We've implemented a workaround to always send an unauthenticated request to GHCR instead of using the user's tokens so we hope our users won't hit this in the future. Thanks!
