### ISSUE TITLE
FreeBSD builds

### ISSUE THREAD

**Issue by tmaroschik** [oras-project/oras#1179]
### What would you like to be added?

We would like to use oras cli to pull artifacts on FreeBSD based servers. Unfortunately the darwin builds aren't compatible.

### Why is this needed for ORAS?

This would expand the potential user base to all popular systems.

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by shizhMSFT** [comment]
BSD is the 2nd large UNIX / UNIX-like system family (around 0.1% - 0.2%) [1]. Although Darwin is derived from BSD, the binaries are not compatible. BTW, I am not sure if FreeBSD binaries can be run in NetBSD or OpenBSD.

@tmaroschik What's the CPU architecture of your FreeBSD based server? Have you tried those Linux binaries as BSDs are compatible with Linux ones?

@FeynmanZhou We definitely need tiers of OS / Arch support.

Reference:
[1] from Bing Chat

**Comment by tmaroschik** [comment]
@shizhMSFT We're on 13.2 and amd64. Unfortunately the linux builds don't work as they quit with `ELF binary type "0" not known.`

**Comment by FeynmanZhou** [comment]
I am curious what is the major scenario of using ORAS CLI on FreeBSD :-)

**Comment by FeynmanZhou** [comment]
Thanks for sharing your scenario. 

For new Arch and OS support, ORAS welcomes contributions from the community. For example, there was a new Arch added to the ORAS build and release flow, see https://github.com/oras-project/oras/pull/1118/

@tmaroschik Are you interested in adding FreeBSD to ORAS build process?

**Comment by tmaroschik** [comment]
@kranurag7 Already went ahead and implemented the build. I verified that the build works on our freebsd 13.2 on amd64. Thanks a lot!
