### ISSUE TITLE
Consider using latest during resolve when tag is not provided

### ISSUE THREAD

**Issue by kranurag7** [oras-project/oras#1193]
### What is the version of your ORAS CLI

main 

### What would you like to be added?

This is a feature request which is an extension to this [pull request](https://github.com/oras-project/oras/pull/1187). This issue requests consideration of falling back to using `latest` when the tag is not provided by the user. 

### Why is this needed for ORAS?

Most of the project use `latest` tag for their dev/staging images. It will be helpful and a good default (IMHO) when it comes to getting the digest of the `latest` image quickly without explicitly mentioning latest tag every time.  

### Are you willing to submit PRs to contribute to this feature?

- [X] Yes, I am willing to implement it.

**Comment by qweeah** [comment]
Tagging a manifest as latest is not a good practice although it is a convention in docker. Many tools like containerd/ctr has dropped the default value of latest. More tagging strategies can be found at [Docker Tagging: Best practices for tagging and versioning docker images – Steve Lasker](https://stevelasker.blog/2018/03/01/docker-tagging-best-practices-for-tagging-and-versioning-docker-images/).
Additionally, oras support pushing without a tag while it is not supported by docker.

**Comment by kranurag7** [comment]
Thanks for the feedback and reference @qweeah 
I think we are good to close this.
