### ISSUE TITLE
Add --dry-run option

### ISSUE THREAD

**Issue by guettli** [oras-project/oras#1198]
### What is the version of your ORAS CLI

1.1.0+Homebrew

### What would you like to be added?

I would like to have a `--dry-run` option.

### Why is this needed for ORAS?

I create machine images (not container images). This takes roughly 12 minutes.

Before starting that I would like to do a check if the current user is allowed to upload to the registry.

My desired steps would be:

1. check if upload is allowed: `oras push --dry-run URL empty-file`. Stop if this fails.
2. create machine image (takes long)
3. do the real `oras push`.

I was not able to create this feature request without activating the checkbox "Yes, I am willing to implement it". Is this intended?

Yes, I am willing. But first I need to do some other work. Maybe in the next summer vacation (six months from now).

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by qweeah** [comment]
ORAS CLI need to push a minimal artifact to the registry to test if the current user is allowed to upload anything to the registry. Since the test pushing would involve write operation, it's not possible to do dry-run check for `oras push`
