### ISSUE TITLE
oras pull/push task for azure devops pipeline not available?

### ISSUE THREAD

**Issue by ashutoshNeu** [oras-project/oras#1203]
### What would you like to be added?

Support for azure devops.  

### Why is this needed for ORAS?

I want to pull a repo from ACR from azure devops pipeline where I need ocar task. But could not find it

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by qweeah** [comment]
Which image are you using? ORAS is pre-installed on Ubuntu and you can use `oras` natively in shell jobs (Please check https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software. )

**Comment by ashutoshNeu** [comment]
thanks, I was not aware.
