### ISSUE TITLE
improve error message

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#1218]
According to the error message guide (see [PR](https://github.com/oras-project/oras/pull/1163)), below works need to be done:
- [x] #1210
- [x] #1211
- [x] #1212
- [x] #1213
- [x] #1214
- [x] #1215
- [x] #1216
- [x] #1217
- [x] #1236

All issues might change since the guideline hasn't got merged yet.

**Comment by amands98** [comment]
Are you currently working on this task, or should I handle it? // @qweeah @yizha1

**Comment by qweeah** [comment]
@amands98 Yes I am working on it.

**Comment by amands98** [comment]
Can I help you ?

**Comment by qweeah** [comment]
@amands98 Thanks for volunteering. #1217 is still not taken but it's planned in the next release [v1.2.0](https://github.com/oras-project/oras/milestone/17). Considering the time urgency, I suggest to commit on future items, e.g. #1066

**Comment by qweeah** [comment]
Closing as all sub-issues are completed
