### ISSUE TITLE
Help message is not properly rendered for `oras attach`

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#1225]
### What happened in your environment?

```console
$ oras attach --help
...
Flags:
...
      --distribution-spec string                   [Preview] set OCI distribution spec version and API option for target. Options: %!(EXTRA string=v1.1-referrers-tag, v1.1-referrers-api)
...
```
`Options` is not rendered correctly.

### What did you expect to happen?

It should be corrected as
```
Options: v1.1-referrers-tag, v1.1-referrers-api
```

### How can we reproduce it?

Run `oras attach --help`

### What is the version of your ORAS CLI?

Version:        1.1.0+unreleased
Go version:     go1.21.0
Git commit:     564bd3202e8fade9a23e2bbc202ba7e30927d771
Git tree state: clean

### What is your OS environment?

Ubuntu 22.04

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by FeynmanZhou** [comment]
It is renderer correctly on my Ubuntu machine. 

```
 --distribution-spec string                   [Preview] set OCI distribution spec version and API option for target. options: v1.1-referrers-api, v1.1-referrers-tag
```

My ORAS version:

```
$ oras version
Version:        1.2.0-format
Go version:     go1.21.0
Git commit:     7728d49458b06843f9d056da405971b352f4a683
Git tree state: clean
```
