### ISSUE TITLE
couldn't upload qcow2 images to harbor

### ISSUE THREAD

**Issue by mcbenjemaa** [oras-project/oras#1249]
### What happened in your environment?

I'm trying to push qcow2 images to Harbor with Oras.
But i got a weird issue:

```
Uploading bb60178e2a6c images/capi/output/ubuntu-2204-kube-v1.28.6/ubuntu-2204-kube-v1.28.6.qcow2
Error: PUT "https://harbor.infra-cluster/v2/itz-dev/ubuntu-22.04-kube/blobs/uploads/8914d340-3e97-4a3d-b75e-be7d050d498f?_state=Ze7X_YQ8MeNeF4rS65Hx1lLjYWGZzhf8x8G5_-T2Zj57Ik5hbWUiOiJpdHotZGV2L3VidW50dS0yMi4wNC1rdWJlIiwiVVVJRCI6Ijg5MTRkMzQwLTNlOTctNGEzZC1iNzVlLWJlN2QwNTBkNDk4ZiIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyNC0wMS0xOVQxODoxNzoyNi45Mzk5Nzg4NjNaIn0%3D&digest=sha256%3Abb60178e2a6c971dc96ae4b023767398b7b4a91358eb0c04565a8000b30886d6": response status code 500: unknown: unknown error: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. For more information, see REST Authentication and SOAP Authentication for details.
	status code: 403, request id: 70974918-d335-148d-9ae2-1070fde7ed2c, host id: 
```

### What did you expect to happen?

artifact uploaded 

### How can we reproduce it?

push qcow2 image

### What is the version of your ORAS CLI?

1.0.0

### What is your OS environment?

ubuntu 22.04

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by TerryHowe** [comment]
The command line you are running might help, redacted if you neeed to.

The error kind of looks like you are authing to AWS and it looks like the problem is there.

**Comment by mcbenjemaa** [comment]
Hey, 
There's nothing to do with AWS here, expect that the storage might be S3 compatible.

Here is the command line.
```
echo ${{ env.REGISTRY_PASSWORD }} | oras login ${{ env.REGISTRY }} -u '${{ env.REGISTRY_USERNAME }}' --password-stdin
oras push ${{ env.REGISTRY }}/${{ env.OCI_PROJECT }}/ubuntu-22.04-kube:${{ env.KUBERNETES_VERSION }} \
 ./${OUTPUT}:application/vnd.unknown.layer.v1+qcow2

```

**Comment by qweeah** [comment]
@mcbenjemaa Thanks for reporting the issue. The command looks good and since you are using ORAS v1.0.0 I don't see any compatibility issue.

The error returned by Harbor is suggesting that something goes wrong on registry-side.
> unknown: unknown error: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. For more information, see REST Authentication and SOAP Authentication for details.
	status code: 403, request id: 70974918-d335-148d-9ae2-1070fde7ed2c, host id:

**Comment by mcbenjemaa** [comment]
Well, when I omitted qcow2 in the media type, it worked.

```
oras push ${REGISTRY}/${OCI_PROJECT}/ubuntu-22.04-kube:${KUBERNETES_VERSION} \
    ./${OUTPUT}:application/vnd.unknown.layer.v1
``` 

Is that Okay, or Should I define a custom mediaType?

**Comment by qweeah** [comment]
> Is that Okay, or Should I define a custom mediaType?

You can define any custom media type via ORAS. I think Harbor enforces a specific check for `application/vnd.unknown.layer.v1+qcow2` and causes the error. You need to sort it out with Harbor community.

> but, in GitHub CI, it failed
The `\` cannot be used in the job YAML of Github Actions, I think it causes the error.

**Comment by mcbenjemaa** [comment]
Yeah, that seems correct. Thank you

**Comment by shizhMSFT** [comment]
Close as issue has been resolved.
