### ISSUE TITLE
oras blob fetch failed to output to stdout in TTY mode

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#1268]
### What happened in your environment?

I tried to fetch a blob with `oras blob fetch` and output the content into stdout in terminal mode. The blob content is not printed to stdout as expected

```console
➜  oras blob fetch ghcr.io/oras-project/oras@sha256:488a49baab43328b45444fc9c13861da4408f279ba5247569bbe06a732265fdc --output -
✓ Downloaded  application/octet-stream                                                                  167/167  B 100.00%     0s
  └─ sha256:488a49baab43328b45444fc9c13861da4408f279ba5247569bbe06a732265fdc
```

With `--no-tty`, the content can be printed
```console
➜  oras blob fetch ghcr.io/oras-project/oras@sha256:488a49baab43328b45444fc9c13861da4408f279ba5247569bbe06a732265fdc --output - --no-tty
{"architecture":"unknown","os":"unknown","config":{},"rootfs":{"type":"layers","diff_ids":["sha256:31e4a5298aed7d277e1784bc57ff297a450e25eb59d5b7ac89f6bb229ac1a18a"]}}%
```

### What did you expect to happen?

The blob content should be printed to stdout

### How can we reproduce it?

Run below command
```bash
oras blob fetch ghcr.io/oras-project/oras@sha256:488a49baab43328b45444fc9c13861da4408f279ba5247569bbe06a732265fdc --output -
```

### What is the version of your ORAS CLI?

v1.2.0-beta.1

### What is your OS environment?

ubuntu 20.04

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by FeynmanZhou** [comment]
To fix this issue, it would be reasonable to make `--output -` emit the content of "oras blob fetch" to stdout. That's being said, the flag  `--output -` implies `--no-tty` in `oras blob fetch`. A sample experience is as follows:

```
$ oras blob fetch ghcr.io/oras-project/oras@sha256:488a49baab43328b45444fc9c13861da4408f279ba5247569bbe06a732265fdc --output -
{"architecture":"unknown","os":"unknown","config":{},"rootfs":{"type":"layers","diff_ids":["sha256:31e4a5298aed7d277e1784bc57ff297a450e25eb59d5b7ac89f6bb229ac1a18a"]}}%
```

**Comment by qweeah** [comment]
We should also allow user to avoid TTY resetting via explicitly put `--no-tty=false`.
