### ISSUE TITLE
Test fail on ARM with "fatal error: traceback did not unwind completely"

### ISSUE THREAD

**Issue by TerryHowe** [oras-project/oras#1277]
### What happened in your environment?

Tests fail with "fatal error: traceback did not unwind completely" on ARM based mac. Work fine on AMD. It appears this is happening in testutils call to `console.NewPty` and probably unrelated to ORAs, but thought we should at least document it. There are several similar errors I see on github, but nothing that I nail down as the same problem

### What did you expect to happen?

Tests to pass

### How can we reproduce it?

`make test` on ARM mac

### What is the version of your ORAS CLI?

latest

### What is your OS environment?

mac M1 Sonoma

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by qweeah** [comment]
Also need to remove `darwin` from the building constraint.

**Comment by TerryHowe** [comment]
Related https://github.com/containerd/console/issues/79
