### ISSUE TITLE
Update github action codecov to v4 when fixed

### ISSUE THREAD

**Issue by TerryHowe** [oras-project/oras#1291]
### What happened in your environment?

It looks like there are problems with v4 coverage I was not aware off. Reverting for now.

https://github.com/codecov/codecov-action/issues/1292

### What did you expect to happen?

it to work

### How can we reproduce it?

Run v4 codecov

### What is the version of your ORAS CLI?

main/latest

### What is your OS environment?

linux

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by TerryHowe** [comment]
Seems like this isn't fixed.

**Comment by qweeah** [comment]
Dependabot PRs are failing, should replicate codecov token to dependabot secrets as is suggested in https://github.com/codecov/codecov-action/issues/1292#issuecomment-1960681670
