### ISSUE TITLE
oras pull to support pulling the `manifest.config` object

### ISSUE THREAD

**Issue by SteveLasker** [oras-project/oras#131]
As we start promoting using `manifest.config.json` files, we should have a means to pull the the file.
The open issue I can see is what happens if a layer is represented as a `config.json` file? Is this an error to have a `manifest.config.json` file as well as a local `config.json` from a layer/blob? 
Should we start using `manifest.config.json` as the file name to be uploaded as the `--manifest-config`? As we add support for `index.config`, we could use `index.config.json`

**Comment by qweeah** [comment]
Ack

**Comment by qweeah** [comment]
This is already supported with `--manifest-config` option for `oras pull`. @SteveLasker Do we need to take a step further to support **downloading only the config**?

**Comment by sajayantony** [comment]
If we want to first class config then having a top level command under `oras config` might be the better option. 
As per the call - this is an old issue and if it not something that we want to promote then maybe we can close this issue.

**Comment by shizhMSFT** [comment]
How about `oras manifest fetch-config`?

**Comment by shizhMSFT** [comment]
@yuehaoliang-microsoft Could you follow up?

**Comment by yuehaoliang-microsoft** [comment]
As @qweeah mentioned above, user can use `oras pull --config` to fetch the config of a manifest, but `oras pull` will pull the entire image, everything.

My understanding is that now we are considering to introduce a new command to allow user to only fetch the config. I think fetching a config is kind of a specific case of fetching a blob. User can use `oras blob fetch` to fetch the config.

The advantage of `oras manifest fetch-config` is that it may save user a step to find out the digest of the config before they can use `oras blob fetch`. Is this new feature still wanted?

@shizhMSFT @sajayantony @FeynmanZhou

**Comment by yuehaoliang-microsoft** [comment]
`oras pull --config` let user provide an optional media type, which could be omitted for image manifest. If user provides the media type, then the successor who has a matched media type will be fetched.

If we decide to have a new command to let user fetch the config more straightforward, I think it could align the same UX, and `--output`, `--descriptor`, `--pretty` could also be supported.

**Comment by yuehaoliang-microsoft** [comment]
Will add `oras manifest fetch-config` to act similarly as [`crane config`](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane_config.md).

**Comment by FeynmanZhou** [comment]
@shizhMSFT @yuehaoliang-microsoft @qweeah 

How about aligning the pulling `manifest.config` object command with `oras pull --config`? Using `oras manifest fetch --config` might provide a more consistent UX for users.

**Comment by shizhMSFT** [comment]
> How about aligning the pulling `manifest.config` object command with `oras pull --config`? Using `oras manifest fetch --config` might provide a more consistent UX for users.

Those commands are not semantically consistent.
- `oras pull --config` means pull an artifact with config. However, not all artifact manifest has config. For instance, OCI Artifact does not have one although OCI image has one.
- `oras manifest fetch --config` means _fetch a manifest_ with a config. It will download both the manifest and the config where the manifest is not desired.

**Comment by yuehaoliang-microsoft** [comment]
Update the UX for `oras manifest fetch-config`:

I built and pushed this image as an example.
![image](https://user-images.githubusercontent.com/109199020/190553037-17658757-6eaf-4e14-a193-0f7414b3a406.png)

`oras manifest fetch-config $IMAGE` and `oras manifest fetch-config $IMAGE --output -` are exactly the same, and both print the config content.
`oras manifest fetch-config $IMAGE --descriptor` prints the config descriptor.
![image](https://user-images.githubusercontent.com/109199020/190553102-06351d68-9e13-4db2-8ef4-b0899157bb74.png)

`oras manifest fetch-config $IMAGE --pretty` prints the prettified config content.
![image](https://user-images.githubusercontent.com/109199020/190553291-524f5bfb-9f11-40bc-bf37-dbfa890b88b6.png)

`oras manifest fetch-config $IMAGE --descriptor --pretty` prints the prettified config descriptor.
`--output -` and `--descriptor` can't be both specified, same as `oras blob fetch` and `oras manifest fetch`.
![image](https://user-images.githubusercontent.com/109199020/190553425-ef9aa678-3cb5-4ff4-9ef9-312440f35569.png)

`oras manifest fetch-config $IMAGE --output config.json` saves the config content to local file, and `--descriptor` can be applied to print the prettified config descriptor.

**Comment by yuehaoliang-microsoft** [comment]
Added a new flag `--platform` to support fetch the config of a manifest with certain platform.

Eg. `oras manifest fetch-config docker.io/library/hello-world:latest --pretty --platform 'linux/arm/v5'`
<img width="843" alt="image" src="https://user-images.githubusercontent.com/109199020/190952867-21364a8f-f72e-4706-8275-3913cc8a4986.png">

Compare to: `oras manifest fetch-config docker.io/library/hello-world:latest --pretty`. The UX is desired because it is not an image manifest.
<img width="804" alt="image" src="https://user-images.githubusercontent.com/109199020/190952963-77f29195-5056-4fe1-a41e-95dedf38c74a.png">

It's actually a manifest list shown by `oras manifest fetch docker.io/library/hello-world:latest --pretty`.
<img width="676" alt="image" src="https://user-images.githubusercontent.com/109199020/190953148-cebbefc0-4024-49a8-9948-0618c70b0ba4.png">

Also, in addition, the manifest of this platform.
<img width="803" alt="image" src="https://user-images.githubusercontent.com/109199020/190953216-3ed59d5b-0ff8-4d26-a27a-6cad942eb057.png">
