### ISSUE TITLE
`oras manifest delete` fails with `Docker-Content-Digest` header missing

### ISSUE THREAD

**Issue by smndtrl** [oras-project/oras#1318]
### What happened in your environment?

```
oras manifest delete localhost:3000/test:lol        
Error: HTTP HEAD request missing required header "Docker-Content-Digest
```

I double checked with the distribution spec if that field should be required or not and it states
```
Legacy Docker support HTTP headers
Because of the origins this specification, the client MAY encounter Docker-specific headers, such as Docker-Content-Digest, or Docker-Distribution-API-Version. These headers are OPTIONAL and clients SHOULD NOT depend on them.
```

### What did you expect to happen?

legacy header are not required

### How can we reproduce it?

`oras manifest delete localhost:3000/test:simple`

### What is the version of your ORAS CLI?

```
oras version
Version:    1.1.0+Homebrew
Go version: go1.21.1
```

### What is your OS environment?

macos

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by qweeah** [comment]
To delete `localhost:3000/test:lol`, ORAS CLI need to resolve the digest of the manifest to call the API. How can a client get the required digest if `Docker-Content-Digest` is not presented?

Also [OCI spec v1.0.1](https://github.com/opencontainers/distribution-spec/blob/v1.0.1/spec.md#:~:text=200%20OK.-,A%20successful%20response%20SHOULD%20contain%20the%20digest%20of%20the%20uploaded%20blob%20in%20the%20header%20Docker%2DContent%2DDigest.,-The%20Docker%2DContent) states that `A successful response SHOULD contain the digest of the uploaded blob in the header Docker-Content-Digest`. It's not `MAY` thus it's not optional.

**Comment by smndtrl** [comment]
Sorry about the misunderstanding, I assumed that  `OPTIONAL` headers that clients `SHOULD NOT` depend upon was the ruling statement here. I will live with not having the the delete manifest functionality then.
