### ISSUE TITLE
Need to improve error message when basic auth flags are used with identity token flags

### ISSUE THREAD

**Issue by wangxiaoxuan273** [oras-project/oras#1340]
After #1294 is completed, `cmd.MarkFlagsMutuallyExclusive` is used to prevent `--identity-token` / `--identity-token-stdin` to be used with `--username`/ `--password` / `--password-stdin`. However, the default error message is confusing for the users. We need to improve the error messages.

**Comment by shizhMSFT** [comment]
@wangxiaoxuan273 Can you note down the current error message in this issue?

**Comment by wangxiaoxuan273** [comment]
Current error message: `Error: if any flags in the group [password identity-token identity-token-stdin password-stdin] are set none of the others can be; [identity-token password] were all set`

<img width="1093" alt="Screenshot 2024-04-12 at 16 45 53" src="https://github.com/oras-project/oras/assets/103478229/bff03659-5efc-403a-8689-437e2ae1e76e">

**Comment by qweeah** [comment]
Also need to improve [MarkFlagsRequiredTogether](https://pkg.go.dev/github.com/spf13/cobra#Command.MarkFlagsRequiredTogether) as it's used by mTLS flag parsing.

**Comment by qweeah** [comment]
The returned error should be compliant to the error guideline proposed in https://github.com/oras-project/oras/pull/1163
