### ISSUE TITLE
list all pushed tags in the json metadata output of `oras push`

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#1341]
### What is the version of your ORAS CLI

1.2.0-beta.1

### What would you like to be added?

Currently all the pushed tags are displayed in the output but not in the json output of `oras push`
```console
$ oras push localhost:5000/test:tag1,tag2,tag3 --format json
✓ Uploaded  application/vnd.oci.empty.v1+json                                                                                    2/2  B 100.00%   48ms
  └─ sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
✓ Uploaded  application/vnd.oci.image.manifest.v1+json                                                                       535/535  B 100.00%   38ms
  └─ sha256:0a6d04eceb050df7446931a07d75d3465b28bd8616003eddcce6838cfdcd3995
Tagged tag3
Tagged tag2
{
  "Ref": "localhost:5000/test@sha256:0a6d04eceb050df7446931a07d75d3465b28bd8616003eddcce6838cfdcd3995",
  "MediaType": "application/vnd.oci.image.manifest.v1+json",
  "Digest": "sha256:0a6d04eceb050df7446931a07d75d3465b28bd8616003eddcce6838cfdcd3995",
  "Size": 535,
  "Annotations": {
    "org.opencontainers.image.created": "2024-04-12T08:26:14Z"
  },
  "ArtifactType": "application/vnd.unknown.artifact.v1"
}
```

### Why is this needed for ORAS?

Pushed tags `tag1` `tag2` and `tag3`  should be added to the  json output of `oras push` and selectable via go templating.

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by qweeah** [comment]
As is suggested in https://github.com/oras-project/oras/pull/1199#discussion_r1566568387 and  https://github.com/oras-project/oras/pull/1199#discussion_r1566563097, the field should be full reference ending with tags.

**Comment by FeynmanZhou** [comment]
@qweeah  `tags` is also recommended to be outputted in `oras attach`.

**Comment by qweeah** [comment]
> @qweeah `tags` is also recommended to be outputted in `oras attach`.

What value should be put into this field? `oras attach` cannot tag artifact.

**Comment by FeynmanZhou** [comment]
@qweeah  You are right. `oras attach` will not produce new tags so it's not necessary to show `tags` in the output. Ignore my suggestion above.
