### ISSUE TITLE
`--pretty` should not prettify file output

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#1361]
### What happened in your environment?

If `oras manifest fetch` is used with `--pretty` set and `--output` set to a file, then the output file is prettified

### What did you expect to happen?

According to the help doc, `--pretty` should only prettify stdout output
>  --pretty                                      prettify JSON objects printed to stdout

### How can we reproduce it?

```shell
 oras manifest fetch -o out mcr.microsoft.com/oss/kubernetes/kubectl:v1.31.0-alpha.0 --platform linux/amd64 --pretty
```
The saved file `out` will be prettified.

### What is the version of your ORAS CLI?

Version:        1.2.0-beta.1+unreleased
Go version:     go1.22.1
Git commit:     fa65f61c86fa75b23b8f2afffe1ba77a5fbf44b7
Git tree state: dirty

### What is your OS environment?

Ubuntu 20.04

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by wangxiaoxuan273** [comment]
I'd like to work on this issue.
