### ISSUE TITLE
Filtering on mediatype should filter first on mediatype, then encoding

### ISSUE THREAD

**Issue by jdolitsky** [oras-project/oras#138]
Instead of passing an array (slice) of acceptable mediatype strings, we should instead pass an array of objects such as 
```
{
  mediaType: "application/vnd.unknown.config.v1", 
  supportedEncodings: [
    "+json",
    "+yaml"
  ]
}

**Comment by shizhMSFT** [comment]
@jdolitsky We might need drop the "allow media type" by #130

**Comment by shizhMSFT** [comment]
Closing as `--allow-media-type` is dropped.
