### ISSUE TITLE
Template formatting issues for manifest content

### ISSUE THREAD

**Issue by sajayantony** [oras-project/oras#1387]
### What happened in your environment?

Command used - 

```
$oras manifest get docker.io/sajay/artifacts:foo-v1 --format go-template --template '{{.content}}'
map[annotations:map[org.opencontainers.image.created:2024-03-05T19:59:05Z] artifactType:example/artifact config:map[data:e30= digest:sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a mediaType:application/vnd.oci.empty.v1+json size:2] layers:[map[data:e30= digest:sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a mediaType:application/vnd.oci.empty.v1+json size:2]] mediaType:application/vnd.oci.image.manifest.v1+json schemaVersion:2]%
```

### What did you expect to happen?

I was expecting the content part of the manifest to emitted similar to 

``` 
❯ oras manifest get docker.io/sajay/artifacts:foo-v1 --format json | jq .content
{
  "annotations": {
    "org.opencontainers.image.created": "2024-03-05T19:59:05Z"
  },
  "artifactType": "example/artifact",
  "config": {
    "data": "e30=",
    "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
    "mediaType": "application/vnd.oci.empty.v1+json",
    "size": 2
  },
  "layers": [
    {
      "data": "e30=",
      "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
      "mediaType": "application/vnd.oci.empty.v1+json",
      "size": 2
    }
  ],
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "schemaVersion": 2
}
```

### How can we reproduce it?

oras manifest get docker.io/sajay/artifacts:foo-v1 --format go-template --template '{{.content}}'

### What is the version of your ORAS CLI?

❯ oras version
Version:        1.2.0-rc.1+unreleased
Go version:     go1.22.0
Git commit:     e24ce35214bec070956f26f3ddeff6123f66228c
Git tree state: dirty

### What is your OS environment?

ubuntu

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by shizhMSFT** [comment]
We have considered this scenario and it is **expected** for go-template. Precisely, it is intended for go-template to print a go object instead of a JSON object. To print the result as a JSON object instead of a go object, a workaround is to specify `--template '{{ toPrettyJson .content }}'` by invoking the sprig function `toPrettyJson`.

As inferred by this issue, a better experience would be a new format type of [jsonpath](https://kubernetes.io/docs/reference/kubectl/jsonpath/). Similar to `kubectl`, the experience for `oras` would be
```console
$ oras manifest get docker.io/sajay/artifacts:foo-v1 --format jsonpath='{.content}'
{
  "annotations": {
    "org.opencontainers.image.created": "2024-03-05T19:59:05Z"
  },
  "artifactType": "example/artifact",
  "config": {
    "data": "e30=",
    "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
    "mediaType": "application/vnd.oci.empty.v1+json",
    "size": 2
  },
  "layers": [
    {
      "data": "e30=",
      "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
      "mediaType": "application/vnd.oci.empty.v1+json",
      "size": 2
    }
  ],
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "schemaVersion": 2
}
```

An alternative to `jsonpath` is [`jmspath`](https://jmespath.org/), which is adopted by Azure CLI.

**Comment by sajayantony** [comment]
Closing this as its an expected behavior as @shizhMSFT mentions. I think having some docs to show examples of outputting parts of the output using the template might be useful.
