### ISSUE TITLE
Add examples for the flag "--format"

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras#1422]
### What happened in your environment?

After upgraded to ORAS v1.2.0, I noticed that there are no any examples of the flag `--format` in ORAS CLI command help reference. Users might be hard to understand how to use `--format` in ORAS CLI commands

<img width="1023" alt="image" src="https://github.com/oras-project/oras/assets/40452856/4d2c2e02-a029-4a71-acf2-56acc3fc5947">

### What did you expect to happen?

It would be much user-friendly if we could add basic examples for the flag "--format" in the help reference. 

### How can we reproduce it?

Run "--help" in each oras command

### What is the version of your ORAS CLI?

oras v1.2.0

### What is your OS environment?

Ubuntu 22.06

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by shizhMSFT** [comment]
We are having more and more examples in the `Example` section of the help. Sometimes, it is hard for me to find the usage and flag usages.

Should we consider `man` pages instead of `--help`? That is,
```bash
man oras
```
or maybe in PowerShell
```powershell
Get-Help oras
```
