### ISSUE TITLE
Make oras Push/Pull an interface

### ISSUE THREAD

**Issue by deitch** [oras-project/oras#145]
As discussed earlier after the artifacts meeting.

Let's say I have some function that calls `oras.Push()`. It has opinions about how ti will structure artifacts, annotations, mime types, etc. At the end, it calls `oras.Push()`. I want to test my functions, but don't actually want it calling `oras.Push()` (or `Pull()`) as I am just testing its ability to get from inputs to the output of calling `oras.Push()` or `Pull()`.

As it stands, it is very hard to mock out `oras.Push()` and `oras.Pull()`. I could monkey-patch it as follows, but it is messy:

```go
// in my main file
var pushFunc = oras.Push
func MySpecial(...) {
   // do lots of logic
   pushFunc(...)
}

// in my _test file
// assume I am in the same package, which isn't great if I am testing exported funcs
//    like MySpecial()
func TestMySpecial(t *testing.T) {
   pushFunc = someMock
   MySpecial(...)
   // assertions, etc.
}
```

This would be far easier - and go-friendly - if instead of defining `Push()` and `Pull()` in the `oras` package, we defined it as an interface with an implementation, so I can stub it in, something like:

```go
// defined in oras or even elsewhere
type Pusher interface {
  Push(...) (...)
}
// define in oras
type OrasPusher struct {
}
func (o *OrasPusher) Push(...) (...) {
}
// in my main file
func MySpecial(pusher oras.Pusher) {
   // do lots of logic
  pusher.Push(...)
}

// in my _test.go file
type PusherMock struct {
}
func (p *PusherMocl) Push(...) (...) {
}

func TestMySpecial(t *testing.T) {
   p := &PusherMock{...}
   MySpecial(p)
   // assertions, etc.
}
```

Thoughts?

**Comment by SteveLasker** [comment]
There's a good recent tension/discussion on the separate between the ORAS libraries, which should support a wide range of capabilities, and the ORAS client generic reference implementation. 
I've started an example of [regdoc](http://github.com/stevelasker/regdoc) that would support `push`, `pull`, `delete` and `tag lsting` with auth capabilities. But, I quickly got out of my expertise here.
The though being a specific cli wouldn't expose mediaType as a parameter, anymore than the docker or helm client expose their mediaType. It's inferred in their experiences. However, it appears, the current ORAS library could use some more factoring.

I'm suggesting we create a mock API for the range of APIs we'd like to support with the ORAS libraries, and then cleanup and consolidate the various libraries we use.

**Comment by deitch** [comment]
> tension/discussion on the separate between the ORAS libraries, which should support a wide range of capabilities, and the ORAS client generic reference implementation

100% agreed. There is a number of things I have been working on that I almost suggested submitting, and then realized it is my opinionated implementation, and should not go upstream. Then there are things that the API could do to make all of this easier.

The above suggestion is (I believe) in line with the library surface side of it.

FWIW, in my implementation, I have a struct that has a field called `Impl` which has the same signature as `oras.Pull`/`Push`, and I can pass it a mock. If none is passed, it uses `oras.Pull`/`Push`.

**Comment by shizhMSFT** [comment]
Closing as it is succeeded by `oras.Copy()` in `oras-go`.
