### ISSUE TITLE
oras tag/push should fail fast on invalid input

### ISSUE THREAD

**Issue by wangxiaoxuan273** [oras-project/oras#1479]
Many oras commands require tag or digest input from the user, but in some cases validation is missing. And if invalid tags or digest is given, errors will be returned from remote registry server.

For example:
`oras tag` does not validate if the given tag is valid. If given a digest, the operation will not fail until reaching the remote registry.
![image](https://github.com/user-attachments/assets/f0f43c06-0005-49b1-9def-6ea4269b142c)

For oci-layout, tagging with digest won't even give an error.
![image](https://github.com/user-attachments/assets/abe707b4-fd73-4d1b-ad66-f8b21cd6ac7d)

Same for `oras push`
![image](https://github.com/user-attachments/assets/c4420163-9042-4725-8f80-56ca23ed82cb)

![image](https://github.com/user-attachments/assets/cd53fa28-cec8-466b-bc07-80fefc9a8a10)

We could instead validate the tags/digests during command parsing, and fail fast if invalid input is found. `oras-go` contains the following methods that can be incorporated into `func (opts *Target) Parse(cmd *cobra.Command) error` of `oras`.

[func (r Reference) ValidateReference() error](https://pkg.go.dev/oras.land/oras-go/v2@v2.5.0/registry#Reference.ValidateReference)
[func (r Reference) ValidateReferenceAsDigest() error](https://pkg.go.dev/oras.land/oras-go/v2@v2.5.0/registry#Reference.ValidateReferenceAsDigest)
[func (r Reference) ValidateReferenceAsTag() error](https://pkg.go.dev/oras.land/oras-go/v2@v2.5.0/registry#Reference.ValidateReferenceAsTag)

**Comment by qweeah** [comment]
Some registries might allow tag names that will fail in https://pkg.go.dev/oras.land/oras-go/v2@v2.5.0/registry#Reference.ValidateReferenceAsTag, so it's better to only exclude digests.
