### ISSUE TITLE
Update runc dependency

### ISSUE THREAD

**Issue by jdolitsky** [oras-project/oras#156]
See issue here: https://github.com/helm/helm/issues/7846

**Comment by killwing** [comment]
any updates? we meet security issues dep on runc & docker.

**Comment by bacongobbler** [comment]
runc is [working towards a v1.0.0](https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc92) release, so it may be worth holding off until it's been released. As described [upstream](https://github.com/helm/helm/issues/7846#issuecomment-606837479), the security issues related to runc and docker are irrelevant for oras, as at no point are container runtimes executed.

**Comment by bacongobbler** [comment]
pinging here again as another ticket was opened at helm/helm#9956.

**Comment by shizhMSFT** [comment]
Closing as `runc` has already upgraded to `v1.1.1`. Once we upgrade to `oras-go` v2. The `runc` dependency should go away.
