### ISSUE TITLE
oras push fails when hostname is localhost

### ISSUE THREAD

**Issue by quater** [oras-project/oras#159]
## Issue

The Oras usage example **Pushing Artifacts with Single Files** from the **README.md** does not work. 

https://github.com/deislabs/oras/blob/237ac925cb6a308a5523cc048292bb53037f6975/README.md 

Following this example, I get the below error that indicates that HTTP rather HTTPS is used.

```bash
$ oras login -u <username> -p <password> --insecure localhost:5000
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded

$ echo "hello world" > artifact.txt

$ oras push --insecure localhost:5000/hello-artifact:v1 \
--manifest-config /dev/null:application/vnd.acme.rocket.config.v1+json \
./artifact.txt
Uploading a948904f2f0f artifact.txt
Error: failed to do request: Head http://localhost:5000/v2/hello-artifact/blobs/sha256:a948904f2f0f479b8f8197694b30184b0d2ed1c1cd2a1ec0fb85d299a192a447: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```
## Version
I am using the Linux x64 binary from https://github.com/deislabs/oras/releases/download/v0.8.1/oras_0.8.1_linux_amd64.tar.gz

## Workaround
I can work around this error by using the actual machine name in place of `localhost`.

**Comment by sajayantony** [comment]
If this is still an issue please reopen.
