### ISSUE TITLE
Add pure OCI Resolver 

### ISSUE THREAD

**Issue by jdolitsky** [oras-project/oras#165]
Should create a Resolver that does not contain Docker-specific logic

For more info, please see https://github.com/opencontainers/tob/pull/68#discussion_r438429027

**Comment by nishakm** [comment]
I'd like to help with this. Do we need to re-implement Resolver from scratch or is there an oci lib we can use?

**Comment by deitch** [comment]
I use google/go-containerregistry a lot.

**Comment by nishakm** [comment]
IIRC google's go-containerregistry also uses docker's Resolver.

**Comment by deitch** [comment]
I've spent so long in their code, I should know that. 😆 

I'm away from laptop now, so cannot check.

**Comment by nishakm** [comment]
I'm certainly no expert! I can dig into the code some more. Still, I have recently tried to use go-containerregistry to pull an index.json with no luck.

**Comment by shizhMSFT** [comment]
@jdolitsky I lost context on this issue. Please re-open if it still need to be resolved. /cc @SteveLasker
