### ISSUE TITLE
finalizer on Pusher returned by Resolver?

### ISSUE THREAD

**Issue by deitch** [oras-project/oras#172]
Looking at how `oras.Push()` is called [here](https://github.com/deislabs/oras/blob/master/pkg/oras/push.go#L17), we pass it a `remotes.Resolver`:

```go
func Push(ctx context.Context, resolver remotes.Resolver, ref string, provider content.Provider, descriptors []ocispec.Descriptor, opts ...PushOpt) (ocispec.Descriptor, error) {
```

`Push()` , in turn, gets a pusher by calling `resolver.Pusher()` [here](https://github.com/deislabs/oras/blob/master/pkg/oras/push.go#L35)

```go
	pusher, err := resolver.Pusher(ctx, ref)
```

and then passing that pusher to `remotes.PushContent` [here](https://github.com/deislabs/oras/blob/master/pkg/oras/push.go#L52):

```go
	if err := remotes.PushContent(ctx, pusher, desc, store, nil, wrapper); err != nil {
```

What if my pusher (returned by `resolver.Pusher()`) needs some finalizing done? There are `Commit()` and `Close()` calls on the `content.Writer` returned by _each_ `Push()`, but not overall. I might have a custom resolver (and therefore pusher) that needs to do some activity at the end of a whole `PushContent`.

`remotes.PushContent()` has an option for doing so via its handlers, which can be both pre- and post-, but `oras.Push()` only accepts pre-push handlers for each push, see [here](https://godoc.org/github.com/deislabs/oras/pkg/oras#WithPushBaseHandler). In any case, those are called with each push, and so no way to know, "this is the final push".

I can do something at the `Resolver` level, rather than `Pusher`, and thus have control after calling `oras.Push()`, but that is one level too high for it, and could bleed into other things. For example, I should be able to push 3 images up, each time calling `oras.Push()` (and hence `resolver.Pusher()`) from the same instance of `resolver`; finalizing would really mess that up.

**Comment by shizhMSFT** [comment]
We can close this once we moved to `oras-go` v2.
