### ISSUE TITLE
Resolver interface (and others) should not use positional arguments

### ISSUE THREAD

**Issue by jdolitsky** [oras-project/oras#176]
The API of `Resolver` (and possibly others) should be redesigned to use options vs. positional arguments like `plainHTTP`, as these may continue to grow and break APIs

**Comment by SteveLasker** [comment]
The ORAS cli should continue to support positional arguments to demonstrate an example of a generic api. However, the underlying libraries should be more explicit.

**Comment by jdolitsky** [comment]
CLI yes. Go library should change though, IMO

**Comment by SteveLasker** [comment]
I think we're saying the same thing. The ORAS libraries should change to enable artifact authors to do what's correct for their CLI and not get caught in positional arguments that imply a behavior to their experience, or risk of breaking changes.

**Comment by jdolitsky** [comment]
Done, see new `ResolverWithOpts`: https://github.com/oras-project/oras-go/blob/dc9aa475e4ca4f9bbf3aa76f04629eab067692bc/pkg/auth/client.go#L44
