### ISSUE TITLE
oras push error when pushing artifacts in to harbor registry

### ISSUE THREAD

**Issue by hemantha-kumara** [oras-project/oras#205]
/kind bug

**What happened:**
Trying to push the artifacts into the harbor registry. harbor login is successful(oras login) but oras push is failing with the below error

here is the log for your reference
```
sh-4.2# oras push harbor.dsml-csfp-2.ccsp.dyn.nesc.nokia.net/kubeflowprofiles/hello-artifact:v1 --manifest-config /dev/null:application/vnd.acme.rocket.config ./artifact.txt --insecure
Uploading a948904f2f0f artifact.txt
Error: failed to authorize: failed to fetch oauth token: unable to decode token response: invalid character '<' looking for beginning of value
```

```
sh-4.2# oras version
Version:        0.8.1
Go version:     go1.12.4
Git commit:     237ac925cb6a308a5523cc048292bb53037f6975
Git tree state: clean
```

`Harbor Version v1.8.0` harbor authentication is enabled using Keycloak(OIDC/OAUTH)

**Comment by etrexel** [comment]
Do you know if Harbor supports the oras artifact spec? In order to push with oras the registry needs to support oras artifacts.

**Comment by shizhMSFT** [comment]
> Do you know if Harbor supports the oras artifact spec? In order to push with oras the registry needs to support oras artifacts.

ORAS works with all OCI-compliant registries for non-experimental features. Hence, `oras` does not require the registry to support oras artifacts.

**Comment by shizhMSFT** [comment]
From the error message, it seems an error in the OAuth2 path.

**Comment by shizhMSFT** [comment]
@hemantha-kumara Closing since this is an auth error. Please re-open this issue if you still have problem.
