### ISSUE TITLE
Tests for pushing CNAB bundle

### ISSUE THREAD

**Issue by jdolitsky** [oras-project/oras#22]
See here for Helm chart test: https://github.com/shizhMSFT/oras/blob/master/pkg/oras/oras_test.go#L87
https://github.com/shizhMSFT/oras/blob/master/pkg/oras/oras_test.go#L146

**Comment by sajayantony** [comment]
@jdolitsky - should we close this - I believe porter support publishing bundles -

**Comment by shizhMSFT** [comment]
Closing as the issue content seems to be outdated. Please re-open if needed.
