### ISSUE TITLE
Build for darwin-arm64?

### ISSUE THREAD

**Issue by peterj** [oras-project/oras#267]
It would be great if a build for `darwin-arm64` is added.

**Comment by jdolitsky** [comment]
@peterj - missing documentation, but there is indeed  a darwin-arm64 build: https://github.com/oras-project/oras/releases/tag/v0.12.0

Will keep this open for the documentation updates

**Comment by sajayantony** [comment]
As per @jdolitsky there is a build for darwin and can be located at - https://github.com/oras-project/oras/releases/download/v0.12.0/oras_0.12.0_darwin_amd64.tar.gz

Please reopen if the build does have an issue.
