### ISSUE TITLE
Pull arbitrary manifest config

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#275]
As the solution to #142, #274 enables the CLI to pull manifest config. However, the user must provide the desired media type of the config or use the default.

The advantages of specified media types are
- Config can be virtually optional although it is a required field in the manifest.
- `oras` will not pull unrecognized config files.

In this issue, we discuss we should allow pulling arbitrary manifest config or not.

If we do want to pull arbitrary manifest config, we will have more implementation complexity.
- We need to explicitly specify a hybrid store of a file store and a memory store.
- We need to add a manifest hooker to the base handler. Basically, we need to explicitly re-invent the `oras.Pull()`.

**Comment by qweeah** [comment]
@shizhMSFT Please assign it to me.

**Comment by lizMSFT** [comment]
Assigned
