### ISSUE TITLE
Links to 0.12.0 in ReadMe are broken

### ISSUE THREAD

**Issue by KarsonAlford** [oras-project/oras#276]
Some or all of the links to version 0.12 are broken.  Based on your releases page this version does not exist yet.

https://github.com/deislabs/oras/releases/download/v0.12.0/oras_0.12.0_windows_amd64.tar.gz

**Comment by jdolitsky** [comment]
@KarsonAlford - apologies, bumped the version in the readme prior to doing the release. v0.12.0 is released now, and these artifacts are now available
