### ISSUE TITLE
ORAS CLI Templates

### ISSUE THREAD

**Issue by SteveLasker** [oras-project/oras#287]
As new artifact types surface, artifact authors seek a cli to enable `thing push|pull`. The `oras` cli has done well to enable iterative testing, however it requires users to specify the `mediaType` and details a `thing` user shouldn't need to specify. With the refactoring of ORAS libraries, it would help new artifact authors with a template for how to implement their own cli.

## Goals

Get a new artifact author up and running with minimal steps, with the ability to add their unique functionality atop the basic oras capabilities of `oras login|push|pull`.

1. Clone an `oras template` repo
2. Change the output binary from `oras-template` to `thing`
3. Change the `artifactType` from `application/x.unknown` to their artifact type (eg: `org.thing`)
4. Optionally declare any unique layer types
5. Build the project
6. Run:
    ```bash
    thing login registry.acme-rockets.io
    thing push registry.acme-rockets.io/myapp:v1 .
    thing pull registry.acme-rockets.io/myapp:v1
    ```

## OCI Artifacts and Reference Types

The current [OCI Artifacts][oci-artifacts] project focuses on individual artifact types. This enables efforts like helm, wasm, opa and is supported by most public and private registries.

There's a new set of artifact types that are considered additional content to existing artifacts, including SBoMs, scan results, signatures, seccomp and other types. To enable these new types, [Artifact Reference Types][artifact-ref-types] are being incubated. While *not yet* adopted by a broad number of registries, there's the common chicken/egg problem where the need drives ability. As registries start implementing reference types, artifact authors will want/need a CLI to enable `push|pull` capabilities. Providing a template for reference types, the ability will drive desire to support the new types.

ORAS support for reference types is provided [here][oras-ref-types]. For an artifact author to use reference types, the ORAS libraries will need to support the capability. An artifact author should be able to choose if their artifact can be pushed as a reference type, or an individual type. How that is done within the template is a good discussion. Whether a fallback mechanism should be provided if the target registry doesn't support reference types is another good discussion.

[oci-artifacts]:      https://github.com/opencontainers/artifacts
[artifact-ref-types]: https://github.com/SteveLasker/artifacts/tree/oci-artifact-manifest
[oras-ref-types]:     https://github.com/oras-project/oras/blob/reference-types/docs/artifact-manifest.md

**Comment by shizhMSFT** [comment]
Artifact authors can use [oras-go](https://github.com/oras-project/oras-go) to create their own CLIs.
