### ISSUE TITLE
auto-generated docker commands on github packages

### ISSUE THREAD

**Issue by myoung3** [oras-project/oras#294]
This is obviously an issue with on github's end, but perhaps this is something that oras can solve universally?

![dockercommands](https://user-images.githubusercontent.com/2517171/128223001-5e94fda7-1ae0-4b94-8733-3aa3002c567b.png)

This package contains a .sif image, but github automatically displays docker command which obviously don't work.
https://github.com/kaufman-lab/build_containers/pkgs/container/geospatial_plus

At the very least, it would be good if we could turn these off (there is no option to turn these off under package settings), but ideally github would detect the image type and display singularity commands.

I'm not really sure what the solution here because I don't understand whether this is happening for all images stored on ghcr, or only because some sort of metadata is absent from the sif image and the default is to assume a docker image. Again, this is an issue with github, but maybe oras can coordinate with github on how to fix this generally.

Also cross-posted to sylabs: https://github.com/sylabs/singularity/issues/213

**Comment by sajayantony** [comment]
@myoung3 - This sounds like a issue with GHCR. The oras CLI doesn't upload a docker manifest.

**Comment by myoung3** [comment]
@sajayantony Yes it's 100% an issue with GHCR, but oras maintainers are better suited to coordinate with github to fix this. I don't understand how tags work in containers and ORAS well enough to submit an coherent feature request to github on this.

**Comment by sajayantony** [comment]
@SteveLasker - Do you think you can engage the GitHub or GHCR team for this issue?

**Comment by SteveLasker** [comment]
Calling @clarkbw for insight

**Comment by clarkbw** [comment]
@nilofer would know more now

**Comment by nilofer** [comment]
👋 Yes, GHCR defaults to `docker pull` instructions right now.  We're taking a look at how to better this experience in the future for other package types hosted on GHCR, but I don't have concrete plans or a timeline to share at the moment.

**Comment by sajayantony** [comment]
Closing the issue since the behavior is a GitHub behavior and not related to the ORAS project from the above discussion.
