### ISSUE TITLE
Add Reference Type support 

### ISSUE THREAD

**Issue by SteveLasker** [oras-project/oras#296]
While capturing the [Notary v2 project requirements](https://github.com/notaryproject/notaryproject/blob/main/requirements.md), we identified the need to have reference types, enabling any artifact to associate itself with an existing artifact. 
This would enable a graph of objects to be represented within a registry, including Signatures, SBOMs, Signatures of SBOMs, Security Scan results, and more.

![image](https://user-images.githubusercontent.com/7647382/129418559-3751f663-1fe3-45ad-91db-98e4f846b7cf.png)

By establishing a reverse linkage between artifacts, registries can persist the objects, with the full ability to manage the artifact lifecycle, and not populate the tag listing, just to keep the lifecycle of the artifact around.

Today, we have a [reference-types branch](https://github.com/oras-project/oras/tree/reference-types) under oras which requires a separate build of ORAS to get the functionality. Similar to the [helm registry work](https://helm.sh/docs/topics/registries/), we'd like to incorporate the artifact-spec reference type support into oras, deferring the support of the capabilities to the target registry.

Azure, AWS and Docker are working to ship reference types this fall. By providing the reference implementation within distribution/distribution and oras, we enable all registries that are based on distribution/distribution to benefit and support the feature more quickly.

**Comment by deitch** [comment]
A few questions (I know that most of these have been answered in discussions; wanted to capture here on the issue).

- To be clear, these are reverse linkage and not forward? So the signature for an object points to the object, and not the other way around? The impact of that is that if I only know the object, I've got no way to get the signature. Is that correct?
- where does the reference exist in the yaml/object structure?

**Comment by SteveLasker** [comment]
reverse, yes. 
Signatures, SBoMs aren’t considered to have individual identity, thus no tag. 
You get a signature by requesting for referred objects of a tag net-monitor:v1 with an artifactType of cncf.notary.v2

The reference types branch of Oras has a discover api that Shiwei created. It’s super powerful. 
https://www.youtube.com/watch?v=GnmqTyo1a3M

**Comment by deitch** [comment]
> referred objects 

So the distribution (registry) needs to have, at least:

- Tracking of references (forward), independent of what is in the referred item. If signature x refers to manifest y, then x points to y inherently, but the registry needs to track that y is referred to by x. Nothing in y knows it, it isn't listed anywhere 
-  Updated garbage collection, since nothing points to x. This may impact local systems as well (think containerd and it's GC).

**Comment by deitch** [comment]
OK, makes sense.

I would like to get a better understanding as to what layer of API implementation is library responsibility (and which lib), and what is cli?

A better way of putting it is to list the underlying activities that need to take place, then identifying where the implementation happens, which leads to what gets rolled together by CLI.

E.g. the newer `Copy()` API just copies all of the tree pointed to by a reference (tag or hash) from target A to target B. It doesn't understand much about references and pointers and such, just the "traditional" manifests. Of course, an SBoM and a signature and such are just manifests, but with some unique media types and properties (like references). Where does it all get tied together and how?

**Comment by SteveLasker** [comment]
Agreed Avi,
If we agree to move forward to address "this issue", we can call out those details in the subsequent PRs. 

The discover APIs is implemented, but we do want to enable copy apis as well, with inclusion and exclusion of `artifactTypes` so users can copy the graph from one registry to another, and we'd like to incorporate this into your refactored design. 

Just to capture consensus, do you LGTM the moving forward of PRs to support the artifact manifest and referrers API?

I've changed the title and content of the issue to reflect the support will be deferred to the capabilities of the target registry.

**Comment by sajayantony** [comment]
Removing the resolver might address this and now that Copy has been implemented we should focus on supporting the new manifest type - 
https://github.com/oras-project/oras-go/pull/17

**Comment by SteveLasker** [comment]
Closing as this was merged in the [alpha.1 release](https://github.com/oras-project/oras/releases/tag/v0.2.1-alpha.1).
