### ISSUE TITLE
ORAS get-manifest command

### ISSUE THREAD

**Issue by SteveLasker** [oras-project/oras#301]
ORAS Artifacts, notation and other clis associate references to a digest. 
However, users think of tags.
The oras CLI and go-lib would take a tag, and return a digest, and the associated manifest.

**Comment by shizhMSFT** [comment]
@FeynmanZhou What do you suggest on the UX of `oras get-manifest`?

**Comment by sajayantony** [comment]
I have outlined some details here - https://github.com/oras-project/oras/discussions/340 - @FeynmanZhou

**Comment by qweeah** [comment]
@shizhMSFT Please assign it to me.

**Comment by qweeah** [comment]
As is described in #459, also need to add `--descriptor` flag for fetching a descriptor of the target manifest.
