### ISSUE TITLE
Auth story for `oras login`

### ISSUE THREAD

**Issue by juliusl** [oras-project/oras#302]
Currently we depend on docker login to support auth. In some of the work with retooling oras-go, I've abstracted this out of the resolver. This leaves auth as an open question for oras.  

What I would like to propose, and the direction I headed in my PR, is to closely rely on golang's oauth2 implementation. (which is the closest I can get to built-in interfaces/structs)

Specifically  `golang.org/x/oauth2/clientcredentials` and also `TokenSource` from `golang.org/x/oauth2`:

```
type Config struct {
	// ClientID is the application's ID.
	ClientID string

	// ClientSecret is the application's secret.
	ClientSecret string

	// TokenURL is the resource server's token endpoint
	// URL. This is a constant specific to each server.
	TokenURL string

	// Scope specifies optional requested permissions.
	Scopes []string

	// EndpointParams specifies additional parameters for requests to the token endpoint.
	EndpointParams url.Values

	// AuthStyle optionally specifies how the endpoint wants the
	// client ID & client secret sent. The zero value means to
	// auto-detect.
	AuthStyle oauth2.AuthStyle
}
```

```
// A TokenSource is anything that can return a token.
type TokenSource interface {
	// Token returns a token or an error.
	// Token must be safe for concurrent use by multiple goroutines.
	// The returned Token must not be modified.
	Token() (*Token, error)
}
```

Since these packages handle the oauth2 flow, including refreshing the token, 2-3 step oauth2 token flow, etc, all you need to do to get an http.Client is: 

```
       oauth := clientcredentials.Config{}
	c := oauth.Client(ctx)
```

and 

```
	client := oauth2.NewClient(ctx, TokenSource)
```

In my retooling, the resolver now only depends on an http.Client. So by using the oauth2 interfaces and structs, all that is needed to onboard new auth flows is either a client credentials config or a TokenSource implementation. Really though, anything that outputs a http.Client and is authn/authr against the target registry will do. 

As a concrete example, with Azure I'm able to use machine credentials, which is a client_id and client_secret. (I imagine other cloud providers having analagous features) Combining that with RBAC, I can create an oauth2 config on the fly without having to rely on any dependencies to do the auth for me (i.e docker login). 

Another example, for my own use I created a BasicAuth TokenSource, https://github.com/juliusl/oras-go/blob/5ad73c0c6ae4da26fa5ffd4c3d0d7149cca06195/pkg/remotes/basicauth.go#L52; 

Downstream, I have some test code in a different repo which I am using to prove/debug/test my new resolver code -- https://github.com/juliusl/oras-actions/blob/26bc052323bc58b65a5c0706dfc637038c769a99/go/src/action/main.go#L24: 
```
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"

	"oras.land/oras-go/pkg/remotes"
)

type Scope struct {
	Login       string `json:"scopeLogin"`
	Name        string `json:"scopeName"`
	Token       string `json:"scopeToken"`
	Permissions string `json:"scopePermissions"`
}

type ScopeMap struct {
	Scopes []Scope `json:"scopes"`
}

func main() {
	ctx := context.Background()

	ref := "registry.example.com/ubuntu:latest"

	file, err := os.Open("./secrets/auth.json")
	if err != nil {
		panic(err.Error())
	}

	scopeMap := &ScopeMap{}
	json.NewDecoder(file).Decode(scopeMap)

	scope := scopeMap.Scopes[0]

	reg := remotes.NewRegistryWithBasicAuthorization(
		ctx,
		ref,
		scope.Name,
		scope.Token,
		scope.Permissions)
...
```

By decoupling auth in this way, it simplifies taking oras-go as a dependency, and makes it easier to adapt oras-go to new auth-flows, without needing to check-in any new auth code to oras-go. For example, I could write an oras-go-azure library which adds: 

```
  NewRegistryWithSystemIdentity
```

or maybe an oras-go-kube library which adds:

```
  NewRegistryWithKubeSecrets
```

So that's my thought process in general, but it doesn't completely answer the question of how `oras login` should work. With the above in mind, I propose some variation of the ScopeMap struct I have above in my test code to start off. In devop pipelines since secrets get passed in some form of  `{{ .Secret }}` it's easier to format secrets via .sh. For example we could add an action that generates a generic script with a loop like this (for example a .sh file called `registry.example.com`): 

```
#!/bin/bash
...
login=$0
user=$1
pass=$2
scope=$3
cat <<EOF > "$login.$scope.json"
{
   "scopeLogin": "$login",
   "scopeName": "$user",
   "scopeToken": "$pass",
   "scopePermissions": "$scope"
}
EOF

# Just an example if you wanted to make a more complete auth file down the line
cat "$login.$scope.json" >> "$login.auth.json"

shift 3
...
```
and then calling it: 
```
./registry.example.com {{.Secrets.Repo1.User}} {{.Secrets.Repo1.Token}} {{.Secrets.Repo1.Scope}} {{.Secrets.Repo2.User}} {{.Secrets.Repo2.Token}} {{.Secrets.Repo2.Scope}}
```

And then oras cli can pick up the file afterwards for auth, or even maybe read this from stdin, or check for env-variable, etc. 

I acknowledge that I might be hand-waving a bit on some details, and so some imagination is required to fill in the gaps, but I wanted to share some ideas I had on the topic to start the discussion.

**Comment by northtyphoon** [comment]
@sajayantony @shizhMSFT

**Comment by shizhMSFT** [comment]
Closing as it is succeeded by oras-go v2.
