### ISSUE TITLE
Include support for helm 3.7 OCI artifacts

### ISSUE THREAD

**Issue by akashkeshari** [oras-project/oras#318]
Hi,

We have a scenario where we push the helm OCI artifacts using ORAS tool to a azure container registry. This registry has anonymous pull enabled and then our customers use the helm client to pull these OCI artifacts (helm chart pull)

1. oras push 'acr_url/chart_path:chart_version' '<path_to_compressed_artifacts>'
2. helm chart pull  'acr_url/chart_path:chart_version'

Recently, there was a breaking change introduced in helm version [3.7](https://github.com/helm/helm/releases/tag/v3.7.0) which has broken above experience. Step 2 mentioned above is failing when using 3.7 version of the helm client.

Imp Note: The failure in step2 happens even if we incorporate the helm client breaking changes. For eg, below command also fails:
helm pull oci://<acr_url/chart_path> --version chart_version

The way to make above command to work is to push the OCI artifacts using helm client as follows:
helm push '<path_to_compressed_artifacts>'  'oci://acr_url/chart_path:chart_version'

Can the above scenario be supported by ORAS tool? Basically we want the 'helm pull'(version 3.7) command to work for OCI artifacts pushed using ORAS tool.

**Comment by jdolitsky** [comment]
@akashkeshari - you simply need to define the mediatypes for both the manifest config and chart layer.

Something like the following would work:
```
echo "{}" > config.json
oras push --manifest-config config.json:application/vnd.cncf.helm.config.v1+json \
  <acr_url>/<chart_path>:<chart_version> \
  <path_to_chart_tgz>:application/vnd.cncf.helm.chart.content.v1.tar+gzip
```

`config.json` should technically be a JSON-ified version of the chart's `Chart.yaml` (vs. empty / `{}`), although this is currently unused.

**Comment by sajayantony** [comment]
Closing for now. Please reopen in case this needs attention @akashkeshari .
