### ISSUE TITLE
Release v0.20.0-alpha1

### ISSUE THREAD

**Issue by SteveLasker** [oras-project/oras#319]
Milestone [v0.20.0-alpha1](https://github.com/oras-project/oras/milestone/3)

## Release Deliverables

- [ ] Decide on main commit for release 
- [ ] Cut branch named `v0.20.0-alpha1` based on agreed upon main commit
- [ ] Cut a tag named `1v0.20.0-alpha1`
- [ ] Update README.md

Maintainers, please respond with a +1 comment once you are in favor of cutting this release?

**Comment by sajayantony** [comment]
We need a similar item for the library since notation and other clients would require these capabil

**Comment by jdolitsky** [comment]
Should v0.20 be v0.13 ? :)
