### ISSUE TITLE
Error: not_found downloading the manifest-config from a remote artifact

### ISSUE THREAD

**Issue by tompizmor** [oras-project/oras#325]
I am trying to download the manifest config from a remote container image as seen [here](https://github.com/oras-project/oras/pull/274) using the following command:

```
oras pull --manifest-config config.json:application/vnd.docker.distribution.manifest.v2+json OCI_REFERENCE
```

The config.json file is downloaded properly with the correct data, however, the cli is returning `Error: not_found` and exiting with error code 1.

Sorry if this issue is already duplicated. I tried looking similar ones but didn't fount it.

**Comment by SteveLasker** [comment]
Hi @tompizmor,
Did this get resolved?
