### ISSUE TITLE
oras push/cp --digest-only

### ISSUE THREAD

**Issue by SteveLasker** [oras-project/oras#326]
To support [tag update scenarios](https://github.com/notaryproject/notation/issues/45), where a new digest, and all its references should be pushed before a tag update is applied, we need a way to push a container image, or any `artifactType`, deferring the tag application.

Initially, I considered `docker push --digest-only`, and that may still be the best idea. Except, that would require a change to the docker client. 
This proposal focuses on `oras push` with a `--digest-only` flag. 

Perhaps `oras cp` with `--digest-only`

See [Docs: Add Promoting Scenario oras-project/oras#98](https://github.com/notaryproject/notation/pull/98) for more info

**Comment by shizhMSFT** [comment]
`oras push` without a tag means "pushing with digest only"

**Comment by SteveLasker** [comment]
@shizhMSFT, correct.

**Comment by qweeah** [comment]
@shizhMSFT Can you assign this to me? Thanks

**Comment by shizhMSFT** [comment]
Closed by #432
