### ISSUE TITLE
Remove fork of containerd

### ISSUE THREAD

**Issue by sajayantony** [oras-project/oras#327]
The current [containerd fork](https://github.com/oras-project/containerd) is not being used by artifacts and can be removed is my understanding and can be removed. 

/cc @bridgetkromhout since the fork is behind and needs attention.

**Comment by SteveLasker** [comment]
@shizhMSFT, do we need this fork?

**Comment by shizhMSFT** [comment]
No, the [artifacts](https://github.com/oras-project/oras/tree/artifacts) branch does not require customized `containerd` anymore.

Although `v0.2.0-alpha.1` requires that fork, it has been succeeded by the `artifacts` branch.

**Comment by SteveLasker** [comment]
Thanks @shizhMSFT 
Since alpha 1 is still our current release, should we keep the fork until alpha 2 is released?

**Comment by SteveLasker** [comment]
removed
