### ISSUE TITLE
Upgrade to oras-go v0.5.0

### ISSUE THREAD

**Issue by jdolitsky** [oras-project/oras#328]
Please see https://github.com/oras-project/oras-go/releases/tag/v0.5.0

**Comment by SteveLasker** [comment]
> Could push and pull simply be treated as an implicit copy from local->remote and remote->local?

I agree with @jdolitsky. I think users are used to `push` | `pull`, where `copy|cp` is yet a 3rd choice. They all implement the same underlying functionality, but the concepts are `push`, `pull`, `copy`

**Comment by deitch** [comment]
I can agree with that. We got away from push and pull underneath for technical reasons, to enable us to treat all targets as the same, and thus open up many possibilities. It shouldn't matter _from a technical perspective_ if the "from" is local or remote, or the "to" is local or remote, or both are remote, or one is a directory and one is memory, etc.

From a non-engineer UX perspective, though, having simple pull/push, which are just narrow special cases of copy, makes sense.

**Comment by sajayantony** [comment]
Should we close this in favor of upgrading to oras-go v2?

**Comment by SteveLasker** [comment]
closing as it looks like we have consensus on the external API vs. internal details
