### ISSUE TITLE
adopt a license scanning tool

### ISSUE THREAD

**Issue by bridgetkromhout** [oras-project/oras#334]
As a step towards completing the [CNCF Sandbox project onboarding](https://github.com/cncf/toc/issues/692), the ORAS project needs to adopt a license scanning tool, like FOSSA or Snyk.

https://www.cncf.io/services-for-projects/#tools

**Comment by jdolitsky** [comment]
Is there some example from another CNCF project somebody can share? Thinking we can easily copy paste something here

**Comment by jdolitsky** [comment]
this looks relevant https://github.com/distribution/distribution/pull/3396

**Comment by idvoretskyi** [comment]
@jdolitsky our suggestion would be to use either FOSSA (which is a pure license scanning tool mostly), or Snyk (which is way more feature-rich, and worth considering if you need other security&scanning features).

We can provide you with the premium-tier licenses for both tools, so let me know if you need any assistance with this :)

**Comment by SteveLasker** [comment]
Thanks, @idvoretskyi, FOSSA seems like a fine suggestion. Can you please set us up?

**Comment by idvoretskyi** [comment]
@SteveLasker sure! Please file a ticket to the CNCF ServiceDesk - servicedesk.cncf.io, happy to help

**Comment by bridgetkromhout** [comment]
This was [completed in April](https://github.com/cncf/toc/issues/692#issuecomment-1104378883) - resolving as already done.
