### ISSUE TITLE
start on CII best practices badge

### ISSUE THREAD

**Issue by bridgetkromhout** [oras-project/oras#335]
As a step towards completing the [CNCF Sandbox project onboarding](https://github.com/cncf/toc/issues/692), the ORAS project needs to start on a [CII best practices badge](https://bestpractices.coreinfrastructure.org/).

**Comment by jdolitsky** [comment]
Is there some example from another CNCF project somebody can share? Thinking we can easily copy paste something here

**Comment by jdolitsky** [comment]
seems relevant https://github.com/kedacore/keda/pull/691

**Comment by bridgetkromhout** [comment]
We can't just PR in a file - we need to click through starting on https://bestpractices.coreinfrastructure.org/en/projects/new and "add" ORAS as a project.

**Comment by bridgetkromhout** [comment]
https://bestpractices.coreinfrastructure.org/en/projects?q=oras
