### ISSUE TITLE
Update the release `v0.20.0-alpha2` to `v2.0.0-alpha.1`

### ISSUE THREAD

**Issue by SteveLasker** [oras-project/oras#350]
With the Helm OCI v1.0 release, all the work that was being tracked as `v0.20.0-alpha2` is no longer a relevant version.

Confirming with maintainers to change the release reference to `v2.0.0-alpha.1`

**Comment by shizhMSFT** [comment]
The `oras` CLI is following its own version. The next version is `v0.13.0`.
