### ISSUE TITLE
New tags with semantically older names exists in this repo

### ISSUE THREAD

**Issue by makkes** [oras-project/oras#352]
The two tags  v0.2.0-alpha.1 and v0.2.1-alpha.1 were created after the v0.12.0 tag. Should those have been called v0.20.x instead of v0.2.x? Was that a mistake?

**Comment by shizhMSFT** [comment]
Those `v0.2.x-alpha.1` are pre-releases built from the feature branch [artifacts](https://github.com/oras-project/oras/tree/artifacts). They will be removed once its feature being merged to the `main` branch. At that time, we will have `v0.13.x` and higher versions, which are semantically higher than `v0.2.x`.

/cc @SteveLasker
