### ISSUE TITLE
"sudo: command not found" in Azure pipeline

### ISSUE THREAD

**Issue by sturlath** [oras-project/oras#354]
For some reason I can´t install oras anymore in my Azure build pipeline ( `ubuntu-latest`).

The following bash (from [this blog](https://gaunacode.com/publishing-helm-3-charts-to-azure-container-registry-using-azure-devops-part-1)) **used to work** but doesn´t now

```
- bash: |
    set -e
    curl -LO https://github.com/deislabs/oras/releases/download/v0.8.1/oras_0.8.1_linux_amd64.tar.gz
    mkdir -p oras-install/
    tar -zxf oras_0.8.1_*.tar.gz -C oras-install/
    sudo mv oras-install/oras /usr/local/bin/
    sudo rm -rf oras_0.8.1_*.tar.gz oras-install/
```

It ends with `sudo: command not found`

![image](https://user-images.githubusercontent.com/2386572/154229678-7da53da6-37a0-489d-9bc1-16581d106c0d.png)

I have tried various other ways to install without luck. Any ideas what I need to do?

**Comment by sajayantony** [comment]
To unblock can we fully qualify the binary location or move it to a any writable location in $PATH ?

**Comment by sturlath** [comment]
Thank you. This here worked

```
- bash: |
    set -e
    curl -LO https://github.com/deislabs/oras/releases/download/v0.8.1/oras_0.8.1_linux_amd64.tar.gz
    mkdir -p oras-install/
    tar -zxf oras_0.8.1_*.tar.gz -C oras-install/
    export PATH=$PATH:/oras-install
  displayName: 'Install ORAS'
```

But I feel like there is more to this... it didn´t work on my "Build and test job" step but did if I moved it to the next job step... sorry but I don´t have time to research this more so am just leaving this here for others if it could help.
