### ISSUE TITLE
Feat req: Add layers to existing image

### ISSUE THREAD

**Issue by russkel** [oras-project/oras#363]
As a follow on from https://github.com/AkihiroSuda/apt-transport-oci/issues/2 it would be nice if oras had the ability to add layers to an existing image by only pushing the new layer[s] and updating the image config accordingly.

**Comment by shizhMSFT** [comment]
Mutating images is out of the scope of `oras`. However, you still can achieve it by the following steps

1. `oras manifest fetch` to fetch the manifest
2. `oras blob push` to push the new layers
3. Add the blob descriptors from the step 2 to the original manifest
4. `oras manifest push` to push the updated manifest
