### ISSUE TITLE
Could it be possible to add 32 bits binaries?

### ISSUE THREAD

**Issue by lmussier** [oras-project/oras#364]
Hi,

There is an amd64 and arm64 binaries availabe from the project, do you have the possibility to push the 32bits version for those artifacts?

**Comment by shizhMSFT** [comment]
Could we understand the scenarios of the demand of 32 bits arch binaries? and also the OS types?

**Comment by shizhMSFT** [comment]
@lmussier May we know the scenario behind this request?

The real scenario I could think about is the Raspberry Pi but in general all systems should be 64 bits.

**Comment by lmussier** [comment]
> @lmussier May we know the scenario behind this request?
> 
> The real scenario I could think about is the Raspberry Pi but in general all systems should be 64 bits.

@shizhMSFT  Sorry I've missed the question.
We are using low end arm32v7 devices as gateway, the idea is to retrieve artefact from somewhere, and since our system already have an oci registry we are putting these aretefacts (mainly conf and binaries) into the registry.

Thanks to have make it possible.

**Comment by shizhMSFT** [comment]
@qweeah has added arm32v7 support with #384 merged. We will release 32 bits binaries along with docker images when we release `v0.13.0`, which should happen soon.
