### ISSUE TITLE
Upgrade login/logout commands to oras-go v2

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#366]
Add login/logout packages for docker and general registries. Re-implement `login` and `logout` commands based on the new packages.

**Comment by qweeah** [comment]
Related to #328 and #347

**Comment by sajayantony** [comment]
Recommend breaking this up if possible or if not then can we describe why not in this thread.

**Comment by shizhMSFT** [comment]
@qweeah Looks like both `v0.4.0` and `v2.0.0` of `oras-go` can exist at the same time.

```
require (
	oras.land/oras-go v0.4.0
	oras.land/oras-go/v2 v2.0.0-20220415135518-c34895e747dc
)
```

Let's split this PR / issue into 3 parts:

1. Login / logout
2. Push
3. Pull

**Comment by qweeah** [comment]
@sajayantony @shizhMSFT I have made this issue specific for login/logout

**Comment by sajayantony** [comment]
Currently there is also an issue for supporting certs for auth #217 - how do we make sure that v2 can support cert login as well. 

Does the client have to significantly change?

**Comment by shizhMSFT** [comment]
We can address #217 after addressing #366. The idea is simple that the client should construct a specific TLS config for the client with the specified cert. No changes required for `oras-go`.
