### ISSUE TITLE
Support ORAS Artifact Spec RC2

### ISSUE THREAD

**Issue by sajayantony** [oras-project/oras#369]
Tracking releasing oras CLI of RC1 of artifact spec

Predecessor 
- [x] https://github.com/oras-project/distribution/issues/4
- [x] https://github.com/oras-project/oras-go/issues/131
- [x] https://github.com/oras-project/oras-go/issues/53
- [x] https://github.com/oras-project/oras-go/issues/63
- [x] https://github.com/oras-project/oras/issues/366

Issues that need resolution - 
- [x] https://github.com/oras-project/oras/issues/361
- [x] https://github.com/oras-project/oras/issues/362
- [x] https://github.com/oras-project/oras/issues/275
- [x] https://github.com/oras-project/oras/issues/301
- [x] https://github.com/oras-project/oras/issues/326
- [x] https://github.com/oras-project/oras/issues/307
- [x] https://github.com/oras-project/oras/issues/88

Triaging required - 

- https://github.com/oras-project/oras/issues/304
- https://github.com/oras-project/oras/issues/156
- https://github.com/oras-project/oras/issues/130

This issue will be updated to track the release of the CLI with support for RC1 artifacts support.

**Comment by sajayantony** [comment]
@qweeah - I will add more items to this issue as part of the migration to v2 and release of RC1.

**Comment by iamsamirzon** [comment]
@shizhMSFT -  Could you share your plans ( with dates) on updating the ORAS libraries that is utilized in Notation Client to support the latest ORAS artifact spec 1.0.0-rc.1 ? As I understand the current ORAS library used by Notation client is pegged to the earlier alpha revision ?

**Comment by shizhMSFT** [comment]
Notation depends on `oras-go` not `oras`. Therefore, you might want to track [this milestone](https://github.com/oras-project/oras-go/milestone/5) instead.

**Comment by iamsamirzon** [comment]
Thank you @shizhMSFT

**Comment by dtzar** [comment]
Suggestion @sajayantony to update the title to support RC2 since there is a very minor delta between and I don't really think it will change much on your action issue list above...

**Comment by shizhMSFT** [comment]
Closing as all items are resolved.
