### ISSUE TITLE
Push / Pull Artifacts from OCI Image Layout

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#378]
ORAS is evolving into a generic registry client along with `oras-go` v2. With the support of `oras-go` v2, the `oras` CLI should be able to push / pull artifacts from [OCI image layout](https://github.com/opencontainers/image-spec/blob/main/image-layout.md).

By resolving this issue, the following issue should be auto resolved.
- #244
- #245 
- #453

**Comment by sajayantony** [comment]
Can we discuss some candidate commands that would pull to tar and push the tar files?

**Comment by qweeah** [comment]
@sajayantony I added a hackmd doc, please help review the session[ Pushing and Pulling via oras copy](https://hackmd.io/ogglvwhLTVW2-T6b2JC_Gg#Pushing-and-Pulling-via-oras-copy)

**Comment by qweeah** [comment]
@FeynmanZhou Thanks for reminding. It's shared it, could you also help review it.

**Comment by qweeah** [comment]
Closing as it's already supportted in following commands:
- oras cp
- oras push
- oras pull
- oras attach
- oras manifest push
- oras blob push
- oras manifest fetch
- oras manifest fetch-config
- oras blob fetch
