### ISSUE TITLE
Discover sub-command is not using the latest ORAS Manifest Referrers API spec

### ISSUE THREAD

**Issue by swu000** [oras-project/oras#382]
The [current logic](https://github.com/oras-project/oras/blob/58fa344544b34571012d91f523cea54bf364549b/pkg/remotes/docker/discoverer.go#L119) still uses the old Manifest Referrers API spec. The API signature has been updated [here](https://github.com/oras-project/artifacts-spec/blob/main/manifest-referrers-api.md).

**Comment by shizhMSFT** [comment]
@swu000 Thanks for noticing. We planned to implement the latest spec in the near future, starting with `oras-go` v2.

The work is tracked at https://github.com/oras-project/oras-go/issues/131. Note that the underlying implementation of the `oras` CLI is migrating to `oras-go` v2, targeting the milestone `0.13.0`.
