### ISSUE TITLE
Tracking OCI working group proposal for reference artifacts

### ISSUE THREAD

**Issue by sajayantony** [oras-project/oras#406]
The OCI reference type working group is formulating a proposal for supporting storing reference types.
The ORAS cli could be expanded to support the OCI reference types.  

This issue can be used to track and gain consensus on the path forward. We need to update the design and related dependency enhancing [oras-go](https://github.com/oras-project/oras-go) libraries to absorb the OCI working groups proposal. 

This issue can be revisited and updated once there is a final proposal on the OCI working group. 
https://github.com/opencontainers/wg-reference-types 

Depends on - https://github.com/oras-project/oras-go/issues/308
 - https://github.com/oras-project/oras-go/issues/271

/cc @lachie83 @michaelb990

**Comment by shizhMSFT** [comment]
Closed by #652
