### ISSUE TITLE
Release v0.13.0

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#416]
We have upgraded the underlying `oras-go` dependency for the `oras` CLI from `v1` to `v2`, and is ready to release a `v0.13.0`.

/cc @FeynmanZhou @yizha1

**Comment by FeynmanZhou** [comment]
I assume we should update the download URL from `0.12.0` to `0.13.0` in some places accordingly. For example, the [installation guide](https://oras.land/cli/) should be updated. 

Please also help to add me as an assignee. I would like to check if any other user-facing changes we need to make.

**Comment by shizhMSFT** [comment]
Released https://github.com/oras-project/oras/releases/tag/v0.13.0
