### ISSUE TITLE
Use v1.0.0-rc.1 instead of v0.14.0

### ISSUE THREAD

**Issue by dtzar** [oras-project/oras#426]
Suggestion is to call the current v0.14.0 milestone as v1.0.0-rc.1 since at this point we will match the RC1 specifications, it will be easier for people to understand interoperability, AND there has been much work/releases to the oras client semver warranting a major version upgrade.

**Comment by shizhMSFT** [comment]
`v0.14.0` is not ready for `1.0.0` release. Once `v0.14.0` is done, we can decide whether we are ready for a `v1.0.0` release. At that time, we can consider `v1.0.0-rc.1` version.

Note: The version of `oras` and `oras-go` are tracked in their own pace. They depend on `artifact-spec` but should not use the same version.

**Comment by shizhMSFT** [comment]
In other words, we may have oras `v1.0.0-rc.2` --> oras-go `v2.0.0-rc.3` --> artifact-spec `v1.0.0-rc.1` where "-->" means "depends on".

**Comment by dtzar** [comment]
I understand they are tracked at their own pace.  That said, we should consider if it is possible to keep a versioning scheme which is easy to track that aligns with SemVer.   i.e. 
oras v1.x.x --> oras-go --> 2.x.x --> artifact-spec 1.x.x
OR
oras v0.x.x-**RC1** --> oras-go --> 2.x.x-**RC1** --> artifact-spect 1.x.x-**RC1**

**Comment by shizhMSFT** [comment]
What if `oras-go` wants to bump to `2.0.0-rc.2` after `2.0.0-rc.1`? We cannot have `2.1.0-rc.1` since we don't have `2.0.0` released yet.

**Comment by dtzar** [comment]
If you're following SemVer - from 0.13.0 to 0.14.0 is not really correct unless i'm missing something.  You're not really just adding new features, you're doing a major breaking change upgrade no?  If so - at a minimum IMO you should do 1.0.0-alpha/beta/etc.  @FeynmanZhou @yizha1

**Comment by FeynmanZhou** [comment]
According to the context above from @shizhMSFT, @dtzar and [SemVer](https://semver.org/), I vote to remain `v0.14.0` instead of `v1.0.0-rc.1` at the current stage.   

- ORAS CLI 0.14 still can not be considered a production-grade status at present. `v1.0.0-rc.1` is targeted to be released after `v0.15.0`. 
- Although there will be [two breaking releases](https://github.com/oras-project/oras/labels/breaking%20change) introduced in `v0.14.0`, it meets [SemVer item#4](https://semver.org/#spec-item-4).

**Comment by dtzar** [comment]
In keeping the current versioning plan of moving to v0.14.0, I suggest at a minimum clarifying the odd behavior that https://github.com/oras-project/oras/releases/tag/v0.2.1-alpha.1 has functionality which 0.13.0 does not and now is back again in 0.14.0.
