### ISSUE TITLE
Empty tag is not checked for `oras pull`

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#428]
https://github.com/oras-project/oras/blob/bb75f50fb5c21a59beb09ce1b632291182046632/cmd/oras/pull.go#L151

**Comment by shizhMSFT** [comment]
@qweeah Could you take a look?

**Comment by qweeah** [comment]
Ack

**Comment by FeynmanZhou** [comment]
We need to investigate if ORAS should support pulling the `latest` tag by default as Docker CLI.
