### ISSUE TITLE
Check the license header for ORAS and its dependencies

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras#435]
We need to check license headers and dependencies' licenses for ORAS before the RC.1 release. This is important to align with the open source compliance policy. 

[SkyWalking-Eyes](https://github.com/apache/skywalking-eyes) might be a good tool to implement the license header check and can be integrated into the [GitHub Actions workflow](https://github.com/marketplace/actions/license-eye).

**Comment by FeynmanZhou** [comment]
Two things we need to complete for this issue
- [ ] Generate a template to generate the summary of dependencies' licenses
- [ ] Add this license check to GitHub Actions

**Comment by shizhMSFT** [comment]
@jasminetMSFT Could you help this?

**Comment by FeynmanZhou** [comment]
@oras-project/oras-maintainers 

@jasminetMSFT checked the license header for ORAS and its dependencies for ORAS, ORAS-go, and ORAS-py repo using SkyWalking Eye. You can find the scanning results from this [doc](https://hackmd.io/w15Y3hdKS9K5Wm-giaEzkA?view).

The dependencies' licenses are correct. We detected some source code files lack license headers, the next step is to fix those files.
