### ISSUE TITLE
Return error if tag or digest is not specified

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#439]
Impacted commands:

- [x] `oras pull` #440
- [x] `oras discover` #442
- [x] `oras copy` #432

**Comment by qweeah** [comment]
ack

**Comment by CharingJC** [comment]
I will help with the copyCmd

**Comment by FeynmanZhou** [comment]
@shizhMSFT  I assume `oras pull` has supported the error return. Is there any additional work?

```
$ ./oras pull mcr.microsoft.com/mcr/hello-world
Error: image reference format is invalid. Please specify <name:tag|name@digest>
```

**Comment by qweeah** [comment]
@FeynmanZhou You must be using ORAS 0.12.0

**Comment by sajayantony** [comment]
So does this mean that oras will not default to latest?
