### ISSUE TITLE
`--artifact-type` support in `oras push`

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#466]
This proposal contains two changes derived from #361.

1. When `--artifact-type $type` is specified, `oras push` will change the media type of the config blob, which is equivalent to `--manifest-config <(echo {}):$type`
2. When there is no blob specified, `--artifact-type` must be specified and an ORAS artifact manifest will be pushed.

**Comment by sajayantony** [comment]
Could we do a zero byte blob for this?

**Comment by shizhMSFT** [comment]
> Could we do a zero byte blob for this?

We are still not sure if a zero-byte config blob is allowed for all registries.

**Comment by shizhMSFT** [comment]
BTW, even if we have a zero-byte blob, we still need to upload that empty blob.

**Comment by yuehaoliang-microsoft** [comment]
Hi, team! I'll start to work on resolving this issue.

**Comment by sajayantony** [comment]
Yes zero byte blobs need to be uploaded but you can choose to short circuit it on the pull path. 
Also registry implementation may also choose to short circuit the writes.

**Comment by sajayantony** [comment]
Thinking more have we considered using --config-media-type and --artifact-type to disambiguate between them.
This way there is no guess work on the CLI and the flags are mutually exclusive since `artifactManifest` does not have a config media type.

**Comment by shizhMSFT** [comment]
> Thinking more have we considered using --config-media-type and --artifact-type to disambiguate between them. This way there is no guess work on the CLI and the flags are mutually exclusive since `artifactManifest` does not have a config media type.

I think here is to make the concept of `artifact type` transparent. Currently, we use OCI manifest to mimic ORAS artifact manifest where the config media type is used as artifact type. In the future when ORAS artifact manifest is widely adopted, we can default `oras push` to ORAS artifact manifest without interface changes.

**Comment by yuehaoliang-microsoft** [comment]
I made a mistake to handle #483, as I clicked the Github UI "fetch upstream" in my repo/branch. Since that PR attempted to merge from my repo/branch, after my repo/branch is updated to upstream, the PR was automatedly closed.

**Comment by shizhMSFT** [comment]
Closing this as #482 is merged and #486 is closed.

**Comment by SteveLasker** [comment]
Would like to make sure we’re in sync on the UX and experience before closing.

**Comment by shizhMSFT** [comment]
Closing again as https://github.com/oras-project/oras-go/issues/271 is planned.
