### ISSUE TITLE
Command to create a tag for a manifest in the remote registry

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#471]
The proposed command is:

```
Usage:
  oras tag  REPO:<TAG|DIGEST> NEW_TAG

Flags:
  --ca-file string               server certificate authority file for the remote registry
  -d, --debug                    debug mode
  -h, --help                     help for tagging
      --insecure                 allow connections to SSL registry without certs
  -p, --password string          registry password or identity token
      --password-stdin           read password or identity token from stdin
      --plain-http               allow insecure connections to registry without SSL check
  -u, --username string          registry username
  -v, --verbose                  verbose output
```

Relate to #459

**Comment by jwang1013** [comment]
I will take care of this issue.

**Comment by jwang1013** [comment]
Do we need to support multi-tagging in one cmd? If so, what should we use as a delimiter.  @FeynmanZhou @shizhMSFT

**Comment by sajayantony** [comment]
Let's use a multi-value flag similar to 
```
➜ docker build -t hello-world:v1 -t hello-world:v2 .
```

This would avoid the need for a delimiter.

**Comment by shizhMSFT** [comment]
Linking https://github.com/oras-project/oras/issues/355

**Comment by FeynmanZhou** [comment]
> Do we need to support multi-tagging in one cmd? If so, what should we use as a delimiter. @FeynmanZhou @shizhMSFT
@jwang1013 @oras-project/oras-maintainers 
It makes sense to support multi-tagging in the `oras push` group instead of `oras tag`. There is a request from a user in https://github.com/oras-project/oras/issues/355. How about we create a separate issue to track multi-tagging in the `oras push` group?

**Comment by sajayantony** [comment]
> Let's use a multi-value flag similar to
> 
> ```
> ➜ docker build -t hello-world:v1 -t hello-world:v2 .
> ```
> 
> This would avoid the need for a delimiter.

I realized that multiple flag values would mean you can pass in different repos. This might not be a good idea now and the comma separated values are probably better.
