### ISSUE TITLE
Command to delete a manifest from a remote registry

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#473]
The proposed commands is:

```
Usage:
  oras manifest delete REG/REPO<:TAG|@DIGEST> [flags]

Flags:
  --ca-file string               server certificate authority file for the remote registry
  -d, --debug                    debug mode
  -h, --help                     help for deleting a manifest
      --insecure                 allow connections to SSL registry without certs
  -p, --password string          registry password or identity token
      --password-stdin           read password or identity token from stdin
      --plain-http               allow insecure connections to registry without SSL check
  -u, --username string          registry username
  -v, --verbose                  verbose output
      --descriptor               show the descriptor of deleted blob
      --yes                      do not prompt for confirmation
```
Related to #459

**Comment by yuehaoliang-microsoft** [comment]
Hi team, I'm interesting in resolve both this issue and #472.

**Comment by yuehaoliang-microsoft** [comment]
The UX of `az acr manifest delete` is:
```
yuehaoliang@yuehaoliang:~$ az acr manifest delete yuehaoliang.azurecr.io/hello:v1
Command group 'acr manifest' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Are you sure you want to delete the artifact 'sha256:f04e7500b73d0d0b970c04f1a53c79134f5ecffb8690cb454dca551354763412' and all manifests that refer to it? (y/n): y
```

Refer to [az-acr-manifest-delete](https://docs.microsoft.com/en-us/cli/azure/acr/manifest?view=azure-cli-latest#az-acr-manifest-delete).

**Comment by yuehaoliang-microsoft** [comment]
Use case: use `-h` to see the usage of `oras manifest delete`:
<img width="857" alt="image" src="https://user-images.githubusercontent.com/109199020/186629264-975bea9a-e662-4b5b-aae6-c9299f9b2d10.png">
Use Case: decide not to delete the manifest:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/109199020/186625568-bc32fb29-79a4-437e-a4c8-de92e82eb0b6.png">
Use Case: decide to delete the manifest:
<img width="857" alt="image" src="https://user-images.githubusercontent.com/109199020/186625866-01d280fe-4f10-4f18-aaf5-a3cad160e303.png">
Use Case: user flag `--yes` or `-y` to confirm deleting the manifest:
<img width="860" alt="image" src="https://user-images.githubusercontent.com/109199020/186626103-add67c90-f4f5-426a-912d-55ee007c62dd.png">
Use Case: `--descriptor` will print the descriptor of the manifest:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/109199020/186627965-18bb4336-6c7b-449a-bc65-f1ca6b4cbbf5.png">
Use Case: use digest to delete the manifest:
<img width="860" alt="image" src="https://user-images.githubusercontent.com/109199020/186628257-b54afd95-ea31-48ad-a0bf-020ce7397a71.png">
Use case: miss the tag or digest
<img width="859" alt="image" src="https://user-images.githubusercontent.com/109199020/186628605-a2c9c834-840d-46d0-bb4d-6ef258b2ce70.png">
Use case: the manifest does not exist:
<img width="861" alt="image" src="https://user-images.githubusercontent.com/109199020/186628705-7ddadf3d-6945-4b6a-9002-cce71309b6d7.png">

According to the discussion about UX listed in #459, newly made some modification to the above PR. Here attached some simple use cases.

**Comment by yuehaoliang-microsoft** [comment]
Updated some UX:
<img width="862" alt="image" src="https://user-images.githubusercontent.com/109199020/188071790-fdea160a-fafc-4025-8721-de0e54eaa2f8.png">
<img width="863" alt="image" src="https://user-images.githubusercontent.com/109199020/188071853-7e800653-6806-4bba-91f6-42cb016e500d.png">
<img width="866" alt="image" src="https://user-images.githubusercontent.com/109199020/188071952-fa15e42f-d4c3-46cc-9916-bb59969c018d.png">
<img width="863" alt="image" src="https://user-images.githubusercontent.com/109199020/188072515-bc378a49-8286-42b3-948c-a7103f163e61.png">
<img width="862" alt="image" src="https://user-images.githubusercontent.com/109199020/188072593-9c60a23e-db50-468f-bcf0-b53bf773f06d.png">
<img width="863" alt="image" src="https://user-images.githubusercontent.com/109199020/188072672-7d89f97a-beb4-44c0-9c88-c43085ae964a.png">
<img width="863" alt="image" src="https://user-images.githubusercontent.com/109199020/188072764-22cfa1c3-964e-42e4-accb-88d894015dcf.png">

**Comment by yuehaoliang-microsoft** [comment]
Should `oras manifest delete` support `--platform` to delete the manifest of a specific platform if target is multi-platform capable?
@qweeah @shizhMSFT

**Comment by shizhMSFT** [comment]
No, `--plaform` should not apply to any delete operation.
