### ISSUE TITLE
Command to push a blob to a remote registry

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#476]
The proposed commands is:

```
Usage:
  oras blob push REG/REPO PATH [flags]

Flags:
  --ca-file string               server certificate authority file for the remote registry
  -d, --debug                    debug mode
  -h, --help                     help for pushing a blob
      --insecure                 allow connections to SSL registry without certs
  -p, --password string          registry password or identity token
      --password-stdin           read password or identity token from stdin
      --plain-http               allow insecure connections to registry without SSL check
  -u, --username string          registry username
  -v, --verbose                  verbose output
```

Related to #459

**Comment by lizMSFT** [comment]
please assign this to me

**Comment by lizMSFT** [comment]
Current UX:
![image](https://user-images.githubusercontent.com/108315938/186065386-ddd9ca35-a834-48e3-98c7-38373ab35eb5.png)
![image](https://user-images.githubusercontent.com/108315938/186065444-aaf059ec-3e82-4a68-9840-d8aa95534860.png)

**Comment by yizha1** [comment]
One minor comment:
- Push a blob to `a` remote registry

Some questions:

- Can we change the mediaType for the blob?
- What is the supported maximum size of a blob? What will happen if the blob size exceeds the maximum value?
- Can we cancel pushing a blob? What will happen if I `ctrl+c` while pushing a large blob?

**Comment by lizMSFT** [comment]
Hi @yizha1,
> * Push a blob to `a` remote registry

Thanks for pointing out, I will change the command message to `Push a blob to a remote registry` 👌

> Can we change the mediaType for the blob?

I'd say no. The blob only has one mediaType `application/octet-stream`, ref: https://docs.docker.com/registry/spec/api/#initiate-blob-upload

> What is the supported maximum size of a blob? What will happen if the blob size exceeds the maximum value?

Currently we do not have a maximum limit on the size of a blob from our ORAS side. But a registry should have some limit on the maximum blob size that it can accept. So if the blob size exceeds the maximum value, the error will be returned from registry side.

> Can we cancel pushing a blob? What will happen if I ctrl+c while pushing a large blob?

Yes, we can cancel pushing a blob by using ctrl+c. If the push operation has not been completely finished yet, then the process will be stopped.

**Comment by FeynmanZhou** [comment]
The overall UX of `oras push` looks intuitive to me. Would it be more exact to update `<name>` to `<registry>`?
![image](https://user-images.githubusercontent.com/40452856/186460544-58839476-8b51-47dc-817d-2889d204cb0b.png)

**Comment by sajayantony** [comment]
I think it would be helpful to output the full descriptor to a file. 
without that how is the user planning to use this ? 
/cc @shizhMSFT

**Comment by shizhMSFT** [comment]
@qweeah We need to unify the UX across all command sets like `oras manifest` and `oras blob` as they all do CRUD. Let's discuss it.

**Comment by lizMSFT** [comment]
> The overall UX of `oras push` looks intuitive to me. Would it be more exact to update `<name>` to `<registry>`? 

That's a good idea! But I notice we are now only using `registry` in login and logout commands, and `name` for others (such as `oras push`). We might need to unify the UX across all commands first.
![image](https://user-images.githubusercontent.com/108315938/186562906-2f8e15b2-621d-480a-a6aa-11b7faa508ba.png)

**Comment by lizMSFT** [comment]
UX design (08/26/2022)
```
# stdout human readable messages 
oras blob push <name> <path>
# stdout json descriptor
oras blob push <name> <path> --descriptor 
# stdout prettified json descriptor
oras blob push <name> <path> --descriptor --pretty
# read from stdin, then push to <name> registry. stdout human readable messages 
# return error if --password-stdin flag is used at the same time
oras blob push <name> - 
```
![image](https://user-images.githubusercontent.com/108315938/186927989-674db588-8a03-4ff2-8706-56fc2901531d.png)
help doc
![image](https://user-images.githubusercontent.com/108315938/186929218-7639dbeb-2742-419e-ac66-a7021887be60.png)
