### ISSUE TITLE
--manifest-annotations can't work as expect when push to GitHub Packages

### ISSUE THREAD

**Issue by yangjuexi-ones** [oras-project/oras#492]
> When i push my artifact to GitHub Packages , the --manifest-annotations don't work as documentation described

## Details:

1. command and oras version(0.13): 
        ```
        oras push --manifest-annotations annotations.json ghcr.io/yangjuexi-ones/test:1.0 cake.txt
        ```
2. content in annotations.json
        
```
{
              "$config": {
                      "hello": "world"
               },
             "$manifest": {
                     "foo": "bar"
                },
                "cake.txt": {
                       "fun": "more cream"
                 }
 }
```

3. expecte result 
  
      
![image](https://user-images.githubusercontent.com/106501704/184310023-d823345f-aa54-462d-ae5d-70a657993959.png)

5. GitHub Packages Page 
     
![image](https://user-images.githubusercontent.com/106501704/184310206-ab2baaf1-1855-4d59-bc3a-f52a028beda6.png)

## question
something i forget to do ? the result don't match what showed in documentation.

**Comment by qweeah** [comment]
Which version of oras are you using(you can check via `oras version`)

**Comment by qweeah** [comment]
My guess is that GHCR did something when redering the manifest on the web page, e.g. the manifest annontation key should be `annotations` but in your screenshot it's `labels`. You can validate that via comparing the manifest digests.

**Comment by yangjuexi-ones** [comment]
> 

The oras version is 0.13.0. I just copy the code snippet from official website and use it in GitHub Action.
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/106501704/184572668-a9821dac-59a8-48ea-b287-e4a39614aa6a.png">

**Comment by yangjuexi-ones** [comment]
> Which version of oras are you using(you can check via `oras version`)

The oras version is 0.13.0. I just copy the code snippet from official website and use it in GitHub Action.
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/106501704/184572668-a9821dac-59a8-48ea-b287-e4a39614aa6a.png">

**Comment by qweeah** [comment]
Github web page is not displaying the real manifest content stored in GHCR.

**Comment by qweeah** [comment]
Unfortunately ORAS doesn't support getting a raw manifest for now(but it should be in 0.14.0, see #463)

You can verify that via some other reigstry client, like `crane manifest get ghcr.io/yangjuexi-ones/test:1.0` to see the real content of the uploaded manifest. ([installation](https://github.com/google/go-containerregistry/tree/main/cmd/crane#installation))

**Comment by yangjuexi-ones** [comment]
> Github web page is not displaying the real manifest content stored in GHCR.

Thanks. I have checked the document of GHCR and find nothing about this.So, i open a discussion in community.

**Comment by shizhMSFT** [comment]
The manifest presented by the "GitHub Packages Page" is re-organized and is **NOT** the original update manifest. If you copy and paste the manifest to a file and calculate a sha256 digest of it, you will see a manifest digest mismatch.

**Comment by shizhMSFT** [comment]
For instance, the `digest` field is not in the original manifest but appears on the GitHub packages page.

**Comment by yangjuexi-ones** [comment]
> Unfortunately ORAS doesn't support getting a raw manifest for now(but it should be in 0.14.0, see #463)

That's good news.Can't wait to try it.

**Comment by yangjuexi-ones** [comment]
> For instance, the `digest` field is not in the original manifest but appears on the GitHub packages page.

Thanks. That's right. I have open a discussion in GHCR community and maybe the developer will give me an guidance.

**Comment by shizhMSFT** [comment]
Closing this issue as it has been resolved.
