### ISSUE TITLE
Improve error message on platform mismatch

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#498]
We should improve the error message when the platform is not found and maybe even validate that the platform is invalid.

```
➜ oras manifest fetch docker.io/library/ubuntu:20.04 --platform invalid
Error: not found
```

**Comment by shizhMSFT** [comment]
@lizMSFT Could you help with this?

**Comment by lizMSFT** [comment]
> @lizMSFT Could you help with this?

I will take care of it👌
