### ISSUE TITLE
Propose to release ORAS CLI v0.14.0

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras#512]
Hi team @oras-project/oras-client-release-managers , 

The ORAS community has put great effort into ORAS projects in the past months, completed the development of planned features, fixed known bugs, and reached the following milestones, I am proposing to release ORAS CLI v0.14.0. 

- [x] [ORAS-go v2.0.0 RC.2](https://github.com/oras-project/oras-go/releases/tag/v2.0.0-rc.2) released on Aug 12
- [x] All [ORAS CLI issues tagged with milestone v0.14.0](https://github.com/oras-project/oras/milestone/6) have been resolved
- [x] Complete the functional testing and validate the usability of new features/commands
- [x] The Release Notes for ORAS CLI v0.14.0 is ready

After the items above are completed, we will cut the release for ORAS v0.14.0 on Aug 22 tentatively. Then we will work on the following items in parallel.

- [ ] Publish the announcement blog 
- [ ] Update the ORAS documentation to up-to-date

Please let us know if you have any ideas or proposals for the release criteria and [release process](https://github.com/oras-project/community/blob/main/governance/RELEASE-PROCESS.md).

**Comment by qweeah** [comment]
- [ ] Update the [quick start doc](https://github.com/oras-project/artifacts-spec/blob/main/docs/quick-start.md) with `attach` command

**Comment by FeynmanZhou** [comment]
Close this issue since we have other three separate issues to track:
https://github.com/oras-project/artifacts-spec/issues/113
https://github.com/oras-project/oras-www/issues/49
https://github.com/oras-project/oras-www/issues/50
