### ISSUE TITLE
can't pull behind proxy on version 0.13.0

### ISSUE THREAD

**Issue by danielzhanghl** [oras-project/oras#513]
Hi,
I met issue when pull one artifact behind proxy with 0.13.0, procedure is as below, and if I use the version 0.12, that works fine(the proxy is set correctly, as I could download ORAS and curl the endpoint ), is there anything I missed?
thanks,

# curl -LO https://github.com/oras-project/oras/releases/download/v0.13.0/oras_0.13.0_linux_amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 3112k  100 3112k    0     0  2427k      0  0:00:01  0:00:01 --:--:-- 8125k

# tar xvf oras_0.13.0_linux_amd64.tar.gz
LICENSE
oras

# ./oras pull -d ghcr.io/aquasecurity/trivy-db:2
DEBU[0000]  Request URL: "**https://ghcr.io/v2/aquasecurity/trivy-db/manifests/2**"
DEBU[0000]  Request method: "GET"
DEBU[0000]  Request headers:
DEBU[0000]    "Accept": "application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, application/vnd.cncf.oras.artifact.manifest.v1+json"
DEBU[0000]    "User-Agent": "oras/0.13.0"

ERRO[0128] Error in getting response: %!w(*net.OpError=&{dial tcp <nil> 0xc0001824e0 0xc0000629a0})
Error: Get "https://ghcr.io/v2/aquasecurity/trivy-db/manifests/2": **dial tcp 140.82.112.34:443: connect: connection timed out**
]# ./oras  version
Version:        0.13.0
Go version:     go1.18.1
Git commit:     bb75f50fb5c21a59beb09ce1b632291182046632
Git tree state: clean

# curl **https://ghcr.io/v2/aquasecurity/trivy-db/manifests/2**
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required"}]}

# env |grep -i proxy
http_proxy=13.24.48.34:8000
https_proxy=13.24.48.34:8000
HTTPS_PROXY=13.24.48.34:8000
HTTP_PROXY=13.24.48.34:8000

**Comment by qweeah** [comment]
@danielzhanghl Thanks for reporting this. Will fix in #514 and release it today in 0.14.0

**Comment by shizhMSFT** [comment]
Reopen for now and will be closed once #512 is resolved.

**Comment by danielzhanghl** [comment]
thanks for the quick action! will have a try in 0.14.0

**Comment by shizhMSFT** [comment]
@danielzhanghl oras CLI [v0.14.0](https://github.com/oras-project/oras/releases/tag/v0.14.0) is released! Could you have a try?

**Comment by danielzhanghl** [comment]
0.14.0 works very well, thank!
