### ISSUE TITLE
Enhance `manifet fetch`

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#531]
1. Refactor the implementation with `oras.Fetch` and `oras.FetchBytes` in oras-go
2. Add below UX
```
# Fetch
# add output flag
oras manifest fetch <name> --pretty > <path>                     # manifest prettified to file via stdout
oras manifest fetch <name> --output <path> --pretty              # manifest raw to file
oras manifest fetch <name> --output - --pretty > <path>          # manifest prettified to file
oras manifest fetch <name> --output <path> --pretty --descriptor # descriptor prettified
# --output - cannot be used with --descriptor at the same time
```

**Comment by shizhMSFT** [comment]
@yuehaoliang-microsoft Could you help this issue?

**Comment by yuehaoliang-microsoft** [comment]
I'll leverage new methods in oras-go to improve `oras manifest fetch`, and support new flags.

**Comment by yuehaoliang-microsoft** [comment]
@shizhMSFT Should `oras manifest fetch <name> --output <path> --pretty` save a prettified content to the file? If not, should it through an error to say that `--output <path>` and `--pretty` can't be used together.
@lizMSFT I think `blob fetch` should through an error in this case.

**Comment by shizhMSFT** [comment]
> Should oras manifest fetch <name> --output <path> --pretty save a prettified content to the file?
No. `--pretty` should only work on `stdout`. If `--pretty` is specified with `--output`, the `--pretty` option is ignored.

**Comment by yuehaoliang-microsoft** [comment]
> > Should oras manifest fetch  --output  --pretty save a prettified content to the file?
> 
> No. `--pretty` should only work on `stdout`. If `--pretty` is specified with `--output`, the `--pretty` option is ignored.

Thank you for clarifying. I see, `--pretty` should be just ignored when used with `oras manifest fetch <name> --output <path>`.
