### ISSUE TITLE
ORAS CLI should support interacting with docker.io

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras#542]
Currently, ORAS is not able to authenticate `docker.io` and will return 401 error:
```
$ oras cp mcr.microsoft.com/mmlspark/spark2.4:1.0.0 docker.io/pengfeizhou/spark2.4:1.0.0
Error: POST "https://registry-1.docker.io/v2/pengfeizhou/spark2.4/blobs/uploads/": unexpected status code 401: unauthorized: authentication required
```
It requires users to specify `registry-1.docker.io` to authenticate with DockerHub. I think ORAS should support the most common domain `docker.io` when interacting with DockerHub.

**Comment by shizhMSFT** [comment]
The root cause is the `docker.io` is a very special case. In docker CLI / daemon, the domain `docker.io` is mapped to `registry-1.docker.io`. `oras-go` does the same trick for `docker.io`.

However, when accessing the credentials, the hostname `registry-1.docker.io` is not recognized as `docker.io`.

@junczhu Could you help fixing this bug and update [internal/credential/store.go](https://github.com/oras-project/oras/blob/main/internal/credential/store.go) to match the same behavior as docker daemon and docker CLI?

**Comment by junczhu** [comment]
Thanks for the insight.
@shizhMSFT Please assign this issue to me and I will start working on it.

**Comment by junczhu** [comment]
@FeynmanZhou Have open an PR #549 for this fix. 
Please check it out

<img width="731" alt="image" src="https://user-images.githubusercontent.com/74894646/189294567-5c229d7a-cddb-4ac6-99b5-4193912fc8f8.png">

/cc @qweeah @shizhMSFT

**Comment by junczhu** [comment]
For your information:

By default, command `docker login` and `docker login docker.io` will store following credential on line 3.
Command `docker login registry-1.docker.io` will store the credential on line 4.

<img width="380" alt="image" src="https://user-images.githubusercontent.com/74894646/189298062-97f6adca-327e-4c18-a614-fa9709247ced.png">

And when using docker cli to push an image to the docker hub, with default hostname, only the credential on line 3 can be used.

When explicitly using registry-1.docker.io as hostname, like `registry-1.docker.io/username/repositoryname`, only the second credential can be used.

In ORAS, we have mapped `'docker.io'` to `'registry-1.docker.io'` for registry reference.
And I am going to apply the same operation in the ORAS CLI to help fix this issue

**Comment by junczhu** [comment]
Hi @FeynmanZhou , the issue has been fixed. 
Kindly check it out once you are available. 😊

/cc @shizhMSFT @qweeah

**Comment by FeynmanZhou** [comment]
@junczhu Thanks for your quick response and action. I will test it from the latest main branch. Let's keep this issue open until I verify this issue.

**Comment by FeynmanZhou** [comment]
> @junczhu Thanks for your quick response and action. I will test it from the latest main branch. Let's keep this issue open until I verify this issue.

@shizhMSFT @junczhu 
I verified ORAS CLI from the main branch and it works with `docker.io`. Thanks for fixing it!
