### ISSUE TITLE
Need verify rc against the descriptor after calling oras.Fetch()

### ISSUE THREAD

**Issue by lizMSFT** [oras-project/oras#547]
When reading from the io.ReadCloser returned by `oras.Fetch()` function, it's recommended to verify the read content against the descriptor. 
We could use the utility method from ORAS-GO to do the verification after https://github.com/oras-project/oras-go/issues/306 being resolved.

reference: 
`desc, rc, err := oras.Fetch(ctx, src, opts.targetRef, oras.FetchOptions{})`
https://github.com/oras-project/oras/pull/520#discussion_r965650328

**Comment by wangxiaoxuan273** [comment]
Sure.
