### ISSUE TITLE
Error: unknown flag: --manifest-config

### ISSUE THREAD

**Issue by Hiieu** [oras-project/oras#548]
It looks like oras doesn't recognize the `--manifest-config` parameter:

```
oras push --manifest-config config.json localhost:5000/hello:latest hi.txt

Error: unknown flag: --manifest-config
```

Version:
```
Version:    0.14.1+Homebrew
Go version: go1.19
```

**Comment by qweeah** [comment]
@Hiieu It's changed to `--config`, see **Breaking Changes** in [0.14.0 releasing log](https://github.com/oras-project/oras/releases/tag/v0.14.0)
