### ISSUE TITLE
e2e: prepare registry mount files for command specs

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#553]
For command-specific E2E tests, the test spec should not have dependency on each other. So the underlying storage for testing distribution need to be initialized before test runs. E.g. `oras pull` need to test pulling `hello:test` so the manifest blob, config blob and layer blobs will be mounted into the test distribution before running the tests.

The mount files should be checked into the source code. Related to #523

**Comment by wju-MSFT** [comment]
Please assign this to me.
