### ISSUE TITLE
Failed to attach a SBOM json to the image in Docker Hub

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras#557]
I generated an SBOM JSON file using SBOM Tool and then attached it to the docker image in Docker Hub, but it returns error code 400 as follows, is anything not supported by the Docker Hub server side, or is something wrong in my SBOM file? 

```
$ oras attach registry-1.docker.io/pengfeizhou/spark2.4:1.0.0 manifest.spdx.json --artifact-type example/sbom
Uploading 97a5dc071dd1 manifest.spdx.json
Uploaded  97a5dc071dd1 manifest.spdx.json
Error: PUT "https://registry-1.docker.io/v2/pengfeizhou/spark2.4/manifests/sha256:5ed6455151b90a036a7cff0b96c4ff00777284a5f1a4c3a38d8c5825bfbc6018": unexpected status code 400: manifest invalid: manifest invalid
```

See the reproduced steps from this [PR](https://github.com/oras-project/oras-www/pull/52/files#diff-af43525124ec8a0512a648e97646e1e106d92ca7117551a4ca6020d147cd503bR51) if needed.

**Comment by qweeah** [comment]
It has nothing to do with SBOM. `oras attach` will generate an [oras artifact](https://github.com/oras-project/artifacts-spec/blob/main/artifact-manifest.md#oras-artifact-manifest-spec), which is not supported by docker registry.

**Comment by shizhMSFT** [comment]
@junczhu Could you help verifying if Docker Hub support OCI image manfiest.

**Comment by junczhu** [comment]
> @junczhu Could you help verifying if Docker Hub support OCI image manfiest.

Sure

**Comment by shizhMSFT** [comment]
If it supports **OCI image manifest**, could you try to push a manifest with a `refers` field?

**Comment by junczhu** [comment]
> If it supports **OCI image manifest**, could you try to push a manifest with a `refers` field?

@shizhMSFT  Based on my test, Docker Hub supports OCI image manifest and we can push a manifest with a refers field.

<img width="881" alt="image" src="https://user-images.githubusercontent.com/74894646/190063823-9df80484-4dc1-48a5-8800-2952664fe5e7.png">

After update the manifest, I am still available to pull the image from Docker Hub with docker CLI
Besides, refers field can be add to docker image manifest("application/vnd.docker.distribution.manifest.v2+json") as well.

/cc @FeynmanZhou @qweeah 

Reference: 
[oci image manifest](https://github.com/opencontainers/image-spec/blob/main/manifest.md)
[Docker Registry API](https://docs.docker.com/registry/spec/api/#put-manifest:~:text=too%20many%20times-,PUT%20Manifest,-Put%20the%20manifest)
[oras-go: PushReference](https://github.com/oras-project/oras-go/blob/v2.0.0-rc.3/registry/remote/repository.go#L179)

**Comment by shizhMSFT** [comment]
@junczhu Does Docker Hub support arbitrary media types for config and layers?

**Comment by junczhu** [comment]
> arbitrary media types

@shizhMSFT 
Docker Hub supports arbitrary media types for layers.
And based on my test, config media type should match the manifest media type.

eg. 
```
{
"schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 1457,
      "digest": ""
   },
   ...   
}
```

```
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "config": {
    "mediaType": "application/vnd.oci.image.config.v1+json",
    "size": 7023,
    "digest": ""
  },
  ...
}
```

**Comment by FeynmanZhou** [comment]
We still need to test this case with `oras attach` to attach artifacts to Docker Hub against the [OCI artifact support feature announced by Docker Hub](https://www.docker.com/blog/announcing-docker-hub-oci-artifacts-support/) using ORAS CLI 0.16.

**Comment by sajayantony** [comment]
I think even attach might have an issue until Docker supports the subject property in an image manifest. I think oras CLI might need a way to skip putting the subject in case put comes back with an Invalid manifest for image manifest push. 
but continue updating the index update @shizhMSFT

**Comment by shizhMSFT** [comment]
Linking #666

**Comment by shizhMSFT** [comment]
Closing since Docker Hub does not support `subject` field in the OCI image manifest
