### ISSUE TITLE
delete multiple manifests at the same time

### ISSUE THREAD

**Issue by yuehaoliang-microsoft** [oras-project/oras#560]
In #473, we introduced a new command `oras manifest delete` to let user delete a specific manifest by tag or its digest. Do we want to support deleting multiple manifests in a single command?

Usage:
  `oras manifest delete [flags] REG/REPO<:TAG1|@DIGEST1> REG/REPO<:TAG2|@DIGEST2>` ...

**Comment by sajayantony** [comment]
Maybe you can post a comment with the option of NO so that folks can vote for yes or No. 
my vote is no and let someone from the community open an issue with this need.

**Comment by yuehaoliang-microsoft** [comment]
> Maybe you can post a comment with the option of NO so that folks can vote for yes or No. my vote is no and let someone from the community open an issue with this need.

It's a really good idea.

Hello guys, please vote to this comment for whether supporting deleting multiple manifests in a single command is a valuable experience for our users. Please have a 👍 for "I agree" and 👎 for "I don't think so".

**Comment by qweeah** [comment]
What benefit can an user get from this multi-deleting?
If this command breaks halfway, can user rerun the same command?

**Comment by FeynmanZhou** [comment]
IMO, the only benefit is to allow delete manifest in bulk. But this use case is not frequent at all. 
I can confirm it with some users in the community to see whether this is a significant use case.

**Comment by sajayantony** [comment]
This issues has not had activity in quite some time. I'm manually closing this issue for now. Please feel free to reopen if want to consider this feature again.
