### ISSUE TITLE
e2e: collect common use cases for scenario-based e2e test 

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#562]
For now we have below use cases:

OCI Image users:
- should be able to use `oras push`oras  command to upload files
- should be able to use `oras manifest fetch`oras  command to inspect the packed manifest
- should be able to use `oras pull` command to pull uploaded files
- should be able to user `oras copy` command to copy the OCI image to a new repository

Common ORAS users:
This is pending for https://github.com/oras-project/oras/issues/414
- should be able to use `oras login`  command to login
- should be able to run `docker` commands and reuse the oras credential
- should be able to use `oras logout` command to logout

ORAS Artifact users:
- should be able to use `oras attach` command to create oras artifacts
- should be able to use `oras manifest fetch` command to fetch created oras artifacts
- should be able to use `oras discover` command to view the attached artifacts
- should be able to use `oras pull` command to pull oras artifacts
- should be able to user `oras copy` command to copy OCI and attached artifacts to a new repository

Also since scenario-specific E2E tests will execute based on certain local test files. We need to check required image/artifact files into the source code for all the use cases.

**Comment by qweeah** [comment]
@FeynmanZhou @yizha1 Can you engage oras users to get more valuable scenarios for E2E tests, thanks.

**Comment by FeynmanZhou** [comment]
Sure. @qweeah Currently, I can provide a sample that how users use ORAS in the secure supply chain scenario with oras `copy`, `attach`, and `discover`, see this [blog](https://deploy-preview-53--oras-project.netlify.app/blog/oras-0.14-and-future/) for details.

We can continue to investigate and append more user scenarios for E2E testing.
