### ISSUE TITLE
e2e: test oras commands before 0.15.0

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#563]
Below commands need to be covered:

# Common Commands
- oras login
- oras logout

# OCI Image Commands
- [x] oras-project/oras#565
- [x] https://github.com/oras-project/oras/issues/566
- [x] https://github.com/oras-project/oras/issues/567
- [x] https://github.com/oras-project/oras/issues/568

# ORAS Artifact Commands
- oras attach
- oras discover
- oras copy -r

**Comment by FeynmanZhou** [comment]
To clarify the OCI image and ORAS artifact commands, the OCI image commands above mean they will not be impacted after [migrating to the OCI artifact](https://github.com/oras-project/oras-go/issues/271), but the ORAS artifact commands above mean they will be impacted and should be added E2E testing after ORAS fully supports and migrates OCI reference types.

**Comment by FeynmanZhou** [comment]
The E2E testing of ORAS login/logout can be implemented after https://github.com/oras-project/oras/issues/414 since ORAS will implement a separate authentication system in v1.0.0.
