### ISSUE TITLE
e2e: test oras commands before 0.16.0

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#564]
Need to cover below ORAS commands

# Manifest
- [x] https://github.com/oras-project/oras/issues/586
- [x] https://github.com/oras-project/oras/issues/585
- [x] https://github.com/oras-project/oras/issues/565
- [x] https://github.com/oras-project/oras/issues/588

# Repository 
- [x] https://github.com/oras-project/oras/issues/714

# Blob
- [x] https://github.com/oras-project/oras/issues/587
- [x] https://github.com/oras-project/oras/issues/584
- [x] https://github.com/oras-project/oras/issues/573

# Tag
- [x] https://github.com/oras-project/oras/issues/717

# Tagging related
- oras push $registry/$repository[:TAG1[,TAG2 ...]] push multiple tags in one time
- oras copy <from> $registry/$repository[:TAG1[,TAG2...]]: copy with multi-tagging

**Comment by yuehaoliang-microsoft** [comment]
There's one more `oras manifest fetch-config` command.
