### ISSUE TITLE
e2e: add test specs for `oras blob fetch` command 

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#573]
Happy paths:
- should fetch blob content and output to a file
- should fetch blob descriptor
- should fetch prettified blob descriptor
- should fetch blob content to a file with prettified descriptor in stdout
- should fetch blob content and output to stdout
- ~~progress status should be disabled when `--output -` or `--descriptor` is provided~~
- should show preview hint in help doc

Bad paths:
- should fail if no subject reference is provided
- should fail if neither output path nor descriptor flag is provided
- should fail if `--output -` and `--descriptor` flag are both provided
- should fail directly if not logged in

**Comment by lizMSFT** [comment]
Happy paths:
- should fetch blob content and output to a file
- should fetch blob content and output to stdout
- should fetch a blob and output descriptor to stdout
- should fetch a blob and output prettified descriptor to stdout
- should fetch blob content to a file and output prettified descriptor to stdout
- progress status should be disabled when --output - or --descriptor is provided
- should show preview hint in help doc

Bad paths:
- should fail directly if not logged in
- should fail if no subject reference is provided
- should fail if the blob reference is not in the form of <name@digest>
- should fail if the specific blob does not exist
- should fail if neither output path (--output) nor descriptor flag (--descriptor) is provided
- should fail if _--output -_ and `--descriptor` flag are both provided
