### ISSUE TITLE
Make `repo` alias to `repository`

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#577]
It is too long to type `oras repository list`. It would be better to type `oras repo ls` for human beings.

**Comment by shizhMSFT** [comment]
@junczhu Could you help on this in working hours?

**Comment by junczhu** [comment]
> @junczhu Could you help on this in working hours?

Well Noted.

**Comment by junczhu** [comment]
I have already added `repo` alias.
Here is the UI/UX we have so far for this command.

<img width="438" alt="image" src="https://user-images.githubusercontent.com/74894646/190941780-fd279261-789e-4ec4-967d-8046215a7e4d.png">
