### ISSUE TITLE
Update example doc: Make flags before arguments

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#578]
Although flags work when put after arguments, it is better to make all examples consistent that flags are before arguments.

For instance, changing

```
Example - Push repository with manifest annotations
  oras push localhost:5000/hello:latest --annotation "key=val"
```

to

```
Example - Push repository with manifest annotations
  oras push --annotation "key=val" localhost:5000/hello:latest
```

**Comment by shizhMSFT** [comment]
@junczhu Could you help with this issue in the working hours? Meanwhile, it is better to update the example to take multiple annotation pairs.

**Comment by junczhu** [comment]
> @junczhu Could you help with this issue in the working hours? Meanwhile, it is better to update the example to take multiple annotation pairs.

Sure. I will help update the description for this command.
