### ISSUE TITLE
e2e: add test specs for `oras blob delete` command

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#584]
Happy paths:
- should delete a blob with interactive confirmation, with delete prompt
- should delete a blob with confirmation flag
- should delete a blob with confirmation flag and output descriptor to stdout
- progress status should be disabled when --descriptor is provided
should show preview hint in help doc

Bad paths:
- should fail if no blob reference is provided
- should fail if no confirmation flag and descriptor flag is provided
- should fail directly if not logged in

**Comment by lizMSFT** [comment]
Hi @qweeah , could you also add:

Happy paths:
- should delete a blob with confirmation flag and output prettified descriptor to stdout

Bad paths:
- should fail if the blob reference is not in the form of <name@digest>
- should fail if the specific blob does not exist
