### ISSUE TITLE
e2e: add test specs for `oras manifest push` command

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#586]
Happy paths:
- should push a manifest from stdin
- should push a manifest from a file with media type flag
- should push a manifest from a file without media type flag
- should push a manifest from a file and output the descriptor
- progress status should be disabled when --descriptor is provided
- should show preview hint in help doc

Bad paths:
- should fail if no manifest file reference is provided
- should fail directly if not logged in

**Comment by yuehaoliang-microsoft** [comment]
Happy path:
Should print prettified descriptor when `--descriptor --pretty` is applied.
Bad path:
Should fail if the file is not in valid json format, and `--media-type` is not specified.
Should fail if the file is in json format but does not contains `mediaType` field, and `--media-type` is not specified.
