### ISSUE TITLE
e2e: add test specs for `oras blob push` command

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#587]
Happy paths:
- should push a blob from stdin
- should push a blob from a file
- should push a blob from a file and output the descriptor
- progress status should be disabled when --descriptor is provided
- should show preview hint in help doc

Bad paths:
- should fail if no blob file reference is provided
- should fail directly if not logged in

**Comment by lizMSFT** [comment]
Hi @qweeah , could you also add:

Happy paths:
- should push a blob from a file and output the descriptor with specific media-type (using --media-type)
- should push a blob from a file and output the prettified descriptor

Bad paths:
- should fail if read from input (-) and read password from input (--password-stdin) are both used
- should fail if push a blob from stdin but either blob size (--size) or digest is not provided
- should fail if push a blob from stdin but provided blob size (--size) and digest are incorrect
