### ISSUE TITLE
Alias `show-tags=tags` for `oras repository`

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#590]
It will be better to have
```
oras repo tags $reg/$repo
```
alias to
```
oras repository show-tags $reg/$repo
```
for human to type.

**Comment by shizhMSFT** [comment]
@FeynmanZhou Do you have any comments?

**Comment by shizhMSFT** [comment]
@junczhu Could you help with this issue?

**Comment by junczhu** [comment]
> @junczhu Could you help with this issue?

I can help with this please assign this issue to me
