### ISSUE TITLE
ORAS delete confirmation prompt directly pressing Enter

### ISSUE THREAD

**Issue by patrickzheng200** [oras-project/oras#592]
When trying to delete using ORAS CLI, after the confirmation prompt pops up, directly pressing Enter (without typing anything) would trigger "unexpected newline" error. Expect behavior is to default as 'No'. 

related code: https://github.com/oras-project/oras/blob/02274658891c7968e8b641138a23eeb52dbd13de/cmd/oras/internal/option/confirmation.go#L46

**Comment by shizhMSFT** [comment]
@yuehaoliang-microsoft Could you take a look?

**Comment by yuehaoliang-microsoft** [comment]
> @yuehaoliang-microsoft Could you take a look?

NP.

**Comment by yuehaoliang-microsoft** [comment]
What should be expected when user input some spaces, like "ye s"?
