### ISSUE TITLE
unify styling for all command help documents

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#593]
# Usage Notation
Reference: https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/command-line-syntax-key
- Text without brackets or braces: Items you must type as shown.
- `<Text inside angle brackets>`: Placeholder for which you must supply a value.
- `[Text inside square brackets]`: Optional items.
- `{Text inside braces}`: Set of required items. You must choose one.
- Vertical bar `( \| )`: Separator for mutually exclusive items. You must choose one.
- Ellipsis `(…)`: Items that can be repeated and used multiple times.

# Styling
- Flags should be put before arguments

**Comment by shizhMSFT** [comment]
@junczhu Could you help with this issue?

**Comment by qweeah** [comment]
@junczhu I had a PR out for the fix #596, you may refer to it.

**Comment by junczhu** [comment]
I can help with this. 
Please go ahead and assign this issue to me.

@shizhMSFT

**Comment by shizhMSFT** [comment]
@junczhu It seems @qweeah has already started the work.

**Comment by junczhu** [comment]
> @junczhu It seems @qweeah has already started the work.

Well noted. Kudos goes to @qweeah

**Comment by sajayantony** [comment]
Very cool. @qweeah . 
@FeynmanZhou given that `repo` alias and `tags` alias has already been checked in, I'm leaning towards not using or considering removing `show-tags` and possibly even the long `repository` and just use these easier short commands. Just makes the UX so much nicer. 
Any point in keeping these long commands anymore before GA?
