### ISSUE TITLE
Update `oras blob fetch` documentation to better explain flag usage

### ISSUE THREAD

**Issue by wju-MSFT** [oras-project/oras#597]
For `oras blob fetch`, the current Usage states:  `oras blob fetch [flags] <name@digest>`, which indicates the flags are optional, but when we try
`oras blob fetch <name@digest>`, we will get `Error: either --output or --descriptor must be provided`.
We will need to update the documentation to better explain flag usage.

**Comment by lizMSFT** [comment]
please also help remove the last example 
```
Example - Fetch blob from the insecure registry:
  oras blob fetch --insecure localhost:5000/hello@sha256:9a201d228ebd966211f7d1131be19f152be428bd373a92071c71d8deaf83b3e5
```
Thanks
