### ISSUE TITLE
Failed to push manifest to Docker Hub

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras#601]
Hi team,

I am testing ORAS 0.15 from the main branch and trying to push manifest to Docker Hub, this error msg confused me a lot. Is it caused by the Docker Hub registry side?

```
$ oras manifest push docker.io/pengfeizhou/spark2.4:1.0.0 manifest.json
Error: PUT "https://registry-1.docker.io/v2/pengfeizhou/spark2.4/manifests/1.0.0": unexpected status code 400: 
manifest blob unknown: blob unknown to registry; manifest blob unknown: blob unknown to registry; manifest 
blob unknown: blob unknown to registry; manifest blob unknown: blob unknown to registry
```

The return msg also seems duplicated in one line.

**Comment by shizhMSFT** [comment]
You need to push the blob first then the manifest first.

Closing since it is customer error.
