### ISSUE TITLE
Improve `oras attach` help doc

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras#602]
Command:
```
oras attach -h
```
Output:
![image](https://user-images.githubusercontent.com/8113721/191662543-dfa0b887-ba19-497d-887d-793817c358e8.png)

Users can't tell that `--artifact-type` is a required field from the current help doc.
Besides, the usage format `name<:tag|@digest>` is not consistent with other commands like `manifest fetch`.
![image](https://user-images.githubusercontent.com/8113721/191663010-89d7c64b-4953-412f-8fce-3b917298abf1.png)

Some improvement can be like:
1. Add `--artifact-type` into the usage doc:
```diff
- oras attach <name:tag|name@digest> [file[:type]...] [flags]
+ oras attach <name:tag|name@digest> [file[:type]...] --artifact-type <artifactType> [flags]
```
2. Call out that `--artifact-type` is a required filed in the flag description:
```diff
- artifact type
+ artifact type (required)
```

**Comment by qweeah** [comment]
option2 is need Cobra change, go with option 1

**Comment by FeynmanZhou** [comment]
For `oras attach` help doc, I think we need to add an example for attaching a multi-file artifact as a reference. Users might not be aware that `oras attach` support attaches a multi-file artifact by default, see [this doc](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-oras-artifacts#attach-a-multi-file-artifact-as-a-reference).

**Comment by FeynmanZhou** [comment]
Another wording I think we need to polish in `oras attach` help doc, how about:

```
Example - Attach a file and add manifest annotations
  oras attach --artifact-type doc/example --annotation "key=val" localhost:5000/hello:latest hi.txt

Example - Attach a file and add manifest annotations from a JSON file
  oras attach --artifact-type doc/example --annotation-file annotation.json localhost:5000/hello:latest hi.txt
```

**Comment by qweeah** [comment]
> Another wording I think we need to polish in `oras attach` help doc, how about:
> 
> ```
> Example - Attach a file and add manifest annotations
>   oras attach --artifact-type doc/example --annotation "key=val" localhost:5000/hello:latest hi.txt
> 
> Example - Attach a file and add manifest annotations from a JSON file
>   oras attach --artifact-type doc/example --annotation-file annotation.json localhost:5000/hello:latest hi.txt
> ```

Examples added with some improvisation, please help review in #603 @FeynmanZhou
