### ISSUE TITLE
Make `oras blob/manifest push` consistent with `oras push`

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#608]
As mentioned by
- https://github.com/oras-project/oras/pull/596#discussion_r977620391
- https://github.com/oras-project/oras/pull/596#discussion_r977621132

we should remove `--media-type` and make `<file>` to `<file>[:<type>]` in `oras blob push` and `oras manifest push` so that the UX is consistent with `oras push`.

/cc @qweeah @lizMSFT @yuehaoliang-microsoft @FeynmanZhou

**Comment by shizhMSFT** [comment]
@yuehaoliang-microsoft Could you help resolving this issue?

**Comment by yuehaoliang-microsoft** [comment]
I got the point. Instead of using a flag `--media-type`, we should let user input the optional type param `<file>[:<type>]` directly following the file path.

**Comment by yuehaoliang-microsoft** [comment]
I came up with one scenario when users do `push [flags] <name>[:<tag>|@<digest>] -` where `-` means read from stdin.

If we have `--media-type` flag, users could specify the media type, otherwise, they couldn't give this param. It's a difference from `oras push`.

@shizhMSFT do you have any comment?

**Comment by yuehaoliang-microsoft** [comment]
`push [flags] <name>[:<tag>|@<digest>] -[:<type>]` is not valid.

`Error: unknown shorthand flag: ':'`

**Comment by shizhMSFT** [comment]
Thank @yuehaoliang-microsoft for pointing the `-:type` issue here.

I've tested with the `cat` command, and it show the same behaviour:
```
$ echo 123 | cat
123
$ echo 123 | cat 456
cat: 456: No such file or directory
$ echo 123 | cat -
123
$ echo 123 | cat -:
cat: invalid option -- ':'
Try 'cat --help' for more information.
```

Therefore, we have to have `--media-type` for manifest / blob push. `oras push` is a different story since it has multiple input files. The user scenarios are different and thus we don't need to make them consistent.
