### ISSUE TITLE
feature request: verbose output of tagging

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#618]
The current UX for tagging is a bit loss. For instances:

```console
% oras tag ${name}:latest 2.12.1 2.12 2
Tagged 2
Tagged 2.12.1
Tagged 2.12
```

and

```console
% oras manifest push ${name}:latest,2.12,2.12.1,2 manifest.json
Pushed ******.azurecr.io/mac/hello:latest
Tagged 2.12
Tagged 2.12.1
Tagged 2
Digest: sha256:fb12d4ce3b48eb37cded0ff91079cd7255740bdbf1c7a05014ed4481fa0d13a
```

It is better to have something like

```console
% oras tag -v ${name}:latest 2.12.1 2.12 2
Tagged ******.azurecr.io/mac/hello:latest <= 2
Tagged ******.azurecr.io/mac/hello:latest <= 2.12.1
Tagged ******.azurecr.io/mac/hello:latest <= 2.12
```

or

```console
% oras tag -v ${name}:latest 2.12.1 2.12 2
Tagged latest <= 2
Tagged latest <= 2.12.1
Tagged latest <= 2.12
```

or

```console
% oras tag -v ${name}:latest 2.12.1 2.12 2
Tagged sha256:fb12d4ce3b48eb37cded0ff91079cd7255740bdbf1c7a05014ed4481fa0d13a <= 2
Tagged sha256:fb12d4ce3b48eb37cded0ff91079cd7255740bdbf1c7a05014ed4481fa0d13a <= 2.12.1
Tagged sha256:fb12d4ce3b48eb37cded0ff91079cd7255740bdbf1c7a05014ed4481fa0d13a <= 2.12
```

**Comment by FeynmanZhou** [comment]
@shizhMSFT 
I would propose adding `Date`, `Digest`, and `Size` when users verbose output of tagging a manifest, see the following example:

```
$ oras tag -v ${registry}/${repo}:latest 2.12.1 2.12 2
2022/11/03 07:54:11 Tagged ${registry}/${repo}:2.12.1, digest: sha256:aaaaa, size: 123
2022/11/03 07:54:12 Tagged ${registry}/${repo}:2.12.2, digest: sha256:bbbb, size: 456
```

**Comment by shizhMSFT** [comment]
> @shizhMSFT I would propose adding `Date`, `Digest`, and `Size` when users verbose output of tagging a manifest, see the following example:
> 
> ```
> $ oras tag -v ${registry}/${repo}:latest 2.12.1 2.12 2
> 2022/11/03 07:54:11 Tagged ${registry}/${repo}:2.12.1, digest: sha256:aaaaa, size: 123
> 2022/11/03 07:54:12 Tagged ${registry}/${repo}:2.12.2, digest: sha256:bbbb, size: 456
> ```
> 
> cc @qweeah @yizha1 @oras-project/oras-maintainers

Adding date, digest, size will make the UX of `oras tags` inconsistent with other commands. Hence, I'm against it.

**Comment by qweeah** [comment]
Some ideas on the UX:
-  Adding digest value to `oras tag` log is undoubtable necessary, the to-be-determined point is that how should be present the digest with the tag? My personal preference is printing the digest of target image before current tagging log because reprinting digest shows duplicated information, which is unnecessary. See below:
```
$ oras tag ${name}:latest 2.12.1 2.12 2
Adding tags to [${TARGET_TYPE}] ${name} sha256:fb12d4ce3b48eb37cded0ff91079cd7255740bdbf1c7a05014ed4481fa0d13a
Tagged 2.12
Tagged 2
Tagged 2.12.1
```
For `oras push` and `oras cp`, we can add above logs right after push/copy logs.

- it's unnecessary to add date to tagging logs since user will only need this kind of information only when debugging/troubleshooting. It's more accurate to refer to debug logs with `-d` set.

-  it's unnecessary to add size into tagging logs. Maybe it's related to push or copy command but I didn't see any valid use case to get that property from tagging logs.

**Comment by FeynmanZhou** [comment]
Agree with @qweeah .

**Comment by wangxiaoxuan273** [comment]
I would like to work on this item.

**Comment by qweeah** [comment]
Suggested UX:

```shell
# oras tag
oras tag ${name}:latest 2.12.1 2.12 2
Tagged 2.12
Tagged 2
Tagged 2.12.1
Done tagging [${TARGET_TYPE}] ${name}@sha256:fb12d4ce3b48eb37cded0ff91079cd7255740bdbf1c7a05014ed4481fa0d13a

# oras push
oras push ${name}:latest,2.12.1,2.12,2
Preparing foobar/bar
Uploading fcde2b2edba5 foobar/bar
Uploaded  fcde2b2edba5 foobar/bar
Uploading c2844d9e1aa3 application/vnd.oci.artifact.manifest.v1+json
Uploaded  c2844d9e1aa3 application/vnd.oci.artifact.manifest.v1+json
Pushed [registry] ${name}:latest
Digest: sha256:c2844d9e1aa3d42a683ed8b823a12de2510d38ef4d700c2a5e9769426e39b63d
Tagged 2.12
Tagged 2
Tagged 2.12.1
Done tagging [${TARGET_TYPE}] ${name}@sha256:c2844d9e1aa3d42a683ed8b823a12de2510d38ef4d700c2a5e9769426e39b63d

# oras copy
oras cp ${name1}:latest ${name2}:latest,2.12.1,2.12,2
Copying ae2d56717c93 signature
Copying 44136fa355b3 test.signature.file
Copied  ae2d56717c93 signature
Copying 44136fa355b3 test.sbom.file
Copying f5d51c0823fc sbom
Copied  44136fa355b3 test.sbom.file
Copied  44136fa355b3 test.signature.file
Copying 2c26b46b68ff foo1
Exists  44136fa355b3 application/vnd.unknown.config.v1+json
Copying fcde2b2edba5 bar
Copied  f5d51c0823fc sbom
Copied  2c26b46b68ff foo1
Copied  fcde2b2edba5 bar
Copying fd6ed2f36b54 application/vnd.oci.image.manifest.v1+json
Skipped 2c26b46b68ff foo2
Copied  fd6ed2f36b54 application/vnd.oci.image.manifest.v1+json
Copied [registry] {name1}@sha256:fd6ed2f36b5465244d5dc86cb4e7df0ab8a9d24adc57825099f522fe009a22bb
Tagged 2.12
Tagged 2
Tagged 2.12.1
Done tagging [${TARGET_TYPE}] ${name2}@sha256:fd6ed2f36b5465244d5dc86cb4e7df0ab8a9d24adc57825099f522fe009a22bb
```

**Comment by shizhMSFT** [comment]
It is unnecessary to print duplicated digest for `oras push` and `oras copy`.

For `oras tag`, it would be better to have the digest before the tags.
```console
% oras tag ${name}:latest 2.12.1 2.12 2
Tagging [${TARGET_TYPE}] ${name}@sha256:fb12d4ce3b48eb37cded0ff91079cd7255740bdbf1c7a05014ed4481fa0d13a
Tagged 2.12
Tagged 2
Tagged 2.12.1
```

**Comment by qweeah** [comment]
> It is unnecessary to print duplicated digest for `oras push` and `oras copy`.
> 
> For `oras tag`, it would be better to have the digest before the tags.
> 
> ```
> % oras tag ${name}:latest 2.12.1 2.12 2
> Tagging [${TARGET_TYPE}] ${name}@sha256:fb12d4ce3b48eb37cded0ff91079cd7255740bdbf1c7a05014ed4481fa0d13a
> Tagged 2.12
> Tagged 2
> Tagged 2.12.1
> ```
updated inline

**Comment by FeynmanZhou** [comment]
@qweeah It looks fine.
