### ISSUE TITLE
Error is not well handled in `oras manifest push`

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#627]
The `err` from `manifests.Resolve(ctx, ref)` is not well handled and causes `oras` print out incorrect output.

https://github.com/oras-project/oras/blob/5e2750d9bcdc85f17bdeeeeb4458ad8666f37d80/cmd/oras/manifest/push.go#L131-L149

Sample output:
```console
$ oras manifest push ${name} manifest.json --debug
DEBU[0000]  Request URL: "https://host.docker.internal:5000/v2/hello/manifests/sha256:361358b5c6b151255f3ade1d0dc0bfc64d0ec1455c55c9c86cbfc027b4981308"
DEBU[0000]  Request method: "HEAD"
DEBU[0000]  Request headers:
DEBU[0000]    "Accept": "application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, application/vnd.cncf.oras.artifact.manifest.v1+json"
DEBU[0000]    "User-Agent": "oras/0.15.0"
ERRO[0000] Error in getting response: %!w(tls.RecordHeaderError={first record does not look like a TLS handshake [72 84 84 80 47] 0xc000286000})
Pushed host.docker.internal:5000/hello
Digest: sha256:361358b5c6b151255f3ade1d0dc0bfc64d0ec1455c55c9c86cbfc027b4981308
```

**Comment by shizhMSFT** [comment]
@yuehaoliang-microsoft Could you take a look and fix it?

**Comment by yuehaoliang-microsoft** [comment]
Surely!

**Comment by yuehaoliang-microsoft** [comment]
Proposed a PR to address this issue. In my scenario to reproduce the error, before the fix:
<img width="855" alt="image" src="https://user-images.githubusercontent.com/109199020/193183730-a9c961c1-517b-4622-9454-39d0c3a35b89.png">

After the fix:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/109199020/193183823-9c4cd189-a5eb-4e04-a5da-b2fc4031cb08.png">

The change doesn't break current logic:
<img width="734" alt="image" src="https://user-images.githubusercontent.com/109199020/193184533-1683eae3-1bb4-49e9-a86e-bdc5519da4b5.png">
