### ISSUE TITLE
Show annotations in `oras discover`

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#631]
Showing the annotations as a part of the OCI specification - 

<img width="618" alt="image" src="https://user-images.githubusercontent.com/1821104/193705158-6ea9ee36-e902-4d11-be56-595e6b5130df.png">

@shizhMSFT @FeynmanZhou - thoughts on how you to show annotations in the discover command -

_Originally posted by @sajayantony in https://github.com/oras-project/oras/issues/630#issuecomment-1266211272_

**Comment by shizhMSFT** [comment]
@sajayantony Annotations in `oras discover` looks interesting. I'd like to have `key: value` instead of `key=value` printed.

We also need to find out the UX for other layouts besides `tree`.

**Comment by FeynmanZhou** [comment]
Replied on https://github.com/oras-project/oras/issues/630#issuecomment-1267307003.

Let me investigate this CLI UX.

**Comment by sajayantony** [comment]
Keeping the string same enables consistent parsing across manifest and outputs is my take.

**Comment by qweeah** [comment]
> @sajayantony Annotations in `oras discover` looks interesting. I'd like to have `key: value` instead of `key=value` printed.
> 
> We also need to find out the UX for other layouts besides `tree`.

@shizhMSFT  Seems `key: value` is not an option since datetime format might conatin `:`

**Comment by shizhMSFT** [comment]
@qweeah The value can be anything so that we are more focusing on the UX other than the content value.
For instance, `{"foo":"bar=fun"}` will result in `foo=bar=fun`.
