### ISSUE TITLE
Cherry pick bug fixes to v0.15.1

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#635]
Bug fixes done in `v0.16.0` with orders:
1. #626
2. #629
3. #632
4. #637

**Comment by shizhMSFT** [comment]
A PR should be created against [release-0.15](https://github.com/oras-project/oras/tree/release-0.15) and merged with rebase merge.

**Comment by qweeah** [comment]
> A PR should be created against [release-0.15](https://github.com/oras-project/oras/tree/release-0.15) and merged with rebase merge.

@shizhMSFT To make releasing process easier, should we add 4 PRs for each cherry-picking?

Also #640 need to be merged in advance.

**Comment by shizhMSFT** [comment]
> To make releasing process easier, should we add 4 PRs for each cherry-picking?

We can have one PR in a shot.

> Also #640 need to be merged in advance.

Yes, fix to #640 should be merged before above cherry-pick PR.

**Comment by shizhMSFT** [comment]
Closed by #643
