### ISSUE TITLE
Use shorter commands by default

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#667]
Human beings are lazy to type. It is better to default to shorter command names
- `repository` --> `repo`
- `list` --> `ls`
- `show-tags` --> `tag`

Basically, the alias and command names should be swapped.

**Comment by FeynmanZhou** [comment]
> Human beings are lazy to type. It is better to default to shorter command names
> 
> * `repository` --> `repo`
> * `list` --> `ls`
> * `show-tags` --> `tag`
> 
> Basically, the alias and command names should be swapped.

I think `show-tags` should be `tags`.

**Comment by shizhMSFT** [comment]
> I think `show-tags` should be `tags`.

Yes, it's `tags`. My typo.

**Comment by shizhMSFT** [comment]
Since `list` becomes unix style `ls`, it is better to rename `delete` to `rm`
- `oras manifest delete` --> `oras manifest rm`
- `oras blob delete` --> `oras manifest rm`

Since we rename `delete` to `rm`, it is better to rename `--yes` to `--force` to be consistent with the unix command `rm`.

Additionally, since `oras manifest fetch` has an alias `get`, we should also have an alias `get-config` for `fetch-config`.

**Comment by shizhMSFT** [comment]
According to [Remove -vs- Delete](https://apps.labor.ny.gov/ux/doc/v1/design-remove-vs-delete.html),
> Remove and Delete are defined quite similarly, but the main difference between them is that delete means erase (i.e. rendered nonexistent or nonrecoverable), while remove denotes take away and set aside (but kept in existence).

manifest / blob delete are indeed delete. Hence, we should keep the `delete` for the correct wording and uses rm just for alias.
