### ISSUE TITLE
Uppercase characters in reference cannot resolve

### ISSUE THREAD

**Issue by joshspicer** [oras-project/oras#679]
### What happened in your environment?

I was attempting to use oras to pull `ghcr.io/NicoVIII/devcontainer-features`, which has uppercase characters from this [GitHub user's username](https://github.com/NicoVIII).  I get "invalid repository" unless I convert all the characters to lowercase (the it works as expected).

### What did you expect to happen?

The casing of the reference does not matter, or at least matches the original casing during publishing. 

### How can we reproduce it?

```
joshspicer@gh-m1 cli % oras pull ghcr.io/NicoVIII/devcontainer-features:latest
Error: invalid reference: invalid repository
```

Downcasing works as expected
```
joshspicer@gh-m1 cli % oras pull ghcr.io/nicoviii/devcontainer-features:latest
Downloading c12f8bff877e devcontainer-collection.json
Downloaded  c12f8bff877e devcontainer-collection.json
Pulled ghcr.io/nicoviii/devcontainer-features:latest
Digest: sha256:2034958bc400cd8506203d4414f30ccba99185291909d3b5982d657829af9625
```

### What is the version of your ORAS CLI?

Version:    0.15.0+Homebrew
Go version: go1.19.1

and

Version:        0.13.0
Go version:     go1.18.1

### What is your OS environment?

linux (github action) and MacOS

### Are you willing to submit PRs to fix it?

- [X] Yes, I am willing to fix it.

**Comment by sajayantony** [comment]
This is again one of these “we need a spec for what a reference is”.

**Comment by qweeah** [comment]
Seems both [docker](https://docs.docker.com/registry/spec/api/#:~:text=More%20strictly%2C%20it%20must%20match%20the%20regular%20expression%20%5Ba%2Dz0%2D9%5D%2B(%3F%3A%5B._%2D%5D%5Ba%2Dz0%2D9%5D%2B)*.) and [OCI spec](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#pulling-manifests:~:text=%3Cname%3E%20MUST,a%2Dz0%2D9%5D%2B\)*\)*) excludes capitalized characters from the repo name.

**Comment by FeynmanZhou** [comment]
Do you think ORAS should prompt the users that all the characters should be lowercase in the output?

**Comment by shizhMSFT** [comment]
Closing as upper-case repository names are not allowed by spec as mentioned by @qweeah.
