### ISSUE TITLE
Support customized DNS resolving from a `host` to a specific `address`

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#688]
### What would you like to be added?

I would like to have a new flag added to all remote registry related commands:
```
--resolve <host:port:address>
```

So any outgoing request towards `host`:`port` should be resolve to `address`:`port`.

### Why is this needed for ORAS?

So ORAS can be 1) used to debug registry services running locally; 2) hardcode DNS resolving to reduce DNS bouncing in geo-replicated registry services.

### Are you willing to submit PRs to contribute to this feature?

- [X] Yes, I am willing to implement it.

**Comment by FeynmanZhou** [comment]
Should we make this flag `--resolve` a global option? I assume it can resolve only one address per request.

**Comment by qweeah** [comment]
> Should we make this flag `--resolve` a global option? I assume it can resolve only one address per request.

No we don't. ORAS has a different option management mechanism. This flag will be added to the [remote option](https://github.com/oras-project/oras/blob/main/cmd/oras/internal/option/remote.go) package and any command relevant to remote registry operation will have this flag.
