### ISSUE TITLE
regression: wrt `zot` since v0.16.0?

### ISSUE THREAD

**Issue by rchincha** [oras-project/oras#719]
### What happened in your environment?

In context of https://github.com/oras-project/oras/pull/709, trying to figure out what broke.

Looks like a regression at 2329c6e.

First skopeo copy busybox:latest image into zot, then

With oras v0.16.0
```
$ORAS_PATH attach --plain-http $ORAS_REGISTRY_HOST/busybox:latest --artifact-type 'signature/example' ./signature.json:application/json
Exists    8a865c9da82b signature.json
Attached to localhost:8080/busybox@sha256:67bb7f36fcda428c491d7aa9a24ec0f1a8f6cdf472ef2c827ec7b6c2e36207f2
Digest: sha256:4e23167b9a8d41e8e95f51536b7333371fbf7b6bd993a9acc422a729150a9e90
```

With oras 2329c6e, see this error.
```
$ORAS_PATH attach --plain-http $ORAS_REGISTRY_HOST/busybox:latest --artifact-type 'signature/example' ./signature.json:application/json
Exists    8a865c9da82b signature.json
Error: sha256:efa88158fbb53aab65044fd2ec001fb855344a881461a1bf6171068eef4cee64: application/vnd.oci.artifact.manifest.v1+json: not found
```

### How can we reproduce it?

Pls see above.

### What is the version of your ORAS CLI?

2329c6e

### What is your OS environment?

ubuntu 22.04

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by qweeah** [comment]
@rchincha Thanks a lot for investigating this issue. After taking a close look, this regression was introduced from oras-go library in https://github.com/oras-project/oras-go/pull/359. 

The manifest was packed into the file store, oras-go created a cache but the packed manifest was not cache. Should check whether the cache contains the descriptor in [here](https://github.com/oras-project/oras-go/blob/main/copy.go#L253).

cc oras-go maintainer @wwwsylvia @shizhMSFT for tracking this issue in oras-go.
