### ISSUE TITLE
e2e: update spec-related constants to string literal

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#721]
So when the spec is updated, the breaking change can be reflected explicitly in failed E2E tests. Bump PR should also include E2E fix.

**Comment by rafiya2003** [comment]
I would like to work on this, frankly I don't know much but I will learn and do. I am a newbie(first year UG student). I want to learn and grow. please give me the opportunity to learn and experience

**Comment by qweeah** [comment]
@rafiya2003 Hi Rafiya, welcome to oras & thanks for your interest. This issue is critical for the upcoming release 1.1.0, so considering the urgency of the time it's not suitable for new contributors.

If you are interested, do you like to work on https://github.com/oras-project/oras/issues/742? It's also a good first issue and not included in 1.1.0 release.

**Comment by rafiya2003** [comment]
yes I would like to work on  #742

**Comment by rafiya2003** [comment]
I can see someone assigned there if you could suggest me any other issue
