### ISSUE TITLE
return success when force deleting a non-existent blob/manifest

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#722]
When force deleting via `oras manifest/blob delete`, if the target reference is not found in the remote registry, then user will see an error message like below:

```
$ oras blob delete localhost:5000/command/blob/delete/1671102430@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa --force
Error: localhost:5000/command/blob/delete/1671102430@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: the specified blob does not exist
```

The returned value should indicate success if successfully resolving the reference and registry returns not found.

@FeynmanZhou

**Comment by shizhMSFT** [comment]
Here are the exit codes of the `rm` command for references.
```console
$ rm not-exist
rm: cannot remove 'not-exist': No such file or directory
$ echo $?
1
$ rm -f not-exist
$ echo $?
0
$ rm /dev/null
rm: cannot remove '/dev/null': Permission denied
$ echo $?
1
$ rm -f /dev/null
rm: cannot remove '/dev/null': Permission denied
$ echo $?
1
```

**Comment by FeynmanZhou** [comment]
Agree to change the return to success in the case above. How can we describe the output message exactly?

**Comment by qweeah** [comment]
Taking `manifest delete` as an example, suppose $IMAGE is not existed:
- oras manifest delete $IMAGE -f
  - return success since `-f` implies forced action
  - output `Missing $IMAGE` to stdout, this UX is consistent with deleting an existent manifest

- oras manifest delete $IMAGE
  - fail and output `Error: $IMAGE: the specified manifest does not exist` to stderr

- oras manifest delete $IMAGE -f --descriptor
  - fail since the to-be-deleted descriptor doesn't exist
  - output `Error: $IMAGE: the specified manifest does not exist` to stderr
