### ISSUE TITLE
Make `--identity-token` an alias of `--password`

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#742]
### What is the version of your ORAS CLI

v0.16.0

### What would you like to be added?

Make `--identity-token` an alias of `--password`

### Why is this needed for ORAS?

`oras` supports using identity token as the credential without a username.

The UX of `oras login $REGISTRY --password $TOKEN` does not seem good enough. It will be better if it is
```sh
oras login $REGISTRY --identity-token $TOKEN
```

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by qweeah** [comment]
What if user mistakenly use `oras login $REGISTRY --username $USERNAME --identity-token $TOKEN`

**Comment by shizhMSFT** [comment]
> What if a user mistakenly use `oras login $REGISTRY --username $USERNAME --identity-token $TOKEN`

I think we should return error for this case.

**Comment by rafiya2003** [comment]
I would like to work on this

**Comment by qweeah** [comment]
@rafiya2003 If you have any questions, feel free [join oras slack](https://oras.land/docs/contributing/#contact-us) and ping me

**Comment by qweeah** [comment]
Not all registry support token refreshing from identity token to registry token. E.g. ghcr returns 405 for token refreshing.

@shizhMSFT We should also add a flag `--registry-token` allow user to use [registry token](https://docs.docker.com/registry/spec/auth/token/) in oras commands.

**Comment by shizhMSFT** [comment]
> Not all registry support token refreshing from identity token to registry token. E.g. ghcr returns 405 for token refreshing.
> 
> @shizhMSFT We should also add a flag `--registry-token` allow user to use [registry token](https://docs.docker.com/registry/spec/auth/token/) in oras commands.

That can be another issue and I noticed that you have created one #968

**Comment by sbdtu5498** [comment]
I have completed the implementation. Will try to push it soon,

**Comment by qweeah** [comment]
@sbdtu5498 Any update on this?

**Comment by sbdtu5498** [comment]
Oh sorry for the delays. I was busy with some other stuff and left the task hanging. Will push it before Monday.

**Comment by qweeah** [comment]
@shizhMSFT  Do we also need `--registry-token-stdin`?

**Comment by qweeah** [comment]
@sbdtu5498 So we need to add another flag to enable read identity token from stdin like:
```bash
echo $TOKEN | oras login $REGISTRY --identity-token-stdin 
```

**Comment by sbdtu5498** [comment]
Sure, will do it ASAP. Sorry for the delayed response.
