### ISSUE TITLE
`@digest` option in `oras manifest push` command seems unnecessary

### ISSUE THREAD

**Issue by northtyphoon** [oras-project/oras#754]
### What happened in your environment?

Usage:
  oras manifest push [flags] <name>[:<tag>[,<tag>][...]|@<digest>] <file>

There seems no use case to pass `@digest`. I'd expect digest is auto-generated based on `<file>`. If users omit tag or digest, the command pushes a manifest without tag.

### How can we reproduce it?

oras manifest push --help

### What is the version of your ORAS CLI?

0.16.0

### What is your OS environment?

WSL

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by qweeah** [comment]
@yuehaoliang-microsoft @shizhMSFT Do we have a specific user scenario for providing digest from reference argument?

**Comment by shizhMSFT** [comment]
The digest is optional. Please refer to the following example:
```
Example - Push a manifest to repository 'localhost:5000/hello' and output the prettified descriptor:
  oras manifest push --descriptor --pretty localhost:5000/hello manifest.json
```

If the digest is provided, the pushed content is verified against the provided digest.

**Comment by shizhMSFT** [comment]
The digest can be pinned if the integrity of the manifest is not guaranteed. For example, `manifest.json` is corrupted while you have its digest in the `checksum.txt`.

Well, the files on the disk seldom corrupt but it is possible if it comes from a network location. For example,
```sh
curl "https://contoso.com/example/manifest.json" | oras manifest push localhost:5000/hello@sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
```
`oras` will return error if the `manifest.json` fetched remotely does not match the given digest.

**Comment by shizhMSFT** [comment]
Closing this issue as the necessity is explained.
