### ISSUE TITLE
support OCI image layout target in `oras manifest delete`

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#762]
User should be able to use `oras manifest delete` to remove a manifest in their OCI layout folder with properly garbage collection.

**Comment by sidharthviz** [comment]
Hi @qweeah I would like to work on this, Could you assign me for this issue ?

**Comment by qweeah** [comment]
Hey @sidharthviz I just found that manifest deletion is not implemented on SDK side. I just created a new issue in oras-go to track: https://github.com/oras-project/oras-go/issues/454, which means this issue might take more effort than expected and may not be a good point to start contributing to oras. 

Will unassign you and remove the good-first-issue tag, sorry and feel free to choose another one from https://github.com/oras-project/oras/contribute.

**Comment by sidharthviz** [comment]
> Hey @sidharthviz I just found that manifest deletion is not implemented on SDK side. I just created a new issue in oras-go to track: [oras-project/oras-go#454](https://github.com/oras-project/oras-go/issues/454), which means this issue might take more effort than expected and may not be a good start point to contribute to oras.
> 
> Will unassign you and remove the good-first-issue tag, sorry and feel free to choose another one from https://github.com/oras-project/oras/contribute.

It's alright Billy :)

**Comment by qweeah** [comment]
both this issue and #761 are depending on merging of https://github.com/oras-project/oras-go/pull/470, moving to 1.2.0 mile stone.

**Comment by FeynmanZhou** [comment]
As a project maintainer for CNCF Notary Project, I would like to have this feature in ORAS v1.2.0 since it enables Notation users to delete a signature from an image in OCI image layout. See an example usage in registry: https://notaryproject.dev/docs/user-guides/how-to/manage-signatures/#delete-a-signature-on-an-artifact

**Comment by shizhMSFT** [comment]
Note that `oras manifest delete` just delete the manifest. To delete an image cleanly, we need the GC feature (https://github.com/oras-project/oras-go/issues/472).
