### ISSUE TITLE
Request for retry support

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#769]
### What is the version of your ORAS CLI

v0.16.0

### What would you like to be added?

Add retry logic introduced in oras-go v2

### Why is this needed for ORAS?

Retry increases the availability of oras.

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by souleb** [comment]
can you assign this to me?

**Comment by shizhMSFT** [comment]
Thank @souleb for contributing! ❤️
