### ISSUE TITLE
bug: The flag `--distribution-spec` is not recognized by `oras attach`

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras#771]
### What happened in your environment?

The flag `--distribution-spec` is not recognized by `oras attach` while there are examples about the flag `--distribution-spec` in the help text.

Error message: 
```shell
Error: unknown flag: --distribution-spec
```
![image](https://user-images.githubusercontent.com/8113721/215431356-c2b88bf2-eade-4643-b9e9-f56962184a7e.png)
![image](https://user-images.githubusercontent.com/8113721/215431064-85e7e4a7-305b-4187-8784-bbb720c50c01.png)

### What did you expect to happen?

The flag should work and should show up in the flag list.

### How can we reproduce it?

```shell
oras attach --artifact-type $artifactType $dstRef $fileToAttach --distribution-spec v1.1-referrers-tag
```

### What is the version of your ORAS CLI?

Version: 0.16.0+unreleased
Go version: go1.19.3
Git commit: https://github.com/oras-project/oras/commit/6e876c1e785e81576f5f9c28fac66a60986776e3

### What is your OS environment?

Windows

### Are you willing to submit PRs to fix it?

- [X] Yes, I am willing to fix it.

**Comment by shizhMSFT** [comment]
Fixed by #772
