### ISSUE TITLE
Disable auto conversion of manifest types

### ISSUE THREAD

**Issue by sajayantony** [oras-project/oras#782]
### What is the version of your ORAS CLI

0.16.0

### What would you like to be added?

Currently ORAS CLI causes artifact manifest with auto fallback to image manifest. As per recent discussions in OCI https://hackmd.io/moB5-fsQTbGmDpnrsY-4yg we feel that auto conversion of manifests leads to different digests that clients may produce. 

### Why is this needed for ORAS?

If a registry starts supporting the artifact manifest, then ORAS CLI would start pushing the new manifest type which might potentially break downstream consumers who might know now about the this manifest type. This makes the pipeline fragile. 

One option would be to make the default use --v1.1 and fail on push. And the clients can then specify --v1.0 which would only use the image manifest and continue using image manifest throughout its time until the producer chooses to push the new type. 

Currrently this behavior switch depends on the target registry and moving this control to the client is the main ask here. 

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by shizhMSFT** [comment]
The behavior of `oras v1.0.0-rc.1` on the flag `--image-spec` is
- Auto fallback from artifact manifest if the flag is not set
- Push artifact manifest if the flag is set to `v1.1-artifact`
- Push image manifest if the flag is set to `v1.1-image`

Based on @sajayantony's ask, my proposal is that the flag `--image-spec` will be changed to
- Auto fallback from artifact manifest if the flag is set to `v1.1-auto`
- Push artifact manifest if the flag is set to `v1.1-artifact`, which is marked as the default value
- Push image manifest if the flag is set to `v1.1-image`

@FeynmanZhou @qweeah Any comments?

**Comment by sajayantony** [comment]
With OCI coalescing around Image manifest, should we default to Image?

**Comment by FeynmanZhou** [comment]
Agree with changing the default manifest type. But the user experience is supposed to be changed as follows:

- Auto fallback is no longer needed as no valid scenario is confirmed if we change the default pushing behavior to OCI image manifest
- Push artifact manifest if the flag `--image-spec` is set to v1.1-artifact, 
- Push image manifest if the flag `--image-spec` is set to v1.1-image, which is marked as the default value and apply to `oras push` and `oras attach`

**Comment by shizhMSFT** [comment]
As discussed in the community call, the flag `--image-spec` will be the default to `v1.1-image` and the auto fallback will be removed. No new flags or flag values will be added.
