### ISSUE TITLE
improve error message when TLS verification fails

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#787]
### What happened in your environment?

I am using oras 1.0 rc on a self-hosted registry service with a self-signed certificate. When I pull an artifact via `oras pull`:
 - If `--insecure` flag is set, everything works fine. The artifact is pulled successfully;
 - If `--insecure` flag is not set, the error message doesn't imply the TLS verification fails because of the self-signed certificate is not trusted:
    ```
    oras pull my.reg/hello-artifact:v1
    Error: failed to resolve v1: Get "https://my.reg/v2/hello-artifact/manifests/v1": x509: certificate relies on legacy Common Name field, 
    use SANs instead
    ```

### What did you expect to happen?

Output message should be informative, e.g. "SSL certificate problem: self signed certificate"

### How can we reproduce it?

Untrust the certificate of a registry and use `oras pull` to pull an artifact without `--insecure` flag.

### What is the version of your ORAS CLI?

Version:        1.0.0-rc.1
Go version:     go1.19.5
Git commit:     a98931bc68a0e7a5de6c51df8e5aa09aadad3057
Git tree state: clean

### What is your OS environment?

Ubuntu 20.04

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by TerryHowe** [comment]
I agree this is not great, but this error comes from outside the project and I don't know if it is a good idea to map errors for a project dependency.

**Comment by shizhMSFT** [comment]
The error message
> x509: certificate relies on legacy Common Name field, use SANs instead

does not mean `SSL certificate problem: self signed certificate`. Even if the self-signed certificate is trusted, it will still show this error where the error message shows literally what it means.

Starting from golang 1.15 (see [release note](https://go.dev/doc/go1.15): X.509 CommonName deprecation), the domain name is no longer verified against the common name (CN) of the subject of the leaf cert. Instead, the domain name is verified against the subject alternative names (SANs), which is an extension attribute of the leaf cert.

Therefore, the error message is accurate but requires additional knowledge. But... usually, users just search for solutions when they see crypto errors.
