### ISSUE TITLE
Make ORAS discover consistent with 0.16

### ISSUE THREAD

**Issue by sajayantony** [oras-project/oras#789]
### What is the version of your ORAS CLI

 1.0.0-rc.1

### What would you like to be added?

Oras discover used to show the fully qualified reference and it is missing that in the current RC release 

```bash
❯ oras discover -o tree sajay.azurecr.io/oci-ref-delete:v1
v1
└── example/test
    └── sha256:4471e38700eab45826c8ed6231736af30c2ad5561eabb9966fee6b79c0e35781
```

Prior to this it would show the this with fully qualified reference which IMHO was less confusing. 

```bash
❯ ./oras discover -o tree sajay.azurecr.io/oci-ref-delete:v1
sajay.azurecr.io/oci-ref-delete:v1
└── example/test
    └── sha256:4471e38700eab45826c8ed6231736af30c2ad5561eabb9966fee6b79c0e35781
```

### Why is this needed for ORAS?

Fully qualified references requires less context and is more usable in general. 
However for OCI layout this might be a challenge and it might something we can special case for OCI layout. 

We could even consider displaying this a fully qualified reference with the digest since it makes it clear to what digest the tag resolved to. 

Currently this looks odd when we use a digest 

```bash
❯ oras discover -o tree sajay.azurecr.io/oci-ref-delete@sha256:414e0518bb9228d35e4cd5165567fb91d26c6a214e9c95899e1e056fcd349011
sha256:414e0518bb9228d35e4cd5165567fb91d26c6a214e9c95899e1e056fcd349011
└── example/test
    └── sha256:4471e38700eab45826c8ed6231736af30c2ad5561eabb9966fee6b79c0e35781
```

**Comment by shizhMSFT** [comment]
The command `oras discover` does not show the resolved digest when given the tag.

How about showing the digest with the FQDN repository name? For example,
```console
$ oras discover -o tree sajay.azurecr.io/oci-ref-delete:v1
sajay.azurecr.io/oci-ref-delete@sha256:414e0518bb9228d35e4cd5165567fb91d26c6a214e9c95899e1e056fcd349011
└── example/test
    └── sha256:4471e38700eab45826c8ed6231736af30c2ad5561eabb9966fee6b79c0e35781
```

**Comment by shizhMSFT** [comment]
OCI layout can show `<path>@<digest>`.

**Comment by sajayantony** [comment]
+1 on digest.

**Comment by FeynmanZhou** [comment]
It looks like this output was mistakenly changed in v1.0.0 RC.1. Let's change it back to return a full digest for the root artifact.

**Comment by qweeah** [comment]
> OCI layout can show `<path>@<digest>`.

I think we can also apply it to remote, since the subject descriptor is always resolved before being discovered.
