### ISSUE TITLE
Redirect both the hostname and port for TCP connections

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#790]
### What is the version of your ORAS CLI

v1.0.0-rc.1

### What would you like to be added?

The `oras` allows the flag `--resolve host:port:address` to dial to an another host, which works like `/etc/hosts`. However, it does not redirect the ports.

Therefore, it would be nice to have
```
--resolve host:port:address[:port]
```

### Why is this needed for ORAS?

It is useful to do local development by using a local registry as a remote registry.

For example:
```sh
oras push --resolve registry.contoso.com:443:localhost:5000 registry.contoso.com/hello hello.txt
```

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by qweeah** [comment]
I think the example is wrong? In rc1, the push command looks like below
> oras push --resolve registry.contoso.com:5000:localhost registry.contoso.com:5000/hello hello.txt

Since the default port of non-plain-http is 443, the dial port should be 443 and oras is mapping it to 5000. The command looks like below
> oras push --resolve registry.contoso.com:443:localhost:5000 registry.contoso.com/hello hello.txt

**Comment by shizhMSFT** [comment]
The example in the description is exactly the same as you've provided.
