### ISSUE TITLE
Improve error message on `oras copy` with non-existent tags

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#791]
### What happened in your environment?

Error message is not clear when the tag `3.9` does not exist in the `alpine` folder.

```console
$ oras cp --from-oci-layout alpine:3.9 localhost:5000/alpine
Error: not found
```

The `not found` is correct but it is hard to let the users know whether the folder does not exist or the tag does not exist.

I do notice the error message was improved in [oras-go](https://github.com/oras-project/oras-go/blob/v2.0.0/copy.go#L138) but the following code is not improved:

https://github.com/oras-project/oras/blob/586fa838f00ea406696a29a571a90fab3f5a1cca/cmd/oras/cp.go#L139-L149

### What did you expect to happen?

Print something like
```
Error: failed to resolve alpine:3.9: not found
```

### How can we reproduce it?

```sh
oras cp docker.io/library/alpine:3.9 --to-oci-layout alpine
oras cp --from-oci-layout alpine:3.9 localhost:5000/alpine
```

### What is the version of your ORAS CLI?

Version:        1.0.0-rc.1
Go version:     go1.19.5
Git commit:     a98931bc68a0e7a5de6c51df8e5aa09aadad3057
Git tree state: clean

### What is your OS environment?

Ubuntu 20.04

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by khanjasir90** [comment]
@shizhMSFT can i work on this!

**Comment by shizhMSFT** [comment]
@khanjasir90 Thanks for contributing! Please note that the example output in the issue description is just an example. You should make the error message consistent with what `oras-go` returns for `oras.Copy()`.

**Comment by khanjasir90** [comment]
@shizhMSFT  got it!

**Comment by khanjasir90** [comment]
@shizhMSFT the Resolve function [here](https://github.com/oras-project/oras/blob/8bda262f901e8ef8404cf23d59c5f47f4280fdf3/cmd/oras/cp.go#L136) which is invoked by the src object throws err `Error: not found` which belongs to the oras-go package. So how should I go about it could you please help me with that.

**Comment by shizhMSFT** [comment]
> @shizhMSFT the Resolve function [here](https://github.com/oras-project/oras/blob/8bda262f901e8ef8404cf23d59c5f47f4280fdf3/cmd/oras/cp.go#L136) which is invoked by the src object throws err `Error: not found` which belongs to the oras-go package. So how should I go about it could you please help me with that.

You may wrap the error returned by the `oras-go`.

**Comment by qweeah** [comment]
@khanjasir90 We are planning to release 1.0.0-RC.2 and this is a critical UX fix, @khanjasir90 do you have any update on this?

**Comment by khanjasir90** [comment]
@qweeah sorry but, due to limited understanding of the codebase and me joining the the oras community recently I wasn't able to fix it. but I m still trying it.

**Comment by shizhMSFT** [comment]
@khanjasir90 It will be as simple as the error wrapping in `oras-go`: https://github.com/oras-project/oras-go/blob/216f081e33ba53a348fa167dc27bc3ad9e591d36/copy.go#L138

**Comment by khanjasir90** [comment]
@shizhMSFT could u give me time till today night!

**Comment by khanjasir90** [comment]
@shizhMSFT can u give me time till today evening. I'll raise a PR.

**Comment by shizhMSFT** [comment]
@khanjasir90 Please take time. We will include this change in [v1.0.0-rc.2](https://github.com/oras-project/oras/milestone/14).

**Comment by khanjasir90** [comment]
Thanks!
