### ISSUE TITLE
OCI not able to push to ECR

### ISSUE THREAD

**Issue by arundeepkurni** [oras-project/oras#796]
### What happened in your environment?

Oras push cli command is successful but ECR repository OCI bundle showing zero size.

Command Triggered:

`oras push -u AWS -p $(aws ecr get-login-password) \
     $REGISTRY:$OPA_BUNDLE \
     --config config.json:application/vnd.acme.rocket.config.v1+json \
     artifact.txt:text/plain \
     ./docs/:application/vnd.acme.rocket.docs.layer.v1+tar`

CLI returns the SHA value :
`Uploading a948904f2f0f artifact.txt
Uploading 9ab7719dedaf docs
Uploaded  9ab7719dedaf docs
Uploaded  a948904f2f0f artifact.txt
Pushed <acount_number>.dkr.ecr.us-east-1.amazonaws.com/artifact-yaml-test-2:opa-temporal-0
Digest: sha256:e871e7c1ed3bd362807861409f77b2b3a1ef94a8ab0892b9edf7c7f39c991538`

But, in AWS ECR repository, the oci bundle size coming as "0.00"

### What did you expect to happen?

expected, two OCI layers shown in ECR repository details, but size coming as Zero

### How can we reproduce it?

`oras push -u AWS -p $(aws ecr get-login-password) \
     $REGISTRY:$OPA_BUNDLE \
     --config config.json:application/vnd.acme.rocket.config.v1+json \
     artifact.txt:text/plain \
     ./docs/:application/vnd.acme.rocket.docs.layer.v1+tar`

### What is the version of your ORAS CLI?

oras version
Version:    0.16.0+Homebrew
Go version: go1.19.3

### What is your OS environment?

mac

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by shizhMSFT** [comment]
@TerryHowe @nima Could you help on this ECR case?

**Comment by TerryHowe** [comment]
While I do see a zero size in the console:
![Screen Shot 2023-02-10 at 08 14 58](https://user-images.githubusercontent.com/104113/218127398-cd27067d-4ad8-4586-8024-68bcbf487221.png)

When I pull it, I got my little artifact file and the contents of directory. I am using a newer version of oras though, but I think it is just that the ECR console isn't properly showing the size.
![Screen Shot 2023-02-10 at 08 17 55](https://user-images.githubusercontent.com/104113/218127822-824f14b7-02b2-4d8c-bada-fb7f1cfa670c.png)

**Comment by Noxsios** [comment]
I also fail to push to ECR:

```bash
$ echo "hello world" > hello-world.txt

$ oras push REGISTRY_URL \
    hello-world.txt:application/txt \
    --verbose
    
Preparing hello-world.txt
Uploading ecf701f727d9 hello-world.txt
Uploaded  ecf701f727d9 hello-world.txt
Uploading 40cafda804c4 application/vnd.oci.artifact.manifest.v1+json
Error: PUT "<REGISTRY_URL>/manifests/v2": response status code 405: unsupported: Invalid parameter at 'ImageManifest' failed to satisfy constraint: 'Invalid JSON syntax'
```

**Comment by qweeah** [comment]
> I also fail to push to ECR:

@Noxsios This is because OCI artifact is not supported in ECR yet. Try specifying an image via `--image-spec`
```
$ echo "hello world" > hello-world.txt

$ oras push REGISTRY_URL \
    hello-world.txt:application/txt \
    --verbose --image-spec v1.1-image
```

**Comment by Noxsios** [comment]
Interestingly enough, on subsequent attempts, I was able to push w/o needing `--image-spec`.  However In my implementation of using the `oras-go` lib, I am still getting a 405.  Performing the same operation using the oras CLI succeeds. Currently comparing the transport logs to compare the HTTP requests and see what I am missing. @qweeah

**Comment by arundeepkurni** [comment]
Able to push and pull in to ECR with `--config`:

push:

```
oras push -u AWS -p $(aws ecr get-login-password) \
     $REGISTRY:$OPA_BUNDLE \
     --config config.json:application/vnd.acme.rocket.config.v1+json \
     artifact.txt:text/plain \
     ./docs/:application/vnd.acme.rocket.docs.layer.v1+tar
```


Pull

`oras pull -u AWS -p $(aws ecr get-login-password) $REGISTRY:$OPA_BUNDLE`

**Comment by FeynmanZhou** [comment]
> Interestingly enough, on subsequent attempts, I was able to push w/o needing `--image-spec`. However In my implementation of using the `oras-go` lib, I am still getting a 405. Performing the same operation using the oras CLI succeeds. Currently comparing the transport logs to compare the HTTP requests and see what I am missing. @qweeah

@Noxsios @arundeepkurni  The flag `--image-spec` is designed to specify an OCI manifest type and solve the compatibility inconsistency with different registries, see [Compatibility mode for ORAS](https://github.com/oras-project/oras/blob/main/docs/proposals/compatibility-mode.md).  `--config` is a workaround before this `--image-spec` flag. Can you also try to push the manifest using the flag `--image-spec` to ECR?

**Comment by Noxsios** [comment]
@FeynmanZhou @arundeepkurni I was simply using the oras CLI to check that oras _could_ push to ECR.  After verifying this, I was able to pin down the issue in my usage of `oras-go`. The issue was that I was doing a `store.Add` to the config descriptor and not a `repo.Push` to create the config layer which led to discrepancies between the digests used.

**Comment by arundeepkurni** [comment]
@FeynmanZhou : 

Encountered **error** while using `--image-spec` instead `--config`

oras cli version below 
Version:    0.16.0+Homebrew
Go version: go1.19.3

**Comment by TerryHowe** [comment]
Can this be closed? It isn't entirely clear to me there is a problem here other than ECR is showing a zero size in the WUI even though the artifact is there and pulls fine. Seems like an ECR WUI problem.

**Comment by arundeepkurni** [comment]
Yes, we can close this issue.
