### ISSUE TITLE
Make public command level methods so users can script in go

### ISSUE THREAD

**Issue by TerryHowe** [oras-project/oras#807]
### What is the version of your ORAS CLI

1.0.0

### What would you like to be added?

Make cmd level methods public so that users can write scripts in go instead of shell. What would be required to do this is just expose the commands, associated options and some aspects of `cmd/oras/internal/option`. Users would create options and call the command. For example for `oras repo tags`, `showTagsOptions` and `showTags` would be made public. The user would also need a way to create a `Target`

### Why is this needed for ORAS?

Shell is pretty terrible to write, test and maintain. It would be a lot easier in go.

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by shizhMSFT** [comment]
Linking alternative solution #810

**Comment by sajayantony** [comment]
From previous discussions, anything made public and GA’d should technically be non breaking and also have test coverage. If there is valid ask and the community is able to come to an agreement that this would benefit the project and is ready to cost/implement then it makes sense to prioritize this item.

**Comment by shizhMSFT** [comment]
Based on the community call, Billy's cobra-based proposal is accepted. To implement, code refactoring work is required.

**Comment by qweeah** [comment]
This issue depends on https://github.com/oras-project/oras/issues/824.
