### ISSUE TITLE
support copying image referrers from index predecessor via `oras copy`

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#816]
Suppose we have an index directly pointing to several images with different platforms. Each image have an artifact attached as below:
```mermaid
graph TD
Z>v1] -..-> index
A["artifact(linux/s390x)"] -- subject --> B["image"]
C["artifact(linux/amd64)"] -- subject --> D["image"]
E["artifact(linux/arm64)"] -- subject --> F["image"]

index -- linux/s390x --> B
index -- linux/arm64 --> D
index -- linux/amd64 --> F

```

Using below command, oras user can copy all the images and artifacts into a new target (registry or image layout) and tag the index in the destination as `v2`:
```
oras cp $FROM:v1 $TO:v2 --recursive
```

**Comment by qweeah** [comment]
Moving this to future mile stone since the state-of-the-art practice is not clear in CSSC industry. E.g. can a certain arch image being distributed and verified without the multi-arch bundle? If not, the sbom and signature can be attach directly to the multi-arch bundle as below, and this feature is not needed.

```mermaid
graph TD
Z>v1] -..-> index
A["artifact(whole bundle)"] -- subject --> index

index -- linux/s390x --> B
index -- linux/arm64 --> D
index -- linux/amd64 --> F


```

**Comment by sajayantony** [comment]
if `--recursive` doesn't copy all the refereers for a related index then that is extra burden on the user. 
Recommen supporting.
