### ISSUE TITLE
support custom headers for `oras cp`

### ISSUE THREAD

**Issue by wangxiaoxuan273** [oras-project/oras#845]
# What happened in your environment?

run below command will get an error:
```bash
oras cp -H "a:b" ...
```

# What did you expect to happen?
oras cp should support --from-header and --to-header for source and destination registry.

# What is the version of your ORAS CLI?
Version: 1.0.0-rc.1
Go version: go1.19.5
Git commit: https://github.com/oras-project/oras/commit/a98931bc68a0e7a5de6c51df8e5aa09aadad3057
Git tree state: clean

# What is your OS environment?
ubuntu 20.04

**Comment by qweeah** [comment]
Also E2E test specs need to be added.
