### ISSUE TITLE
Additional test coverage

### ISSUE THREAD

**Issue by jdolitsky** [oras-project/oras#88]
add some unit tests for new code where there is none

**Comment by shizhMSFT** [comment]
Linking #388

**Comment by qweeah** [comment]
@shizhMSFT Do we have a quantified target for the coverage?

**Comment by shizhMSFT** [comment]
We can start with 80%.

**Comment by shizhMSFT** [comment]
Closing as unit tests have been added. @qweeah will add more E2E tests.
