### ISSUE TITLE
Vote for release of v1.0.0

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#896]
At least 3 approvals are needed from the 5 owners to cut [b58e7b9](https://github.com/oras-project/oras/commit/b58e7b910ca556973d111e9bd734a71baef03db2) as the release branch for oras CLI v1.0.0 release. This branch will be named as `release-1.0` and tagged as `v1.0.0` for releasing.

 - [x] Terry Howe (@TerryHowe)
 - [ ] Sajay Antony (@sajayantony)
 - [x] Shiwei Zhang (@shizhMSFT)
 - [x] Steve Lasker (@SteveLasker)
 - [x] Billy Zha (@qweeah)

The release will be conducted by following the [release checklist](https://oras.land/cli/5_developer_guide/#release-checklist). Comparing to [v1.0.0-rc.2](https://github.com/oras-project/oras/tree/v1.0.0-rc.2), the release includes below code changes:
- #822
- #861 
- #865 
- #869 
- #837
- #871 
- #866
- #874
- #873
- #878
- #882
- #885
- #888
- #886
- #889
- #890
- #892
- #880
- #894
- #895

**Comment by shizhMSFT** [comment]
LGTM

**Comment by SteveLasker** [comment]
LGTM

**Comment by qweeah** [comment]
Release branch https://github.com/oras-project/oras/tree/release-1.0 is created.
