### ISSUE TITLE
show distribution warning headers as output on the ORAS CLI

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#898]
### What is the version of your ORAS CLI

1.0.0

### What would you like to be added?

Registry implementations MAY include informational warnings in [warning headers](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#warnings), as described in [RFC 7234](https://www.rfc-editor.org/rfc/rfc7234#section-5.5). User should be able to verbosely show the returned warning headers in the output if a target is a remote registry.

### Why is this needed for ORAS?

With this feature, oras is enabled to report the server-side warnings to the user in an unobtrusive way.

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by shizhMSFT** [comment]
Linking https://github.com/oras-project/oras-go/issues/469
