### ISSUE TITLE
Pushing multiple container images in the same repo with Oras

### ISSUE THREAD

**Issue by radu-matei** [oras-project/oras#90]
Background: I'm looking at pushing [CNAB Bundles](https://github.com/deislabs/cnab-spec) to OCI registries using Oras - I am currently only pushing the bundle descriptor (a `bundle.json` file) using a custom media type, and the next step is to also push all container images referenced in the bundle.

Now, I could push the exported image archive, but the entire image would result in a single layer (not ideal when working with large images) - and I'm interested in how Oras deals with pushing (multiple) container images in the same repository.

Thanks!

**Comment by radu-matei** [comment]
Ideally, each container image would create a ditribution manifest/manifest list, with the original name and other info as annotations?

**Comment by shizhMSFT** [comment]
As [Transmitting Thick Bundles](https://github.com/deislabs/cnab-spec/blob/master/104-bundle-formats.md#transmitting-thick-bundles) mentioned, you may decompose thick bundles for the purpose of efficiently transmitting them.

**Comment by shizhMSFT** [comment]
For thin bundles, it just a `bundle.json` with image references. For referenced docker images, you can do normal `docker push` to a registry or the same repository with different tags. Currently, `oras` does not support manifest list well.

**Comment by radu-matei** [comment]
Ok, thanks a lot for the response here.

I'm able to push the images separately and reference them, but it would be really cool to see support for an OCI index.
Is there anything specifically blocking? How could I help?

See https://github.com/radu-matei/coras/issues/8 for more context.

Thanks!

**Comment by shizhMSFT** [comment]
A manifest list should contain manifest only. Also, `oras` does support upload multiple files in a single manifest.

**Comment by jdolitsky** [comment]
@radu-matei @shizhMSFT just checking in, is there any request for new functionality here? It sounds like the original ask is possible?

**Comment by radu-matei** [comment]
Continuing on the background about CNAB - when we push a bundle using `oras`, we might also want to push the container images referenced in the bundle. 
However, regardless of how many other images are in the same repository (under different tags), the resulting manifest created by `oras` only contains the layer pointing to the bundle file.

While functionally it has no impact, it would be great for the resulting manifest to contain both the bundle and other image manifests - so `oras` would generate an OCI index, as opposed to a single image config.

**Comment by shizhMSFT** [comment]
According to the [OCI Image Index Specification](https://github.com/opencontainers/image-spec/blob/master/image-index.md), the image index is a higher-level manifest which points to specific image manifests. Therefore, it is not a good idea to store non-manifest in a manifest list.

I understand that having everything in a single tag will be grateful. Here is my proposal to your problem.

---

A thin CNAB is a `bundle.json` file. It can be pushed by `oras` as a single manifest. All its referenced images can be pushed by `docker` or other tools as individual manifest.

A fat CNAB can be viewed as a collection of the thin CNAB and its referenced images. Naturally, a fat CNAB is a signel manifest list / index of the manifest of the thin CNAB and its referenced images.
```
manifest index (fat CNAB)
 |- oras manifest (thin CNAB)
 |    |- config
 |    |- layer (bundle.json)
 |- image manifest A
 |- image manifest B
 |- image manifest C
```

---

Overall, the feature we need is to combine multiple manifests to be a single manifest index. However, it's more like a manifest managment feature other than a feature for `oras`.

@jdolitsky @sajayantony  Any comments?

**Comment by sajayantony** [comment]
The docker manifest create command handles building of manifest lists. Enabling ORAS to support manifest list does make sense if it fulfills CNABs spec. 
The OCI Index may be considered different from a manifest list and by definition is an index of things rather than a list of manifest. I think that’s what CNAB is might be going for and I don’t know the Spec enough to comment.
The one interesting thing to consider is that CNAB pull push should consider moving all elements of the index unlike docker pull push which only gets a single matching architecture.

**Comment by SteveLasker** [comment]
@radu-matei, I believe the ask here is to add Index support?
That will come as part of the [Notary v2](https://github.com/notaryproject/nv2/pull/10) work

**Comment by shizhMSFT** [comment]
Closing as the issue content seems to be outdated. Please re-open if needed.
