### ISSUE TITLE
add OCI layout support in command help doc

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#904]
### What happened in your environment?

Below command do support operating an OCI layout folder, but the short and long description only mentioned the support for remote registry
- `oras discover`
- `oras pull`
- `oras push`
- `oras tag`
- `oras blob`
- `oras blob push`
- `oras blob fetch`
- `oras manifest`
- `oras manifest push`
- `oras manifest fetch`
- `oras manifest fetch-config`

### What did you expect to happen?

Short and long description of below commands should mention OCI layout support. 
- `oras discover`
- `oras pull`
- `oras push`
- `oras tag`
- `oras blob`
- `oras blob push`
- `oras blob fetch`
- `oras manifest`
- `oras manifest push`
- `oras manifest fetch`
- `oras manifest fetch-config`

### How can we reproduce it?

Run `<command> -h`

### What is the version of your ORAS CLI?

1.0.0

### What is your OS environment?

20.04

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by FeynmanZhou** [comment]
Agree. Do we need to update the CLI help info in the ORAS CLI code repo either?

**Comment by qweeah** [comment]
> Do we need to update the CLI help info in the ORAS CLI code repo either?

Yes, this issue is to track changes in ORAS CLI code

>  it's recommended that create a separate guide to elaborate on the OCI layout usage.

Indeed, but the short description should not be limited to registry only, e.g. for `oras discover` the description is `Discover referrers of a manifest in the remote registry
` should be sth like `Discover referrers of an artifact`

**Comment by rafiya2003** [comment]
I would like to work on this, frankly I don't know much but I will learn and do. I am a newbie(first year UG student). I want to learn and grow. please give me the opportunity to learn and experience

**Comment by qweeah** [comment]
@rafiya2003 Hi Rafiya, welcome to oras & thanks for your interest. This issue is critical for the upcoming release 1.1.0, so considering the urgency of the time it's not suitable for new contributors.

If you are interested, do you like to work on https://github.com/oras-project/oras/issues/742? It's also a good first issue and not included in 1.1.0 release.
