### ISSUE TITLE
add command to get the digest of a tagged manifest without parsing output

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#907]
### What is the version of your ORAS CLI

1.0.0

### What would you like to be added?

Add a new command to get the digest of a tagged manifest as below:
```console
$ oras resolve -h
Resolves digest of the target artifact

Usage:
  oras resolve [flags] <name>:<tag>

Aliases:
  digest

Flags:
      --ca-file string                              server certificate authority file for the remote registry
  -d, --debug                                       debug mode
      --descriptor                                  output a descriptor of the artifact
      --full-ref                                    print the full artifact reference with digest
  -H, --header stringArray                          add custom headers to requests
  -h, --help                                        help for resolve
      --insecure                                    allow connections to SSL registry without certs
      --media-type strings                          accepted media types
      --oci-layout                                  set target as an OCI image layout
  -p, --password string                             registry password or identity token
      --password-stdin                              read password or identity token from stdin
      --plain-http                                  allow insecure connections to registry without SSL check
      --platform os[/arch][/variant][:os_version]   request platform in the form of os[/arch][/variant][:os_version]
      --pretty                                      prettify JSON objects printed to stdout
      --registry-config path                        path of the authentication file for registry
      --resolve host:port:address[:address_port]    customized DNS for registry, formatted in host:port:address[:address_port]
  -u, --username string                             registry username
  -v, --verbose                                     verbose output
```

**Examples**
- Resolve digest of `docker.io/library/hello-world:latest`
```console
$ oras resolve docker.io/library/hello-world:latest
sha256:ffb13da98453e0f04d33a6eee5bb8e46ee50d08ebe17735fc0779d0349e889e9
```
- Resolve full reference of `docker.io/library/hello-world:latest` with digest
```console
$ oras resolve docker.io/library/hello-world:latest --full-ref
docker.io/library/hello-world@sha256:ffb13da98453e0f04d33a6eee5bb8e46ee50d08ebe17735fc0779d0349e889e9
```

### Why is this needed for ORAS?

This will increase the usability of oras in CI/CD jobs.

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by TerryHowe** [comment]
How about just call it `digest` instead of as an alias?

**Comment by qweeah** [comment]
To me, `resolve` is a verb and aligns more to current command naming convention.

**Comment by shizhMSFT** [comment]
> To me, `resolve` is a verb and aligns more to current command naming convention.

The last command should be a verb so that it sounds like a nature language. Say... `oras resolve <something>`.

**Comment by shizhMSFT** [comment]
In general, `oras` follows [subject-verb-object word order](https://en.wikipedia.org/wiki/Subject%E2%80%93verb%E2%80%93object_word_order) where `oras` is the subject, `<command>` is the verb and `<reference>` is the object.

**Comment by rafiya2003** [comment]
I would like to work on this, frankly I don't know much but I will learn and do. I am a newbie(first year UG student). I want to learn and grow. please give me the opportunity to learn and experience

**Comment by qweeah** [comment]
@rafiya2003 This issue requires knowledge on
- Cobra: the framework we used to build CLI, you might want to start with https://cobra.dev/#getting-started
- oras-go: the golang SDK oras CLI used to interact with registries and oci layout stores. You might want to start with sdk examples in [godoc](https://pkg.go.dev/oras.land/oras-go/v2#pkg-examples) or [oras.land](https://oras.land/docs/Client_Libraries/go)

**Comment by rafiya2003** [comment]
@qweeah  can you plz suggest me some issues

**Comment by qweeah** [comment]
@rafiya2003 #742 is similar to this but much simpler.

**Comment by sajayantony** [comment]
Would be interesting if we can support format parameter as well for formats that are used in other places like . `{{.Registry}}/{{.Repository}}:{{.Tag}}@{{.Digest}}`

**Comment by amands98** [comment]
I am up for taking this item.
