### ISSUE TITLE
Update `github.com/moby/term` to `golang.org/x/term`

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras#908]
### What is the version of your ORAS CLI

v1.0.0

### What would you like to be added?

Update `github.com/moby/term` to `golang.org/x/term`

### Why is this needed for ORAS?

`oras` uses untagged version of `github.com/moby/term` for reading passwords in `oras login` since the package `term` does not have any tags.

https://github.com/oras-project/oras/blob/67dca8e1d5a9f6c3dae7a5eb61719a94155aab21/go.mod#L7

By updating to `golang.org/x/term`, we can also remove the dependencies on 

https://github.com/oras-project/oras/blob/67dca8e1d5a9f6c3dae7a5eb61719a94155aab21/go.mod#L19

and

https://github.com/oras-project/oras/blob/67dca8e1d5a9f6c3dae7a5eb61719a94155aab21/go.mod#L25

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by qweeah** [comment]
I can work on this. Just refactoring `oras login` code to make E2E cover manual input scenario.
