### ISSUE TITLE
Simplify installation process for windows by using `winget`

### ISSUE THREAD

**Issue by asilverman** [oras-project/oras#939]
### What would you like to be added?

Currently, the installation process for Windows is pretty involved...

[winget-cli](https://github.com/microsoft/winget-cli) is a package manager for windows and it is pre-installed in most windows distributions. I would really like to be able to install oras client by leveraging `winget`

### Why is this needed for ORAS?

It reduces the barriers for adoption and makes installation simpler

### Are you willing to submit PRs to contribute to this feature?

- [x] Yes, I am willing to implement it.

**Comment by FeynmanZhou** [comment]
@asilverman Awesome! I just tested installing ORAS v1.0.0 on Win11 using Winget and it works fine!
We will add this installation method to the [ORAS installation guide](https://oras.land/docs/cli/installation/#windows).

**Comment by sajayantony** [comment]
Should we close this issue since the instructions have been merged or are there more follow up items?

**Comment by asilverman** [comment]
@sajayantony I would suggest that a CI/CD step is added to the release pipeline of ORAS to update the package when a new version is released, this will not happen otherwise

**Comment by sajayantony** [comment]
winget releaser seems like a nice option then. I in that case this isn’t currently triaged or assigned and maybe we can queue this up in the next patch update.

**Comment by FeynmanZhou** [comment]
@asilverman Good idea. I think we may need to add a `release-winget/yml` to [ORAS GitHub Actions](https://github.com/oras-project/oras/tree/main/.github/workflows) to cover Winget package update when a new version is released. 

cc @oras-project/oras-cli

**Comment by amands98** [comment]
I can add the github actions, but I may need someone to create secrets and other admin items.

**Comment by qweeah** [comment]
It's completed and future improve can be found in #1025
