### ISSUE TITLE
Incorrect Link in File: CONTRIBUTING.md

### ISSUE THREAD

**Issue by yash7raut** [oras-project/oras#950]
### What happened in your environment?

The file CONTRIBUTING.md contains an incorrect link that needs to be corrected. The current link is leading to an incorrect destination, causing confusion and hindering the intended functionality. This issue aims to rectify the link and ensure it points to the correct location.

### What did you expect to happen?

The link in CONTRIBUTING.md is currently pointing to an incorrect web page, leading to confusion for users. To resolve this issue, the link should be updated to direct users to the correct web page. The correct destination URL should be provided, ensuring that when users click on the link, they are directed to the intended web page with accurate and relevant information.

### How can we reproduce it?

To reproduce this issue, follow these steps:

1. Visit the following URL: https://github.com/oras-project/oras/blob/main/CONTRIBUTING.md.
2. Within the file, locate the specific link.
3. Click on the link.

The link currently redirects to the wrong page, leading to an incorrect destination.

![Screenshot from 2023-05-18 00-00-40](https://github.com/oras-project/oras/assets/73844713/19be2561-6a25-4ea5-b1e5-47399502e678)

### What is the version of your ORAS CLI?

oras version:        1.0.0

### What is your OS environment?

Ubuntu 22.04.2

### Are you willing to submit PRs to fix it?

- [X] Yes, I am willing to fix it.

**Comment by qweeah** [comment]
Good catch! Thanks @yash7raut
