### ISSUE TITLE
improve path traversal error msg of `oras pull` 

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#978]
If path of artifact blobs are absolute and needs to be pulled outside of current working directory, by default `oras pull` will be terminated with error like `path traversal disallowed`

Need to advise user action for this specific error, like `Use pull with option -T/allow-path-traversal to allow path traversal`

> Can this be added to the error message when the pull fails with "Path travel disallowed". Use pull with option -T or --allow-path-traversal to allow path traversal.

_Originally posted by @suganyas in https://github.com/oras-project/oras/issues/973#issuecomment-1596433851_

**Comment by qweeah** [comment]
@suganyas Can you help fix this issue？

**Comment by suganyas** [comment]
@qweeah I am working on this as part of PR #988

**Comment by qweeah** [comment]
completed in https://github.com/oras-project/oras/pull/988
