### ISSUE TITLE
add Github actions to lint go code

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#981]
### What is the version of your ORAS CLI

1.0.0

### What would you like to be added?

Use [existing Github](https://github.com/golangci/golangci-lint) to do static code formatting scan for pull requests.

### Why is this needed for ORAS?

As the number of contributor grows, adding such a CI job will help unifying coding style.

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by FeynmanZhou** [comment]
@kranurag7 Thanks for your interest!

**Comment by qweeah** [comment]
> @kranurag7 Thanks for your interest!
> 
> @qweeah Do you think we could assign this issue to @kranurag7 ?

Yes of course.
